// Catalogue anglais (PLAN-LANGUES, A15) : transposition de la grammaire
// du prototype, jamais une invention — mêmes clés que catalogue.fr.js,
// l'audit e2e casse au moindre écart. Les guillemets « » deviennent
// “ ”, l'heure reste sur 24 h (on livre une langue, pas une locale).

export const EN = {
  // --- Dossiers canoniques (nav, statut, conversation) ----------------
  'boite.reception': 'Inbox',
  // RETOURS-13 R3 : the organized mode keeps the short name.
  'boite.receptionOrganisee': 'Inbox',
  // PLAN-MODE-ORGANISE E1 — the organized-mode views (HEY-inspired names).
  'boite.kiosque': 'Feed',
  'boite.registre': 'Paper trail',
  'boite.portier': 'Screener',
  'boite.envoyes': 'Sent',
  'boite.brouillons': 'Drafts',
  'boite.indesirables': 'Junk',
  'boite.archives': 'Archives',
  'boite.corbeille': 'Trash',
  'nav.toutes': 'All inboxes',
  'nav.boites': 'Inboxes',
  'nav.aria': 'Folders and accounts',

  // --- Entête de l'écran 02 -------------------------------------------
  'entete.recherche': 'Search',
  'entete.chercher': 'Search messages, people, files',
  'entete.effacerRecherche': 'Clear search',
  'entete.ecrire': 'Compose',
  'entete.organise': 'Organized',
  'action.deplacerVers': 'Move to…',
  'toast.expediteurDeplace': 'Sender moved to {boite}: their messages follow.',
  'erreur.sansAdresse': 'This message has no sender address.',

  // --- The Screener (PLAN-MODE-ORGANISE E2) ---------------------------
  'portier.sousTitre1': 'These senders are writing to you for the first time.',
  'portier.sousTitre2': 'Do you allow them to contact you?',
  'portier.sousTitre3': 'Senders will never be told of your decision.',
  'portier.question': 'Do you want to receive their messages?',
  'portier.oui': 'Yes',
  'portier.non': 'No',
  'portier.ouiChoix': 'Yes, choosing the destination',
  'portier.nonChoix': 'No, choosing the rule',
  'portier.ouiVers': 'Yes, and their messages go to…',
  'portier.nonSeront': 'No, and their messages will be…',
  'portier.versReception': 'The Inbox',
  'portier.versKiosque': 'The Feed',
  'portier.versRegistre': 'The Paper trail',
  'portier.laReception': 'the Inbox',
  'portier.leKiosque': 'the Feed',
  'portier.leRegistre': 'the Paper trail',
  'portier.regleSpam': 'Marked as junk',
  'portier.regleArchive': 'Archived automatically',
  'portier.regleCorbeille': 'Moved automatically to the Trash',
  'portier.regleEcarte': 'Screened out without moving',
  'portier.vide': 'No one is waiting at the Screener. New senders will appear here.',
  'portier.historique': 'Screener history',
  'portier.historiqueVide':
    'You have not screened out any senders yet.',
  'portier.reintegrer': 'Reinstate',
  // RETOURS-14 R4 (D5): the mixed-thread marker.
  'fil.attentePortier': 'Awaiting the Screener',
  'portier.ecarte': 'screened out',
  'portier.ecarteSpam': 'screened out (marked as junk)',
  'portier.ecarteArchive': 'screened out (archived automatically)',
  'portier.ecarteCorbeille': 'screened out (deleted automatically)',
  'toast.portierOuiNu': '{qui} can write to you: their messages arrive in the Inbox.',
  'toast.portierOuiVers': '{qui} can write to you: their messages go to {boite}.',
  'toast.portierNonNu': '{qui} is screened out; they will never know.',
  'toast.portierNonSpam': '{qui} is screened out; their next messages will go to Junk.',
  'toast.portierNonArchive':
    '{qui} is screened out; their next messages will be archived automatically.',
  'toast.portierNonCorbeille':
    '{qui} is screened out; their next messages will go to the Trash.',
  // E4 — the organized Inbox: sections and per-row gestures.
  // RETOURS-14 R6: a Paper trail group row counts THREADS.
  'registre.fil': '{n} conversation',
  'registre.fils': '{n} conversations',
  'registre.voirPlus': 'Show more',
  // RETOURS-14 R9: the section sort button (4-state cycle).
  'tri.dateDesc': 'Newest first',
  'tri.dateAsc': 'Oldest first',
  'tri.alphaAZ': 'Sender A → Z',
  'tri.alphaZA': 'Sender Z → A',
  'tri.aria': 'Change the section sort',
  'liste.sectionNouveau': 'New for you · {n}',
  'liste.sectionConsulte': 'Previously seen',
  'liste.gestes': 'Actions on this message',
  'liste.deplacerVers': 'Move to {boite}',
  'liste.ecarter': 'Screen out this sender',
  // E5 — Set Aside: the pile, the fan, the board.
  'pile.misDeCote': 'Set aside',
  'pile.mettre': 'Set aside',
  'pile.reprendre': 'Bring back',
  'pile.voirTableau': 'See the board',
  'pile.ouvrir': 'Open',
  'pile.tableauTitre': 'The Set Aside board',
  'pile.tableauNote':
    'Everything you set aside, at a glance on one screen. \u201cDone\u201d sends the message back where it came from.',
  'pile.tableauVide': 'The pile is empty.',
  'pile.aria': 'Set-aside messages',
  'toast.misDeCote': 'Set aside: the pile lives at the bottom right of the Inbox.',
  'toast.reprisPile': 'Brought back from the pile.',
  // E5bis — the Feed as cards; header and sections RETOURS-13 R10/R11.
  'kiosque.sousTitre1': 'All your informational emails are gathered here.',
  'kiosque.sousTitre2': 'Just scroll through them to read.',
  'kiosque.sectionNonLus': 'Unread',
  'kiosque.sectionLus': 'Previously read',
  'kiosque.toutLu': 'You have read all the new stories in your Feed.',
  'kiosque.vide':
    'Nothing in the Feed. From a message, “Move to the Feed” sends that sender’s newsletters here.',
  'toast.portierReintegre':
    '{qui} is reinstated; their messages from the last 90 days reappear at the Screener.',
  'groupe.portier': 'Screener',
  'reglages.portierDesc':
    'The default actions of the Screener buttons. The mini ⋯ on each button still offers a one-off choice.',
  'reglages.portierOui': 'The “Yes” button',
  'reglages.portierOuiDesc': 'Where an allowed sender’s messages go.',
  'reglages.portierNon': 'The “No” button',
  'reglages.portierNonDesc':
    'What happens to a screened-out sender’s next messages.',
  // RETOURS-14 R5 (D6): the exhaustive list of decisions.
  'reglages.portierDecisions': 'Decisions by sender',
  'reglages.portierDecisionsDesc':
    'Every decision made at the Screener, in alphabetical order. Reinstating a sender will present them at the Screener again on their next message.',
  'reglages.portierModifier': 'Edit',
  'reglages.renvoyerPortier': 'Send back to the Screener',
  'reglages.portierRecherche': 'Search for a sender',
  'reglages.portierAucuneDecision': 'No decisions yet.',
  'reglages.portierAucunResultat': 'No sender matches.',
  'entete.reglages': 'Settings',
  'entete.feedback': 'Feedback',
  'retour.titre': 'Feedback',
  'retour.sous':
    'Tell us what is broken or missing in this form. When you click Send, it forwards your feedback by email to feedback-wind@fcts.io. We read every piece of feedback; it is invaluable to us!',
  'retour.placeholder': 'Your feedback…',
  'retour.merci': 'Thank you for your feedback!',

  // --- Barre de statut --------------------------------------------------
  'statut.recherche': 'Search · {n} result|Search · {n} results',
  'statut.recherchePlafond': 'Search · {n} of {total} result|Search · {n} of {total} results',
  'statut.categorie': '{boite} · {n} item|{boite} · {n} items',
  'statut.synchro': 'Syncing · {p}%',
  'statut.rattrapageCorps': 'Catching up on messages · {n} to go · {p} %',
  'statut.rattrapageCorpsSeul': 'Catching up on messages · {n} to go',
  'statut.rattrapageApercus': 'Catching up on previews…',
  'statut.envois': 'Outbox · {n} message waiting|Outbox · {n} messages waiting',
  'statut.programmes':
    'Outbox · {n} message scheduled · leaves {quand}|Outbox · {n} messages scheduled · next leaves {quand}',
  'statut.synchroImpossible': 'Sync failed · will retry automatically',
  'statut.synchroImpossibleDepuis':
    'Sync failed · will retry automatically · last synced {depuis}',
  'statut.ajour': 'All messages are up to date',
  'statut.ajourDepuis': 'All messages are up to date · last synced {depuis}',
  'statut.horsLigne': 'Offline',
  'statut.horsLigneDepuis': 'Offline · last synced {depuis}',
  'statut.cyclePrefixe': 'Syncing',
  'statut.synchroPartielle':
    '{n} account of {m} unreachable · will retry automatically|{n} accounts of {m} unreachable · will retry automatically',
  'statut.pourcent': '{p}%',
  'statut.phase.inventaire': 'folder inventory',
  'statut.phase.fils': 'conversation threads',
  'statut.phase.brouillons': 'drafts',
  'depuis.instant': 'just now',
  'depuis.minutes': '{n} minute ago|{n} minutes ago',
  'depuis.heures': '{n} hour ago|{n} hours ago',
  'depuis.jours': '{n} day ago|{n} days ago',
  'statut.demarrage': 'starting…',
  'statut.perf': '{total} conversations · first page served+rendered in {ms} ms',

  // --- Fente d'avis -----------------------------------------------------
  'avis.envoiRefuse': 'The message “{sujet}” was rejected{erreur}.',
  'avis.envoiInterrompu': 'The message “{sujet}” was interrupted{erreur}.',
  'avis.maj': 'An update is available (version {version}).',
  'avis.crash': 'Wind ran into a problem during a previous session ({n} report(s) pending). Nothing is sent without you.',
  'avis.telemetrie': 'Help improve Wind? If it crashes, a technical report would be saved on your machine, never the content of your mail. You then choose whether to send it.',
  'avis.connexion': 'Account not reconnected: {details}',
  'avis.programme': '“{sujet}” will be sent {quand}, if Wind is open at that time.',
  'avis.actionsRefusees': '{n} action refused by the server (folder not found or rejected): the message stayed where it was.|{n} actions refused by the server (folder not found or rejected): the messages stayed where they were.',

  // --- Actions partagées ------------------------------------------------
  'action.renvoyer': 'Send again',
  'action.abandonner': 'Discard',
  'action.installer': 'Install',
  'action.plusTard': 'Later',
  'action.ouvrirRapports': 'Open the reports folder',
  'action.ignorer': 'Dismiss',
  'action.activer': 'Turn on',
  'action.nonMerci': 'No thanks',
  'action.reprendre': 'Resume',
  'action.reessayer': 'Try again',
  'action.synchroniser': 'Sync',
  'action.synchronisation': 'Syncing…',
  'action.repondre': 'Reply',
  'action.repondreTous': 'Reply all',
  'action.transferer': 'Forward',
  'action.archiver': 'Archive',
  'action.signalerSpam': 'Report as spam',
  'action.pasSpam': 'Not spam',
  'action.epingler': 'Pin',
  'action.desepingler': 'Unpin',
  'action.supprimer': 'Delete',
  'action.envoyer': 'Send',
  'action.annuler': 'Cancel',
  'action.continuer': 'Continue',
  'action.fermer': 'Close',
  'action.replier': 'Collapse',
  'action.deplier': 'Expand',
  'action.retirer': 'Remove',
  'action.termine': 'Done',
  'action.annulerEnvoi': 'Cancel send',
  'action.enregistrer': 'Save',
  'action.effacer': 'Clear',
  'action.accepter': 'Accept',
  'action.provisoire': 'Tentative',
  'action.refuser': 'Decline',
  // PLAN-RETOURS-10 R1 : la barre de sélection multiple.
  'action.marquerLu': 'Mark as read',
  'action.marquerNonLu': 'Mark as unread',
  'action.annulerSelection': 'Cancel selection',

  // --- Invitation card (PLAN-INVITATIONS) -------------------------------
  'inv.kicker': 'Invitation',
  'inv.kickerAnnulee': 'Invitation cancelled',
  'inv.kickerReponse': 'Reply to your invitation',
  'inv.sansReponse': 'You have not replied',
  'inv.vous_accepte': 'You accepted',
  'inv.vous_provisoire': 'You tentatively accepted',
  'inv.vous_refuse': 'You declined',
  'inv.repondant_accepte': '{qui} accepted',
  'inv.repondant_provisoire': '{qui} tentatively accepted',
  'inv.repondant_refuse': '{qui} declined',
  'inv.repondant_sans_reponse': '{qui} replied',
  'inv.annuleeTexte': 'The meeting was cancelled by the organiser.',
  'inv.lieuOrganisateur': '{lieu} · organised by {qui}',
  'inv.organisePar': 'Organised by {qui}',
  'inv.seRepete': 'repeats',
  'inv.heureLocale': 'organiser’s local time',
  'inv.sujet_accepte': 'Accepted: {titre}',
  'inv.sujet_provisoire': 'Tentative: {titre}',
  'inv.sujet_refuse': 'Declined: {titre}',
  'inv.puce_accepte': 'Accepted',
  'inv.puce_provisoire': 'Tentative',
  'inv.puce_refuse': 'Declined',
  'inv.puce_annulee': 'Cancelled',

  // --- Toasts -----------------------------------------------------------
  'toast.compteAjoute': 'Account added.',
  'toast.compteRetire': 'Account removed.',
  'toast.archivee': 'Conversation archived.',
  'toast.supprimee': 'Conversation deleted.',
  'toast.messageSupprime': 'Message deleted.',
  'toast.spamSignale': 'Reported as spam.',
  'toast.pasSpam': 'Moved back to Inbox.',
  // PLAN-RETOURS-10 R1 : les gestes de masse — UN toast par lot.
  'toast.groupeArchivees': 'Conversation archived.|{n} conversations archived.',
  'toast.groupeSupprimees': 'Message deleted.|{n} messages deleted.',
  'toast.groupeSpam': 'Conversation reported as spam.|{n} conversations reported as spam.',
  'toast.groupePasSpam': 'Conversation moved back to Inbox.|{n} conversations moved back to Inbox.',
  'toast.groupeLues': 'Conversation marked as read.|{n} conversations marked as read.',
  'toast.groupeNonLues': 'Conversation marked as unread.|{n} conversations marked as unread.',
  'erreur.groupePartiel': '{faits} of {total}; the rest failed.',
  'toast.pieceEnregistree': 'Attachment saved: {chemin}',
  'toast.brouillonEnregistre': 'Draft saved.',
  'toast.brouillonSupprime': 'Draft deleted.',
  'toast.brouillonFork': 'This draft had changed elsewhere; your version was kept separately.',
  'toast.envoye': 'Message sent.',
  'toast.programme': 'Send scheduled: leaves {quand}.',
  'toast.envoiAnnule': 'Send cancelled: the message is back in your drafts.',
  'toast.signature': 'Signature saved.',
  'toast.signatureTous': 'Signature and choice applied to all accounts.',
  'toast.echoAttente': 'Copy still syncing: try again in a moment.',

  // --- Enveloppes d'erreur (le détail du cœur reste verbatim, L-3) -----
  'erreur.spamImpossible': 'This account has no spam folder.',
  'erreur.renvoi': 'Could not resend: {err}',
  'erreur.abandon': 'Could not discard: {err}',
  'erreur.maj': 'Update failed: {err}',
  'erreur.ouverture': 'Could not open: {err}',
  'erreur.preference': 'Preference not saved: {err}',
  'erreur.enregistrement': 'Could not save: {err}',
  'erreur.transfert': 'Could not forward: {err}',
  'erreur.repondreTous': 'Could not reply all: {err}',
  'erreur.envoi': 'Could not send: {err}',
  'erreur.invitation': 'The reply was not sent: {err}',
  'erreur.piece': 'Could not attach: {err}',
  'erreur.piecesManquantes':
    'Some forwarded files are still missing: wait for retrieval, try again, or remove them before sending.',
  'erreur.aucunCompte': 'No sending account: add an account.',
  'erreur.connexion': 'Could not connect: {err}',
  'erreur.differePasse': 'Pick a time in the future.',
  'erreur.annulerEnvoi': 'Could not cancel: {err}',
  'erreur.annulerTard': 'Too late: the message already left.',
  'erreur.signature': 'Signature not saved: {err}',

  // --- Liste ------------------------------------------------------------
  'liste.aria': 'Message list',
  'liste.aucunResultat': 'No results.',
  'liste.vide': 'No messages here.',
  'liste.chargerPlus': 'Show the next result|Show the next {n} results',
  'liste.affiner': 'Refine your search (from:, to:, date:) to go further.',
  'liste.prefixeBrouillon': 'Draft: ',
  'liste.dest': 'To: {a}',
  // A80, décision D10 : « Camille Roux in Work » — la boîte est un
  // contenant, pas un support.
  'liste.sur': 'in',
  // PLAN-RETOURS-10 R1 : la sélection multiple.
  'liste.nSelection': '{n} selected|{n} selected',
  'liste.cocher': 'Select the conversation',
  'brouillons.a': 'To: {a}',
  'brouillons.sansDestinataire': '(no recipient)',
  'brouillons.sansObjet': '(no subject)',
  'puce.messages': '{n} message|{n} messages',
  'puce.fichiers': '{n} file|{n} files',
  'puce.epingle': 'Pinned',
  'onglet.tous': 'All',
  'onglet.nonlus': 'Unread',

  // --- Volet de lecture -------------------------------------------------
  'lecture.aria': 'Message',
  'lecture.vide': 'Select a message to read it.',
  'lecture.ouvrir': 'Open',
  'lecture.corpsEchec': 'This message could not be loaded.',
  'lecture.imagesBloquees': '{n} remote image blocked to protect your privacy.|{n} remote images blocked to protect your privacy.',
  'lecture.afficherImages': 'Show images',
  'lecture.toujoursAfficherImages': 'Always show images from this sender',
  'lecture.corps': 'Message content',
  'lecture.enregistrer': 'Save…',
  'lecture.voileEnregistrer': 'Save',

  // --- Conversation (écran 03) ------------------------------------------
  'conv.deplier': 'Expand all',
  'conv.replier': 'Collapse all',
  'conv.brouillon': 'Draft',
  'conv.ligneA': 'To: {liste}',
  'conv.ligneCc': 'Cc: {liste}',
  'conv.de': 'From',
  'conv.a': 'To',
  'conv.objet': 'Subject',
  'conv.fichiersJoints': 'Attachments',

  // --- Composition ------------------------------------------------------
  // Reconnexion d'un compte au jeton mort (constat terrain 2026-08-20).
  'reglages.deconnecte': 'Disconnected',
  'reglages.reconnecter': 'Reconnect',
  'reglages.reconnecterCompte': 'Reconnect {email}',
  'reglages.reconnexionEnCours': 'Waiting for consent…',
  'reglages.reconnexionImpossible': 'Reconnection failed: {err}',
  'reglages.repereCompte': 'Marker for {email}',
  'reglages.repereTitre': 'Account icon and color',
  'reglages.repereIcones': 'Marker icon',
  'reglages.repereTeintes': 'Marker color',
  'reglages.repereRetirer': 'Remove marker',
  'reglages.repereImpossible': 'Marker not saved: {err}',
  // PLAN-RETOURS-9 : le retrait se dit (D2), le nom personnalisé (D3).
  'reglages.retirer': 'Remove account',
  'reglages.nommerCompte': 'Name {email}',
  'reglages.nomTitre': 'Account name',
  'reglages.nomImpossible': 'Name not saved: {err}',
  'repere.icone.home': 'Home',
  'repere.icone.work': 'Work',
  'repere.icone.school': 'School',
  'repere.icone.star': 'Star',
  'repere.icone.favorite': 'Heart',
  'repere.icone.flight': 'Travel',
  'repere.icone.shopping_bag': 'Shopping',
  'repere.icone.account_balance': 'Bank',
  'repere.icone.sports_esports': 'Games',
  'repere.icone.eco': 'Nature',
  'repere.icone.pets': 'Pets',
  'repere.icone.music_note': 'Music',
  'repere.teinte.rouge': 'Red',
  'repere.teinte.orange': 'Orange',
  'repere.teinte.ocre': 'Ochre',
  'repere.teinte.olive': 'Olive',
  'repere.teinte.vert': 'Green',
  'repere.teinte.sapin': 'Pine',
  'repere.teinte.bleu': 'Blue',
  'repere.teinte.indigo': 'Indigo',
  'repere.teinte.violet': 'Purple',
  'repere.teinte.magenta': 'Magenta',
  'repere.teinte.rose': 'Pink',
  'repere.teinte.brun': 'Brown',

  'compo.nouveau': 'New message',
  'compo.re': 'Re: {sujet}',
  'compo.tr': 'Fwd: {sujet}',
  'compo.bonjour': 'Hello {prenom},',
  'compo.sansObjet': 'no subject',
  'compo.compteEmetteur': 'Sending account',
  'compo.destinataire': 'Recipient',
  'compo.suggestions': 'Suggested addresses',
  'compo.objetPlaceholder': 'Message subject',
  'compo.corpsPlaceholder': 'Your message…',
  'compo.cc': 'Cc',
  'compo.cci': 'Bcc',
  // Barre de mise en forme réelle (PLAN-COMPOSITION-HTML, R4). Lien et
  // Citation RETIRÉS (décision CE D1 : périmètre strict).
  'compo.police': 'Font',
  'compo.policeSans': 'Sans serif',
  'compo.policeSerif': 'Serif',
  'compo.policeMono': 'Monospace',
  'compo.taille': 'Size',
  'compo.taillePetit': 'Small',
  'compo.tailleNormal': 'Normal',
  'compo.tailleGrand': 'Large',
  'compo.tailleTresGrand': 'Extra large',
  'compo.gras': 'Bold',
  'compo.italique': 'Italic',
  'compo.souligne': 'Underline',
  'compo.barre': 'Strikethrough',
  'compo.couleur': 'Text color',
  'compo.alignerGauche': 'Align left',
  'compo.alignerCentre': 'Center',
  'compo.alignerDroite': 'Align right',
  'compo.listePuces': 'Bulleted list',
  'compo.listeNumerotee': 'Numbered list',
  'compo.retraitMoins': 'Decrease indent',
  'compo.retraitPlus': 'Increase indent',
  'compo.effacerFormat': 'Clear formatting',
  'compo.joindre': 'Attach',
  'compo.retirerPiece': 'Remove {nom}',
  'compo.rapatriement': '{nom} · retrieving…',
  'compo.poidsTotal': '{poids} / 25 MB',
  'compo.pieceRefusee': '"{nom}" exceeds the remaining space ({reste}).',
  'compo.enregistrerBrouillon': 'Save draft',
  'compo.supprimerBrouillon': 'Delete draft',
  'compo.supprConfirme': 'Delete this draft? This cannot be undone.',
  // R3 (PLAN-RETOURS-6) : le marquage « important » de l'envoi —
  // bouton-icône de la barre de mise en forme, l'infobulle dit le geste.
  'compo.importantTitre': 'Mark the message as important',
  // R2 : l'envoi différé — la carte au-dessus du pied.
  'compo.plusTard': 'Send later',
  'compo.differeQuand': 'Leaves',
  'compo.differeNote': 'The message will be sent at that time if Wind is open, otherwise at the next launch.',
  'compo.programmer': 'Schedule',

  // --- Écran 01 et guichet de compte ------------------------------------
  'accueil.bienvenue': 'Welcome to',
  'accueil.etape': 'Step {n}/{total}',
  'accueil.ajouterSous': 'To begin, add an email address.',
  'accueil.ajouter': 'Add',
  'accueil.ajouterAutre': 'Add another email address',
  'accueil.retour': 'Back',
  'accueil.continuer': 'Continue',
  'accueil.terminer': 'Finish',
  'accueil.voletsTitre': 'Choose your window layout',
  'accueil.voletsSous': 'You can change it later in Settings > Display.',
  'accueil.themeTitre': 'Choose your theme',
  'accueil.themeSous': 'You can change it later in Settings > Themes.',
  'accueil.betaTitre': 'Wind is in beta',
  'accueil.betaSous':
    'You are using a beta version of Wind. Some features may still evolve, but everything should work without problems.',
  'accueil.betaBouton':
    'Tell us what is broken or missing in this form. When you click Send, it forwards your feedback by email to feedback-wind@fcts.io. We read every piece of feedback; it is invaluable to us!',
  'accueil.finTitre': 'All set.',
  'accueil.finTexte': 'Check your choices before finishing.',
  'accueil.revenir': 'Return to this step',
  'accueil.theme': 'Theme',
  'guichet.adresse': 'Email address',
  'guichet.mdp': 'Password',
  'guichet.imap': 'IMAP server',
  'guichet.smtp': 'SMTP server',
  'guichet.port': 'Port',
  'guichet.adresseInvalide': 'Enter your full email address.',
  'guichet.autorisation': 'Authorization in progress in your browser…',
  'guichet.verification': 'Checking the connection to the server…',
  'guichet.noteGenerique': "Enter your provider's servers. The password goes to the system vault, never a file.",
  'guichet.horizon': 'History to import for search',
  'horizon.1m': '1 month',
  'horizon.2m': '2 months',
  'horizon.3m': '3 months',
  'horizon.6m': '6 months',
  'horizon.1a': '1 year',
  'horizon.2a': '2 years',
  'horizon.5a': '5 years',
  'horizon.tout': 'Everything from the beginning',
  'boite.nettoyage': 'Spring cleaning',
  'nettoyage.sousTitre':
    'By starting a spring cleaning, you can sort your archives over the period of your choice by deciding, for each sender, how their messages should be handled.',
  'nettoyage.plage': 'Period to clean',
  'nettoyage.perimetre': 'Mailboxes to clean',
  'nettoyage.perimetre.reception': 'Inbox only',
  'nettoyage.perimetre.dossiers': 'Inbox + Folders',
  'nettoyage.perimetre.dossiersArchives': 'Inbox + Folders + Archive',
  'nettoyage.perimetre.archives': 'Inbox + Archive',
  'nettoyage.demarrer': 'Start cleaning',
  'nettoyage.progression': '{p}% done',
  'nettoyage.progressionAria': 'Cleaning progress',
  'nettoyage.message': '{n} message',
  'nettoyage.messages': '{n} messages',
  'nettoyage.fini': 'Every sender in the chosen period has been handled.',
  'nettoyage.terminer': 'Finish cleaning',
  'reglages.horizonCompte': 'Imported history for {email}',
  'reglages.horizonTitre': 'Imported history for search',
  'reglages.horizonNote':
    'Extending the duration fetches older messages at the next sync. Reducing it deletes nothing already on this computer.',
  'reglages.horizonImpossible': 'Could not save this choice ({err}).',

  // --- Modale de migration ----------------------------------------------
  'migration.aria': 'Message database update',
  'migration.titre': 'Updating your mailbox.',
  'migration.note': 'About {n} messages are being updated. This runs only once and deletes nothing.',
  'migration.preparation': 'Preparing…',
  'migration.pourcent': '{p}%',
  'migration.annulee': 'Update canceled, everything is back as before. It will resume at the next launch, or right away:',
  'migration.echec': 'The update failed ({err}). Nothing is lost: it can be run again.',

  // --- Réglages ---------------------------------------------------------
  'reglages.groupesAria': 'Settings groups',
  'groupe.comptes': 'Accounts',
  'groupe.themes': 'Themes',
  'groupe.affichage': 'Display',
  'groupe.notifications': 'Notifications',
  'groupe.signature': 'Signature',
  'groupe.raccourcis': 'Shortcuts',
  'groupe.apropos': 'About',
  'reglages.sectionThemes': 'Color theme',
  'reglages.sectionRaccourcis': 'Keyboard shortcuts',
  'reglages.ajouterCompte': 'Add an account',
  'reglages.retirerCompte': 'Remove account {email}',
  'reglages.retirerConfirme': 'Remove {email}? Its local mail is erased and its connection forgotten. Nothing is deleted on the server.',
  'reglages.retraitEnCours': 'Removing…',
  'reglages.retraitImpossible': 'Removal failed: {err}',
  'reglages.sombreAuto': 'Automatic dark',
  'reglages.sombreAutoDesc': 'Follow the system dark setting: the night variant of your chosen theme shows while it is on, the light one returns as soon as it turns off. A hand-picked night theme stays as it is.',
  'reglages.langue': 'Language',
  'reglages.langueDesc': 'The interface language, applied immediately.',
  'reglages.volets': 'Layout',
  'reglages.voletsDesc':
    'How many panes the main screen shows. Below three, reading opens full screen; with one pane, navigation lives in a drawer.',
  'volets.3': 'Three panes',
  'volets.2': 'Two panes',
  'volets.1': 'One pane',
  'reglages.espacement': 'Message spacing',
  'reglages.espacementDesc':
    'The air between two messages in the list. The more there is, the more the list breathes, and the fewer messages it shows at once.',
  'espacement.faible': 'Low',
  'espacement.moyen': 'Medium',
  'espacement.eleve': 'High',
  'reglages.imagesExpediteurs': 'Remote images',
  'reglages.imagesExpediteursDesc':
    'Images in messages from these senders always load, without asking.',
  'reglages.retirerExpediteur': 'Remove',
  'nav.ouvrirTiroir': 'Open navigation',
  'nav.fermerTiroir': 'Close navigation',
  'volets.poigneeNav': 'Resize the navigation pane',
  'volets.poigneeListe': 'Resize the list pane',
  'reglages.bulles': 'Arrival notifications',
  'reglages.bullesDesc': 'A system notification announces new messages at sync. Turning it off never stops the sync itself.',
  'reglages.noteRaccourcis': 'In a text field, letters are letters again; only Esc keeps a meaning.',
  'reglages.version': 'Version',
  'reglages.maj': 'Updates',
  'reglages.verifierMaj': 'Check for updates',
  'reglages.verification': 'Checking…',
  'reglages.ajour': 'You are up to date.',
  'reglages.majDisponible': 'Version {version} available.',
  'reglages.majImpossible': 'Check failed: {err}',
  'reglages.installation': 'Downloading and installing…',
  'reglages.signatureDesc':
    'One signature per account, added at the bottom of messages you compose. Composer formatting applies.',
  'reglages.signaturePlaceholder': 'Your signature…',
  'reglages.signatureRepliques': 'Also in replies and forwards',
  'reglages.signatureRepliquesDesc': 'Otherwise the signature is only added to new messages.',
  'reglages.signatureTous': 'Apply to all accounts',
  'reglages.icones': 'Icons',
  'reglages.iconesValeur': "Wind's original set, drawn after Material Symbols (Google, Apache 2.0); no network.",
  'reglages.origineValeur': 'Made in EU',

  // --- Raccourcis (table D3, référence) ---------------------------------
  'raccourci.touche.c': 'c',
  'raccourci.touche.r': 'r',
  'raccourci.touche.f': 'f',
  'raccourci.touche.e': 'e',
  'raccourci.touche.suppr': 'Del',
  'raccourci.touche.slash': '/',
  'raccourci.touche.echap': 'Esc',
  'raccourci.geste.c': 'Compose a new message',
  'raccourci.geste.r': 'Reply to the selected conversation',
  'raccourci.geste.f': 'Forward the selected conversation',
  'raccourci.geste.e': 'Archive the selected conversation',
  'raccourci.geste.suppr': 'Delete the selected conversation',
  'raccourci.geste.slash': 'Go to search',
  'raccourci.geste.echap': 'Close the overlay, leave the field, return to the inbox',

  // --- Thèmes (fiches du sélecteur : Réglages, accueil) -----------------
  // V7 amended by A94: the theme table is short and living (the
  // 28-entry Wada table stays retired) — the keys
  // follow FICHES (lib/theme.js), the coherence gate checks both ways.
  'theme.elements.nom': 'Elements',
  'theme.elements.desc': 'Light paper, the brand teal: the Elements direction.',
  'theme.elements-nuit.nom': 'Elements · night',
  'theme.elements-nuit.desc': 'Dark variant. Same 17 tokens.',
  'theme.innamoramento.nom': 'Innamoramento',
  'theme.innamoramento.desc': 'Deep rose, mauve tiles: the Innamoramento direction.',
  'theme.innamoramento-nuit.nom': 'Innamoramento · night',
  'theme.innamoramento-nuit.desc': 'Dark variant. Same 17 tokens.',

  // --- Langues (chaque langue se nomme dans SA langue) ------------------
  'langue.fr': 'Français',
  'langue.en': 'English',

  // --- Dates (quand.js) — transposition de la grammaire du prototype ----
  'quand.mois': [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
  ],
  'quand.jours': [
    'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday',
  ],
  'quand.hier': 'Yesterday',
  'quand.aujourdhui': 'Today',
  'quand.long': '{jour}, {heure}',
  'quand.premier': '1',
  'quand.dansAnnee': '{mois} {jour}',
  'quand.auDela': '{mois} {jour}, {annee}',
};
