// French catalogue (PLAN-LANGUES, A15): the French of the prototype,
// word for word — this file IS the reference, the extraction changed
// nothing on screen. Templates `{name}`; a bar `|` separates singular
// from plural (the per-language rule lives in text.svelte.js). The
// date tables (months, days) are arrays: when.js consumes them as is.

export const FR = {
  // --- Canonical folders (nav, status, conversation) -------------------
  'mailbox.inbox': 'Boîte de réception',
  // RETOURS-13 R3: in organized mode, the inbox is called « Réception ».
  'mailbox.organizedInbox': 'Réception',
  // PLAN-MODE-ORGANISE E1 — the organized-mode views (CE names).
  'mailbox.feed': 'Kiosque',
  'mailbox.paper_trail': 'Registre',
  'mailbox.screener': 'Portier',
  'mailbox.sent': 'Envoyés',
  'mailbox.drafts': 'Brouillons',
  'mailbox.junk': 'Indésirables',
  'mailbox.archive': 'Archives',
  'mailbox.trash': 'Corbeille',
  'nav.all': 'Toutes les boîtes',
  'nav.mailboxes': 'Boîtes',
  'nav.aria': 'Dossiers et comptes',

  // --- Screen 02 header --------------------------------------------------
  'header.search': 'Recherche',
  'header.searchHint': 'Chercher un message, une personne, un fichier',
  'header.clearSearch': 'Effacer la recherche',
  'header.compose': 'Écrire',
  'header.organized': 'Organisé',
  'action.moveTo': 'Déplacer vers…',
  'toast.senderMoved': 'Expéditeur déplacé vers {mailbox} : ses messages suivent.',
  'error.noAddress': "Ce message n'a pas d'adresse d'expéditeur.",

  // --- The Screener (PLAN-MODE-ORGANISE E2; subtitle in three
  // sentences, RETOURS-13 R4, CE texts — D1: hyphens settled).
  'screener.subtitle1': 'Ces expéditeurs vous écrivent pour la première fois.',
  'screener.subtitle2': 'Les autorisez-vous à vous contacter ?',
  'screener.subtitle3': 'Les expéditeurs ne seront jamais informés de votre décision.',
  'screener.question': 'Voulez-vous recevoir leurs messages ?',
  'screener.yes': 'Oui',
  'screener.no': 'Non',
  'screener.yesChoice': 'Oui, en choisissant la destination',
  'screener.noChoice': 'Non, en choisissant la règle',
  'screener.yesTo': 'Oui, et ses messages vont vers…',
  'screener.noWillBe': 'Non, et ses messages seront…',
  'screener.toInbox': 'La Réception',
  'screener.toFeed': 'Le Kiosque',
  'screener.toPaperTrail': 'Le Registre',
  'screener.theInbox': 'la Réception',
  'screener.theFeed': 'le Kiosque',
  'screener.thePaperTrail': 'le Registre',
  'screener.ruleSpam': 'Signalés indésirables',
  'screener.ruleArchive': 'Archivés automatiquement',
  // Field RETOURS-13 (C3): the CE word — nothing is « deleted »,
  // it is the server's trash (D4).
  'screener.ruleTrash': 'Déplacés automatiquement dans la corbeille',
  // RETOURS-13 R9: the fourth choice of the No — the 0.14.0 behavior.
  'screener.ruleScreenedOut': 'Écartés sans déplacer',
  'screener.empty':
    "Personne n'attend au Portier. Les nouveaux expéditeurs apparaîtront ici.",
  'screener.history': 'Historique du Portier',
  // RETOURS-13 R6: the CE text — the privacy note now lives
  // in the subtitle (R4).
  'screener.historyEmpty':
    "Vous n'avez écarté aucun expéditeur pour le moment.",
  'screener.reinstate': 'Réintégrer',
  // RETOURS-14 R4 (D5): the mixed-thread marker.
  'thread.screenerPending': 'En attente au Portier',
  'screener.screenedOut': 'écarté',
  'screener.screenedOutSpam': 'écarté (signalé indésirable)',
  'screener.screenedOutArchive': 'écarté (archivage automatique)',
  'screener.screenedOutTrash': 'écarté (suppression automatique)',
  'toast.screenerYesBare': '{who} peut vous écrire : ses messages arrivent en Réception.',
  'toast.screenerYesTo': '{who} peut vous écrire : ses messages vont vers {mailbox}.',
  'toast.screenerNoBare': "{who} est écarté ; il n'en saura rien.",
  'toast.screenerNoSpam':
    '{who} est écarté ; ses prochains messages partiront aux Indésirables.',
  'toast.screenerNoArchive':
    "{who} est écarté ; ses prochains messages s'archiveront automatiquement.",
  'toast.screenerNoTrash':
    '{who} est écarté ; ses prochains messages iront à la Corbeille.',
  // E4 — the organized Réception: sections and per-row gestures.
  // RETOURS-14 R6: a Registre group's rank counts THREADS.
  'paper_trail.thread': '{n} conversation',
  'paper_trail.threads': '{n} conversations',
  'paper_trail.seeMore': 'Voir plus',
  // RETOURS-14 R9: the section sort button (4-state cycle).
  'sort.dateDesc': "Plus récents d'abord",
  'sort.dateAsc': "Plus anciens d'abord",
  'sort.alphaAz': 'Expéditeur A → Z',
  'sort.alphaZa': 'Expéditeur Z → A',
  'sort.aria': 'Changer le tri de la section',
  'list.sectionNew': 'Nouveau pour vous · {n}',
  'list.sectionSeen': 'Déjà consulté',
  'list.gestures': 'Gestes sur ce message',
  'list.moveTo': 'Déplacer vers {mailbox}',
  'list.screenOut': 'Écarter cet expéditeur',
  // E5 — Set aside: the pile, the fan, the board (texts from the
  // prototype).
  'pile.setAside': 'Mis de côté',
  'pile.put': 'Mettre de côté',
  'pile.resume': 'Reprendre',
  'pile.seeBoard': 'Voir le tableau',
  'pile.open': 'Ouvrir',
  'pile.boardTitle': 'Le tableau des mis de côté',
  'pile.boardNote':
    "Tout ce que vous avez mis de côté, en aperçu sur un seul écran. « Terminé » renvoie le message d'où il vient.",
  'pile.boardEmpty': 'La pile est vide.',
  'pile.aria': 'Messages mis de côté',
  'toast.setAside': 'Mis de côté : la pile vit en bas à droite de la Réception.',
  'toast.resumedPile': 'Repris de la pile.',
  // E5bis — the Kiosque as cards; header and sections RETOURS-13
  // R10/R11 (CE texts, word for word).
  'feed.subtitle1': "Tous vos emails d'information sont regroupés ici.",
  'feed.subtitle2': 'Il vous suffit de les faire défiler pour les lire.',
  'feed.sectionUnread': 'Non lus',
  'feed.sectionRead': 'Lus précédemment',
  // Field C5 (CE text, agreement settled as in D1).
  'feed.allRead':
    'Vous avez lu toutes les nouvelles actualités de votre Kiosque.',
  'feed.empty':
    "Rien au Kiosque. Depuis un message, « Déplacer vers le Kiosque » y envoie les lettres d'information de cet expéditeur.",
  'toast.screenerReinstated':
    '{who} est réintégré ; ses messages des 90 derniers jours réapparaissent au Portier.',
  // RETOURS-13 R9: the Portier section of Réglages — the defaults of
  // the two desk buttons.
  'group.screener': 'Portier',
  'settings.screenerDesc':
    'Les actions par défaut des boutons du Portier. Le mini ⋯ de chaque bouton permet toujours un autre choix, au cas par cas.',
  'settings.screenerYes': 'Le bouton « Oui »',
  'settings.screenerYesDesc': "Où vont les messages d'un expéditeur autorisé.",
  'settings.screenerNo': 'Le bouton « Non »',
  'settings.screenerNoDesc':
    "Ce que deviennent les prochains messages d'un expéditeur écarté.",
  // RETOURS-14 R5 (D6): the exhaustive list of decisions.
  'settings.screenerDecisions': 'Décisions par expéditeur',
  'settings.screenerDecisionsDesc':
    'Toutes les décisions prises au Portier, par ordre alphabétique. Réintégrer un expéditeur le représentera au Portier à son prochain message.',
  'settings.screenerEdit': 'Modifier',
  'settings.resendScreener': 'Renvoyer au portier',
  'settings.screenerSearch': 'Rechercher un expéditeur',
  'settings.screenerNoDecision': 'Aucune décision pour le moment.',
  'settings.screenerNoResult': 'Aucun expéditeur ne correspond.',
  'header.settings': 'Réglages',
  // The beta feedback (RETOURS-11 R3): the CE's word, as is.
  'header.feedback': 'Feedback',
  'feedback.title': 'Feedback',
  // Text settled by the CE in the field on 2026-08-28, word for word.
  'feedback.subtitle':
    'Dites-nous ce qui cloche ou ce qui manque dans ce formulaire. Lorsque vous cliquez sur Envoyer, il nous transmet votre retour par email à feedback-wind@fcts.io. Nous lisons tous les retours, ils nous sont très précieux !',
  'feedback.placeholder': 'Votre retour…',
  'feedback.thanks': 'Merci pour votre retour !',

  // --- Status bar ---------------------------------------------------------
  'status.search': 'Recherche · {n} résultat|Recherche · {n} résultats',
  'status.searchCap': 'Recherche · {n} sur {total} résultat|Recherche · {n} sur {total} résultats',
  'status.category': '{mailbox} · {n} élément|{mailbox} · {n} éléments',
  'status.sync': 'Synchronisation · {p} %',
  'status.bodyBackfill': 'Rattrapage des messages · {n} restants · {p} %',
  'status.bodyBackfillAlone': 'Rattrapage des messages · {n} restants',
  'status.previewBackfill': 'Rattrapage des aperçus…',
  'status.sends': "Boîte d'envoi · {n} envoi en attente|Boîte d'envoi · {n} envois en attente",
  'status.scheduled':
    "Boîte d'envoi · {n} envoi programmé · départ {when}|Boîte d'envoi · {n} envois programmés · prochain départ {when}",
  'status.syncFailed': 'Synchronisation impossible · nouvelle tentative automatique',
  'status.syncFailedSince':
    'Synchronisation impossible · nouvelle tentative automatique · dernière synchronisation {since}',
  'status.upToDate': 'Tous les messages sont à jour',
  'status.upToDateSince': 'Tous les messages sont à jour · dernière synchronisation {since}',
  'status.offline': 'Hors ligne',
  'status.offlineSince': 'Hors ligne · dernière synchronisation {since}',
  'status.cyclePrefix': 'Synchronisation',
  'status.syncPartial':
    '{n} compte sur {m} injoignable · nouvelle tentative automatique|{n} comptes sur {m} injoignables · nouvelle tentative automatique',
  'status.percent': '{p} %',
  'status.phase.inventory': 'inventaire des dossiers',
  'status.phase.threads': 'fils de discussion',
  'status.phase.drafts': 'brouillons',
  'since.now': "à l'instant",
  'since.minutes': 'il y a {n} minute|il y a {n} minutes',
  'since.hours': 'il y a {n} heure|il y a {n} heures',
  'since.days': 'il y a {n} jour|il y a {n} jours',
  'status.startup': 'démarrage…',
  'status.perf': '{total} conversations · première page servie+rendue en {ms} ms',

  // --- Notice slot --------------------------------------------------------
  'notice.sendRefused': "L'envoi « {subject} » a été refusé{error}.",
  'notice.sendInterrupted': "L'envoi « {subject} » a été interrompu{error}.",
  'notice.update': 'Une mise à jour est disponible (version {version}).',
  'notice.crash': "Wind a rencontré un problème lors d'une session précédente ({n} rapport(s) en attente). Rien n'est envoyé sans vous.",
  'notice.telemetry': "Aider à améliorer Wind ? En cas de plantage, un rapport technique serait enregistré sur votre machine, jamais le contenu de vos mails. Vous choisissez ensuite de l'envoyer.",
  'notice.connection': 'Compte non reconnecté : {details}',
  'notice.scheduled': '« {subject} » partira {when}, si Wind est ouvert à ce moment-là.',
  'notice.refusedActions': "{n} action refusée par le serveur (dossier introuvable ou refus) : le message est resté où il était.|{n} actions refusées par le serveur (dossier introuvable ou refus) : les messages sont restés où ils étaient.",

  // --- Shared actions -------------------------------------------------
  'action.resend': 'Renvoyer',
  'action.discard': 'Abandonner',
  'action.install': 'Installer',
  'action.later': 'Plus tard',
  'action.openReports': 'Ouvrir le dossier des rapports',
  'action.dismiss': 'Ignorer',
  'action.enable': 'Activer',
  'action.noThanks': 'Non merci',
  'action.resume': 'Reprendre',
  'action.retry': 'Réessayer',
  'action.sync': 'Synchroniser',
  'action.syncing': 'Synchronisation…',
  'action.reply': 'Répondre',
  'action.replyAll': 'Répondre à tous',
  'action.forward': 'Transférer',
  'action.archive': 'Archiver',
  'action.delete': 'Supprimer',
  'action.reportSpam': 'Signaler comme spam',
  'action.notSpam': 'Ce n’est pas un spam',
  'action.pin': 'Épingler',
  'action.unpin': 'Désépingler',
  'action.send': 'Envoyer',
  'action.cancel': 'Annuler',
  'action.continue': 'Continuer',
  'action.close': 'Fermer',
  'action.collapse': 'Replier',
  'action.expand': 'Déplier',
  'action.remove': 'Retirer',
  'action.done': 'Terminé',
  'action.cancelSend': "Annuler l'envoi",
  'action.save': 'Enregistrer',
  'action.clear': 'Effacer',
  'action.accept': 'Accepter',
  'action.tentative': 'Provisoire',
  'action.decline': 'Refuser',
  // PLAN-RETOURS-10 R1: the multi-select bar.
  'action.markRead': 'Marquer lu',
  'action.markUnread': 'Marquer non lu',
  'action.cancelSelection': 'Annuler la sélection',

  // --- Invitation card (PLAN-INVITATIONS) ---------------------------------
  'inv.kicker': 'Invitation',
  'inv.kickerCancelled': 'Invitation annulée',
  'inv.kickerReply': 'Réponse à votre invitation',
  'inv.noReply': 'Vous n’avez pas répondu',
  'inv.you_accepted': 'Vous avez accepté',
  'inv.you_tentative': 'Vous avez répondu provisoirement',
  'inv.you_declined': 'Vous avez refusé',
  'inv.attendee_accepted': '{who} a accepté',
  'inv.attendee_tentative': '{who} a répondu provisoirement',
  'inv.attendee_declined': '{who} a refusé',
  'inv.attendee_no_reply': '{who} a répondu',
  'inv.cancelledText': 'La réunion a été annulée par l’organisateur.',
  'inv.organizerLocation': '{location} · organisé par {who}',
  'inv.organizedBy': 'Organisé par {who}',
  'inv.repeats': 'se répète',
  'inv.localTime': 'heure locale de l’organisateur',
  'inv.subject_accepted': 'Accepté : {title}',
  'inv.subject_tentative': 'Provisoire : {title}',
  'inv.subject_declined': 'Refusé : {title}',
  'inv.chip_accepted': 'Acceptée',
  'inv.chip_tentative': 'Provisoire',
  'inv.chip_declined': 'Refusée',
  'inv.chip_cancelled': 'Annulée',

  // --- Toasts ---------------------------------------------------------
  'toast.accountAdded': 'Compte ajouté.',
  'toast.accountRemoved': 'Compte retiré.',
  'toast.archived': 'Conversation archivée.',
  'toast.deleted': 'Conversation supprimée.',
  'toast.messageDeleted': 'Message supprimé.',
  'toast.spamReported': 'Message signalé comme indésirable.',
  'toast.notSpam': 'Message remis en réception.',
  // PLAN-RETOURS-10 R1: bulk gestures — ONE toast per batch.
  'toast.groupArchived': 'Conversation archivée.|{n} conversations archivées.',
  'toast.groupDeleted': 'Message supprimé.|{n} messages supprimés.',
  'toast.groupSpam': 'Conversation signalée indésirable.|{n} conversations signalées indésirables.',
  'toast.groupNotSpam': 'Conversation remise en réception.|{n} conversations remises en réception.',
  'toast.groupRead': 'Conversation marquée lue.|{n} conversations marquées lues.',
  'toast.groupUnread': 'Conversation marquée non lue.|{n} conversations marquées non lues.',
  'error.groupPartial': '{done} sur {total} ; le reste a échoué.',
  'toast.attachmentSaved': 'Pièce enregistrée : {path}',
  'toast.draftSaved': 'Brouillon enregistré.',
  'toast.draftDeleted': 'Brouillon supprimé.',
  'toast.draftFork': 'Ce brouillon avait changé ailleurs ; votre version a été conservée à part.',
  'toast.sent': 'Message envoyé.',
  'toast.scheduled': 'Envoi programmé : départ {when}.',
  'toast.sendCancelled': 'Envoi annulé : le message est revenu dans vos brouillons.',
  'toast.signature': 'Signature enregistrée.',
  'toast.signatureAll': 'Signature et choix appliqués à tous les comptes.',
  'toast.echoPending': 'Copie en cours de synchronisation : réessayez dans un instant.',

  // --- Error envelopes (the core's detail stays verbatim, L-3) -----------
  'error.spamFailed': 'Ce compte n’a pas de dossier indésirable.',
  'error.resend': 'Renvoi impossible : {err}',
  'error.discard': 'Abandon impossible : {err}',
  'error.update': 'Mise à jour impossible : {err}',
  'error.opening': 'Ouverture impossible : {err}',
  'error.preference': 'Préférence non enregistrée : {err}',
  'error.save': 'Enregistrement impossible : {err}',
  'error.forward': 'Transfert impossible : {err}',
  'error.replyAll': 'Répondre à tous impossible : {err}',
  'error.send': 'Envoi impossible : {err}',
  'error.invitation': 'La réponse n’est pas partie : {err}',
  'error.attachment': 'Pièce jointe impossible : {err}',
  'error.attachmentsMissing':
    "Des pièces du transfert manquent encore : attendez le rapatriement, réessayez, ou retirez-les avant d'envoyer.",
  'error.noAccount': 'Aucun compte émetteur : ajoutez un compte.',
  'error.connection': 'Connexion impossible : {err}',
  'error.deferredPass': 'Choisissez une date à venir.',
  'error.cancelSend': 'Annulation impossible : {err}',
  'error.cancelLater': "Trop tard : l'envoi est déjà parti.",
  'error.signature': 'Signature non enregistrée : {err}',

  // --- List -------------------------------------------------------------
  'list.aria': 'Liste des messages',
  'list.noResult': 'Aucun résultat.',
  'list.empty': 'Aucun message ici.',
  'list.loadMore': 'Afficher le résultat suivant|Afficher les {n} résultats suivants',
  'list.refine': 'Affinez votre recherche (from:, to:, date:) pour aller plus loin.',
  'list.draftPrefix': 'Brouillon : ',
  'list.dest': 'À : {a}',
  // A80: the preposition of the mailbox block — « Camille Roux sur Travail ».
  // Word order is fixed by the design (name, block, time): a language
  // that needed another order would require a template, not a key
  // (limit stated at PLAN-REPERE-LIGNE §4.6).
  'list.on': 'sur',
  // PLAN-RETOURS-10 R1: multi-select.
  'list.nSelection': '{n} sélectionné|{n} sélectionnés',
  'list.check': 'Sélectionner la conversation',
  'drafts.to': 'À : {a}',
  'drafts.withoutRecipient': '(sans destinataire)',
  'drafts.withoutSubject': '(sans objet)',
  'chip.messages': '{n} message|{n} messages',
  'chip.files': '{n} fichier|{n} fichiers',
  'chip.pin': 'Épinglé',
  'tab.all': 'Tous',
  'tab.unread': 'Non lus',

  // --- Reading pane -------------------------------------------------------
  'reading.aria': 'Message',
  'reading.empty': 'Sélectionnez un message pour le lire.',
  'reading.open': 'Ouvrir',
  'reading.bodyFailure': 'Le message n’a pas pu être chargé.',
  'reading.blockedImages': '{n} image distante bloquée pour protéger votre vie privée.|{n} images distantes bloquées pour protéger votre vie privée.',
  'reading.showImages': 'Afficher les images',
  'reading.alwaysShowImages': 'Toujours afficher les images de cet expéditeur',
  'reading.body': 'Contenu du message',
  'reading.save': 'Enregistrer…',
  'reading.veilSave': 'Enregistrer',

  // --- Conversation (screen 03) --------------------------------------------
  'conv.expand': 'Tout déplier',
  'conv.collapse': 'Tout replier',
  'conv.draft': 'Brouillon',
  'conv.toLine': 'À : {list}',
  'conv.ccLine': 'Cc : {list}',
  'conv.from': 'De',
  'conv.to': 'À',
  'conv.subject': 'Objet',
  'conv.attachedFiles': 'Fichiers joints',

  // --- Compose --------------------------------------------------------
  // Reconnecting an account with a dead token (field finding 2026-08-20).
  'settings.disconnected': 'Déconnecté',
  'settings.reconnect': 'Reconnecter',
  'settings.reconnectAccount': 'Reconnecter {email}',
  'settings.reconnectionInProgress': 'Consentement en cours…',
  'settings.reconnectionFailed': 'Reconnexion impossible : {err}',
  'settings.markerAccount': 'Repère de {email}',
  'settings.markerTitle': 'Icône et couleur du compte',
  'settings.markerIcons': 'Icône du repère',
  'settings.markerHues': 'Couleur du repère',
  'settings.markerRemove': 'Retirer le repère',
  'settings.markerFailed': 'Repère non enregistré : {err}',
  // PLAN-RETOURS-9: the removal is worded this way (D2), the custom name (D3).
  'settings.remove': 'Retirer le compte',
  'settings.renameAccount': 'Nommer {email}',
  'settings.nameTitle': 'Nom du compte',
  'settings.nameFailed': 'Nom non enregistré : {err}',
  'marker.icon.home': 'Maison',
  'marker.icon.work': 'Travail',
  'marker.icon.school': 'Études',
  'marker.icon.star': 'Étoile',
  'marker.icon.favorite': 'Cœur',
  'marker.icon.flight': 'Voyage',
  'marker.icon.shopping_bag': 'Achats',
  'marker.icon.account_balance': 'Banque',
  'marker.icon.sports_esports': 'Jeux',
  'marker.icon.eco': 'Nature',
  'marker.icon.pets': 'Animaux',
  'marker.icon.music_note': 'Musique',
  'marker.hue.red': 'Rouge',
  'marker.hue.orange': 'Orange',
  'marker.hue.ochre': 'Ocre',
  'marker.hue.olive': 'Olive',
  'marker.hue.green': 'Vert',
  'marker.hue.pine': 'Sapin',
  'marker.hue.blue': 'Bleu',
  'marker.hue.indigo': 'Indigo',
  'marker.hue.violet': 'Violet',
  'marker.hue.magenta': 'Magenta',
  'marker.hue.pink': 'Rose',
  'marker.hue.brown': 'Brun',

  'compose.new': 'Nouveau message',
  'compose.re': 'Re : {subject}',
  'compose.tr': 'Tr : {subject}',
  'compose.hello': 'Bonjour {firstName},',
  'compose.withoutSubject': 'sans objet',
  'compose.sendingAccount': 'Compte émetteur',
  'compose.recipient': 'Destinataire',
  'compose.suggestions': 'Adresses suggérées',
  'compose.subjectPlaceholder': 'Objet du message',
  'compose.bodyPlaceholder': 'Votre message…',
  'compose.cc': 'Cc',
  'compose.bcc': 'Cci',
  // The actual formatting bar (PLAN-COMPOSITION-HTML, R4). Link and
  // Quote REMOVED (CE decision D1: strict scope).
  'compose.font': 'Police',
  'compose.fontSans': 'Sans serif',
  'compose.fontSerif': 'Serif',
  'compose.fontMono': 'Monospace',
  'compose.size': 'Taille',
  'compose.sizeSmall': 'Petit',
  'compose.sizeNormal': 'Normal',
  'compose.sizeLarge': 'Grand',
  'compose.sizeVeryLarge': 'Très grand',
  'compose.bold': 'Gras',
  'compose.italic': 'Italique',
  'compose.underline': 'Souligné',
  'compose.strikethrough': 'Barré',
  'compose.color': 'Couleur du texte',
  'compose.alignLeft': 'Aligner à gauche',
  'compose.alignCenter': 'Centrer',
  'compose.alignRight': 'Aligner à droite',
  'compose.listBullets': 'Liste à puces',
  'compose.listNumbered': 'Liste numérotée',
  'compose.indentLess': 'Diminuer le retrait',
  'compose.indentMore': 'Augmenter le retrait',
  'compose.clearFormat': 'Effacer la mise en forme',
  'compose.attach': 'Joindre',
  'compose.removeAttachment': 'Retirer {name}',
  'compose.retrieving': '{name} · rapatriement…',
  'compose.totalWeight': '{poids} / 25 Mo',
  'compose.attachmentRefused': '« {name} » dépasse la place restante ({remaining}).',
  'compose.saveDraft': 'Enregistrer le brouillon',
  'compose.deleteDraft': 'Supprimer le brouillon',
  'compose.deleteConfirm': 'Supprimer ce brouillon ? C’est définitif.',
  // R3 (PLAN-RETOURS-6): marking the send as « important » —
  // icon button of the formatting bar, the tooltip names the gesture.
  'compose.importantTitle': 'Marquer le message comme important',
  // R2: the deferred send — the card above the footer.
  'compose.later': 'Envoyer plus tard',
  'compose.deferredWhen': 'Départ',
  'compose.deferredNote': 'Le message partira à cette heure si Wind est ouvert, sinon au prochain lancement.',
  'compose.schedule': 'Programmer',

  // --- Screen 01 and account desk ------------------------------------------
  'onboarding.welcome': 'Bienvenue dans',
  'onboarding.step': 'Étape {n}/{total}',
  'onboarding.addUnder': 'Pour commencer, ajoutez une adresse email.',
  'onboarding.add': 'Ajouter',
  'onboarding.addOther': 'Ajouter une autre adresse email',
  'onboarding.back': 'Retour',
  'onboarding.continue': 'Continuer',
  'onboarding.finish': 'Terminer',
  'onboarding.panesTitle': 'Choisissez votre disposition de fenêtre',
  'onboarding.panesUnder': 'Vous pourrez la changer plus tard dans Réglages > Affichage.',
  'onboarding.themeTitle': 'Choisissez votre thème',
  'onboarding.themeUnder': 'Vous pourrez le changer plus tard dans Réglages > Thèmes.',
  'onboarding.betaTitle': 'Wind est en bêta',
  // Texts settled by the CE in the field on 2026-08-28; the button
  // text is THE SAME as the feedback window's (retour.sous).
  'onboarding.betaUnder':
    'Vous utilisez une version Bêta de Wind. Certaines fonctionnalités peuvent évoluer, mais toutes doivent fonctionner sans problème.',
  'onboarding.betaButton':
    'Dites-nous ce qui cloche ou ce qui manque dans ce formulaire. Lorsque vous cliquez sur Envoyer, il nous transmet votre retour par email à feedback-wind@fcts.io. Nous lisons tous les retours, ils nous sont très précieux !',
  'onboarding.endTitle': 'Tout est prêt.',
  'onboarding.endText': 'Vérifiez vos choix avant de continuer.',
  'onboarding.goBack': 'Revenir à cette étape',
  'onboarding.theme': 'Thème',
  'desk.address': 'Adresse e-mail',
  'desk.password': 'Mot de passe',
  'desk.imap': 'Serveur IMAP',
  'desk.smtp': 'Serveur SMTP',
  'desk.port': 'Port',
  'desk.addressInvalid': 'Saisissez votre adresse e-mail complète.',
  'desk.authorization': 'Autorisation en cours dans votre navigateur…',
  'desk.checking': 'Vérification de la connexion au serveur…',
  'desk.noteGeneric': 'Renseignez les serveurs de votre fournisseur. Le mot de passe rejoint le coffre du système, jamais un fichier.',
  'desk.horizon': "Historique à importer pour la recherche",
  'horizon.1m': '1 mois',
  'horizon.2m': '2 mois',
  'horizon.3m': '3 mois',
  'horizon.6m': '6 mois',
  'horizon.1a': '1 an',
  'horizon.2a': '2 ans',
  'horizon.5a': '5 ans',
  'horizon.all': 'Tout depuis le début',
  'mailbox.cleanup': 'Nettoyage de printemps',
  'cleanup.subtitle':
    'En lançant un nettoyage de printemps, vous allez pouvoir trier vos archives sur la durée de votre choix en choisissant, pour chaque expéditeur, comment vous souhaitez que ses messages soient traités.',
  'cleanup.range': 'Période à nettoyer',
  'cleanup.scope': 'Boîtes à nettoyer',
  'cleanup.scope.inbox': 'Réception seule',
  'cleanup.scope.folders': 'Réception + Dossiers',
  'cleanup.scope.foldersArchive': 'Réception + Dossiers + Archives',
  'cleanup.scope.archive': 'Réception + Archives',
  'cleanup.start': 'Démarrer le nettoyage',
  'cleanup.progress': '{p} % traités',
  'cleanup.progressAria': 'Progression du nettoyage',
  'cleanup.message': '{n} message',
  'cleanup.messages': '{n} messages',
  'cleanup.done': 'Tous les expéditeurs de la période choisie ont été traités.',
  'cleanup.finish': 'Terminer le nettoyage',
  'settings.horizonAccount': 'Historique importé pour {email}',
  'settings.horizonTitle': 'Historique importé pour la recherche',
  'settings.horizonNote':
    "Étendre la durée rapatrie les messages plus anciens à la prochaine relève. Réduire n'efface rien de ce qui est déjà sur cet ordinateur.",
  'settings.horizonFailed': "Impossible d'enregistrer ce choix ({err}).",

  // --- Migration modal ------------------------------------------------
  'migration.aria': 'Mise à jour de la base de messages',
  'migration.title': 'Mise à jour de votre boîte.',
  'migration.note': 'Environ {n} messages sont mis à jour. Cette mise à jour ne se fait qu’une fois et n’efface rien.',
  'migration.preparing': 'Préparation…',
  'migration.percent': '{p} %',
  'migration.cancelled': 'Mise à jour annulée, tout est revenu comme avant. Elle reprendra au prochain lancement, ou tout de suite :',
  'migration.failure': 'La mise à jour a échoué ({err}). Rien n’est perdu : elle peut être relancée.',

  // --- Settings -----------------------------------------------------------
  'settings.groupsAria': 'Groupes de réglages',
  'group.accounts': 'Comptes',
  'group.themes': 'Thèmes',
  'group.display': 'Affichage',
  'group.notifications': 'Notifications',
  'group.signature': 'Signature',
  'group.shortcuts': 'Raccourcis',
  'group.about': 'À propos',
  'settings.sectionThemes': 'Thème de couleur',
  'settings.sectionShortcuts': 'Raccourcis clavier',
  'settings.addAccount': 'Ajouter un compte',
  // The button's visible text (« Retirer le compte ») lives INSIDE its
  // accessible name — WCAG 2.5.3, reviewed 2026-08-23.
  'settings.removeAccount': 'Retirer le compte {email}',
  'settings.removeConfirm': 'Retirer {email} ? Son courrier local est effacé et sa connexion oubliée. Rien n’est supprimé sur le serveur.',
  'settings.removalInProgress': 'Retrait…',
  'settings.removalFailed': 'Retrait impossible : {err}',
  'settings.darkAuto': 'Sombre automatique',
  'settings.darkAutoDesc': "Suivre le réglage sombre du système : la déclinaison nuit du thème choisi s'affiche quand il est actif, la claire revient dès qu'il s'éteint. Un thème nuit choisi à la main reste tel quel.",
  'settings.language': 'Langue',
  'settings.languageDesc': "La langue de l'interface, appliquée immédiatement.",
  'settings.panes': 'Disposition',
  'settings.panesDesc':
    "Le nombre de volets de l'écran principal. En dessous de trois, la lecture s'ouvre en plein écran ; en un volet, la navigation vit dans un tiroir.",
  'panes.3': 'Trois volets',
  'panes.2': 'Deux volets',
  'panes.1': 'Un volet',
  'settings.spacing': 'Espacement des messages',
  'settings.spacingDesc':
    "L'air entre deux messages dans la liste. Plus il est grand, plus la liste respire, et moins elle montre de messages à la fois.",
  'spacing.low': 'Faible',
  'spacing.medium': 'Moyen',
  'spacing.high': 'Élevé',
  'settings.imagesSenders': 'Images distantes',
  'settings.imagesSendersDesc':
    "Les images des messages de ces expéditeurs s'affichent toujours, sans demande.",
  'settings.removeSender': 'Retirer',
  'nav.openDrawer': 'Ouvrir la navigation',
  'nav.closeDrawer': 'Fermer la navigation',
  'panes.handleNav': 'Régler la largeur de la navigation',
  'panes.handleList': 'Régler la largeur de la liste',
  'settings.bubbles': "Bulles d'arrivée",
  'settings.bubblesDesc': "Une bulle système annonce les nouveaux messages à la synchronisation. La couper n'arrête jamais la synchronisation elle-même.",
  'settings.noteShortcuts': 'Dans un champ de saisie, les lettres redeviennent des lettres ; seul Échap garde un sens.',
  'settings.version': 'Version',
  'settings.update': 'Mises à jour',
  'settings.checkUpdate': 'Vérifier les mises à jour',
  'settings.checking': 'Vérification…',
  'settings.upToDate': 'Vous êtes à jour.',
  'settings.updateAvailable': 'Version {version} disponible.',
  'settings.updateFailed': 'Vérification impossible : {err}',
  'settings.installing': 'Téléchargement et installation…',
  'settings.signatureDesc':
    "Une signature par compte, ajoutée au bas des messages que vous composez. La mise en forme du composeur s'applique.",
  'settings.signaturePlaceholder': 'Votre signature…',
  'settings.signatureReplies': 'Aussi dans les réponses et transferts',
  'settings.signatureRepliesDesc':
    'Sinon, la signature ne s’ajoute qu’aux nouveaux messages.',
  'settings.signatureAll': 'Appliquer à tous les comptes',
  'settings.icons': 'Icônes',
  'settings.iconsValue': "Jeu original de Wind, dessiné d'après Material Symbols (Google, Apache 2.0) ; aucun réseau.",
  // D5 (PLAN-RETOURS-11): the label as is, identical in both
  // languages; no key (CE verdict from the visual STOP).
  'settings.originValue': 'Made in EU',

  // --- Shortcuts (table D3, reference) -------------------------------
  'shortcut.key.c': 'c',
  'shortcut.key.r': 'r',
  'shortcut.key.f': 'f',
  'shortcut.key.e': 'e',
  'shortcut.key.delete': 'Suppr',
  'shortcut.key.slash': '/',
  'shortcut.key.escape': 'Échap',
  'shortcut.gesture.c': 'Écrire un nouveau message',
  'shortcut.gesture.r': 'Répondre à la conversation sélectionnée',
  'shortcut.gesture.f': 'Transférer la conversation sélectionnée',
  'shortcut.gesture.e': 'Archiver la conversation sélectionnée',
  'shortcut.gesture.delete': 'Supprimer la conversation sélectionnée',
  'shortcut.gesture.slash': 'Aller à la recherche',
  'shortcut.gesture.escape': 'Fermer la surimpression, sortir du champ, revenir à la boîte',

  // --- Themes (picker entries: Settings, onboarding) ---------------------
  // V7 amended by A94: the theme table is short and living
  // (the 28-entry Wada table stays retired) —
  // the keys follow FICHES (lib/theme.js), the coherence gate
  // watches both directions.
  'theme.elements.name': 'Elements',
  'theme.elements.desc': 'Papier clair, teal de la marque : la direction Elements.',
  'theme.elements-nuit.name': 'Elements · nuit',
  'theme.elements-nuit.desc': 'Déclinaison sombre. Mêmes 17 jetons.',
  'theme.innamoramento.name': 'Innamoramento',
  'theme.innamoramento.desc': 'Rose profond, tuiles mauves : la direction Innamoramento.',
  'theme.innamoramento-nuit.name': 'Innamoramento · nuit',
  'theme.innamoramento-nuit.desc': 'Déclinaison sombre. Mêmes 17 jetons.',

  // --- Languages (each language is named in ITS OWN language, both
  //     catalogues carry the same values) ------------------------------
  'language.fr': 'Français',
  'language.en': 'English',

  // --- Dates (when.js) — exact forms from the prototype -------------------
  'when.month': [
    'janv.', 'févr.', 'mars', 'avr.', 'mai', 'juin',
    'juil.', 'août', 'sept.', 'oct.', 'nov.', 'déc.',
  ],
  'when.days': [
    'Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi',
  ],
  'when.yesterday': 'Hier',
  'when.today': "Aujourd'hui",
  'when.long': '{day}, {time}',
  'when.first': '1ᵉʳ',
  'when.inYear': '{day} {month}',
  'when.beyond': '{day} {month} {year}',
};
