// English catalogue (PLAN-LANGUES, A15): a transposition of the
// prototype's grammar, never an invention — same keys as catalog.fr.js,
// the e2e audit breaks at the slightest gap. The “ ” quotes become
// “ ”, the time stays on 24h (we ship a language, not a locale).

export const EN = {
  // --- Canonical folders (nav, status, conversation) -------------------
  'mailbox.inbox': 'Inbox',
  // RETOURS-13 R3 : the organized mode keeps the short name.
  'mailbox.organizedInbox': 'Inbox',
  // PLAN-MODE-ORGANISE E1 — the organized-mode views (HEY-inspired names).
  'mailbox.feed': 'Feed',
  'mailbox.paper_trail': 'Paper trail',
  'mailbox.screener': 'Screener',
  'mailbox.sent': 'Sent',
  'mailbox.drafts': 'Drafts',
  'mailbox.junk': 'Junk',
  'mailbox.archive': 'Archives',
  'mailbox.trash': 'Trash',
  'nav.all': 'All inboxes',
  'nav.mailboxes': 'Inboxes',
  'nav.aria': 'Folders and accounts',

  // --- Screen 02 header --------------------------------------------------
  'header.search': 'Search',
  'header.searchHint': 'Search messages, people, files',
  'header.clearSearch': 'Clear search',
  'header.compose': 'Compose',
  'header.organized': 'Organized',
  'action.moveTo': 'Move to…',
  'toast.senderMoved': 'Sender moved to {mailbox}: their messages follow.',
  'error.noAddress': 'This message has no sender address.',

  // --- The Screener (PLAN-MODE-ORGANISE E2) ---------------------------
  'screener.subtitle1': 'These senders are writing to you for the first time.',
  'screener.subtitle2': 'Do you allow them to contact you?',
  'screener.subtitle3': 'Senders will never be told of your decision.',
  'screener.question': 'Do you want to receive their messages?',
  'screener.yes': 'Yes',
  'screener.no': 'No',
  'screener.yesChoice': 'Yes, choosing the destination',
  'screener.noChoice': 'No, choosing the rule',
  'screener.yesTo': 'Yes, and their messages go to…',
  'screener.noWillBe': 'No, and their messages will be…',
  'screener.toInbox': 'The Inbox',
  'screener.toFeed': 'The Feed',
  'screener.toPaperTrail': 'The Paper trail',
  'screener.theInbox': 'the Inbox',
  'screener.theFeed': 'the Feed',
  'screener.thePaperTrail': 'the Paper trail',
  'screener.ruleSpam': 'Marked as junk',
  'screener.ruleArchive': 'Archived automatically',
  'screener.ruleTrash': 'Moved automatically to the Trash',
  'screener.ruleScreenedOut': 'Screened out without moving',
  'screener.empty': 'No one is waiting at the Screener. New senders will appear here.',
  'screener.history': 'Screener history',
  'screener.historyEmpty':
    'You have not screened out any senders yet.',
  'screener.reinstate': 'Reinstate',
  // RETOURS-14 R4 (D5): the mixed-thread marker.
  'thread.screenerPending': 'Awaiting the Screener',
  'screener.screenedOut': 'screened out',
  'screener.screenedOutSpam': 'screened out (marked as junk)',
  'screener.screenedOutArchive': 'screened out (archived automatically)',
  'screener.screenedOutTrash': 'screened out (deleted automatically)',
  'toast.screenerYesBare': '{who} can write to you: their messages arrive in the Inbox.',
  'toast.screenerYesTo': '{who} can write to you: their messages go to {mailbox}.',
  'toast.screenerNoBare': '{who} is screened out; they will never know.',
  'toast.screenerNoSpam': '{who} is screened out; their next messages will go to Junk.',
  'toast.screenerNoArchive':
    '{who} is screened out; their next messages will be archived automatically.',
  'toast.screenerNoTrash':
    '{who} is screened out; their next messages will go to the Trash.',
  // E4 — the organized Inbox: sections and per-row gestures.
  // RETOURS-14 R6: a Paper trail group row counts THREADS.
  'paper_trail.thread': '{n} conversation',
  'paper_trail.threads': '{n} conversations',
  'paper_trail.seeMore': 'Show more',
  // RETOURS-14 R9: the section sort button (4-state cycle).
  'sort.dateDesc': 'Newest first',
  'sort.dateAsc': 'Oldest first',
  'sort.alphaAz': 'Sender A → Z',
  'sort.alphaZa': 'Sender Z → A',
  'sort.aria': 'Change the section sort',
  'list.sectionNew': 'New for you · {n}',
  'list.sectionSeen': 'Previously seen',
  'list.gestures': 'Actions on this message',
  'list.moveTo': 'Move to {mailbox}',
  'list.screenOut': 'Screen out this sender',
  // E5 — Set Aside: the pile, the fan, the board.
  'pile.setAside': 'Set aside',
  'pile.put': 'Set aside',
  'pile.resume': 'Bring back',
  'pile.seeBoard': 'See the board',
  'pile.open': 'Open',
  'pile.boardTitle': 'The Set Aside board',
  'pile.boardNote':
    'Everything you set aside, at a glance on one screen. \u201cDone\u201d sends the message back where it came from.',
  'pile.boardEmpty': 'The pile is empty.',
  'pile.aria': 'Set-aside messages',
  'toast.setAside': 'Set aside: the pile lives at the bottom right of the Inbox.',
  'toast.resumedPile': 'Brought back from the pile.',
  // E5bis — the Feed as cards; header and sections RETOURS-13 R10/R11.
  'feed.subtitle1': 'All your informational emails are gathered here.',
  'feed.subtitle2': 'Just scroll through them to read.',
  'feed.sectionUnread': 'Unread',
  'feed.sectionRead': 'Previously read',
  'feed.allRead': 'You have read all the new stories in your Feed.',
  'feed.empty':
    'Nothing in the Feed. From a message, “Move to the Feed” sends that sender’s newsletters here.',
  'toast.screenerReinstated':
    '{who} is reinstated; their messages from the last 90 days reappear at the Screener.',
  'group.screener': 'Screener',
  'settings.screenerDesc':
    'The default actions of the Screener buttons. The mini ⋯ on each button still offers a one-off choice.',
  'settings.screenerYes': 'The “Yes” button',
  'settings.screenerYesDesc': 'Where an allowed sender’s messages go.',
  'settings.screenerNo': 'The “No” button',
  'settings.screenerNoDesc':
    'What happens to a screened-out sender’s next messages.',
  // RETOURS-14 R5 (D6): the exhaustive list of decisions.
  'settings.screenerDecisions': 'Decisions by sender',
  'settings.screenerDecisionsDesc':
    'Every decision made at the Screener, in alphabetical order. Reinstating a sender will present them at the Screener again on their next message.',
  'settings.screenerEdit': 'Edit',
  'settings.resendScreener': 'Send back to the Screener',
  'settings.screenerSearch': 'Search for a sender',
  'settings.screenerNoDecision': 'No decisions yet.',
  'settings.screenerNoResult': 'No sender matches.',
  'header.settings': 'Settings',
  'header.feedback': 'Feedback',
  'feedback.title': 'Feedback',
  'feedback.subtitle':
    'Tell us what is broken or missing in this form. When you click Send, it forwards your feedback by email to feedback-wind@fcts.io. We read every piece of feedback; it is invaluable to us!',
  'feedback.placeholder': 'Your feedback…',
  'feedback.thanks': 'Thank you for your feedback!',

  // --- Status bar ---------------------------------------------------------
  'status.search': 'Search · {n} result|Search · {n} results',
  'status.searchCap': 'Search · {n} of {total} result|Search · {n} of {total} results',
  'status.category': '{mailbox} · {n} item|{mailbox} · {n} items',
  'status.sync': 'Syncing · {p}%',
  'status.bodyBackfill': 'Catching up on messages · {n} to go · {p} %',
  'status.bodyBackfillAlone': 'Catching up on messages · {n} to go',
  'status.previewBackfill': 'Catching up on previews…',
  'status.sends': 'Outbox · {n} message waiting|Outbox · {n} messages waiting',
  'status.scheduled':
    'Outbox · {n} message scheduled · leaves {when}|Outbox · {n} messages scheduled · next leaves {when}',
  'status.syncFailed': 'Sync failed · will retry automatically',
  'status.syncFailedSince':
    'Sync failed · will retry automatically · last synced {since}',
  'status.upToDate': 'All messages are up to date',
  'status.upToDateSince': 'All messages are up to date · last synced {since}',
  'status.offline': 'Offline',
  'status.offlineSince': 'Offline · last synced {since}',
  'status.cyclePrefix': 'Syncing',
  'status.syncPartial':
    '{n} account of {m} unreachable · will retry automatically|{n} accounts of {m} unreachable · will retry automatically',
  'status.percent': '{p}%',
  'status.phase.inventory': 'folder inventory',
  'status.phase.threads': 'conversation threads',
  'status.phase.drafts': 'drafts',
  'since.now': 'just now',
  'since.minutes': '{n} minute ago|{n} minutes ago',
  'since.hours': '{n} hour ago|{n} hours ago',
  'since.days': '{n} day ago|{n} days ago',
  'status.startup': 'starting…',
  'status.perf': '{total} conversations · first page served+rendered in {ms} ms',

  // --- Notice slot --------------------------------------------------------
  'notice.sendRefused': 'The message “{subject}” was rejected{error}.',
  'notice.sendInterrupted': 'The message “{subject}” was interrupted{error}.',
  'notice.update': 'An update is available (version {version}).',
  'notice.crash': 'Wind ran into a problem during a previous session ({n} report(s) pending). Nothing is sent without you.',
  'notice.telemetry': 'Help improve Wind? If it crashes, a technical report would be saved on your machine, never the content of your mail. You then choose whether to send it.',
  'notice.connection': 'Account not reconnected: {details}',
  'notice.scheduled': '“{subject}” will be sent {when}, if Wind is open at that time.',
  'notice.refusedActions': '{n} action refused by the server (folder not found or rejected): the message stayed where it was.|{n} actions refused by the server (folder not found or rejected): the messages stayed where they were.',

  // --- Shared actions -------------------------------------------------
  'action.resend': 'Send again',
  'action.discard': 'Discard',
  'action.install': 'Install',
  'action.later': 'Later',
  'action.openReports': 'Open the reports folder',
  'action.dismiss': 'Dismiss',
  'action.enable': 'Turn on',
  'action.noThanks': 'No thanks',
  'action.resume': 'Resume',
  'action.retry': 'Try again',
  'action.sync': 'Sync',
  'action.syncing': 'Syncing…',
  'action.reply': 'Reply',
  'action.replyAll': 'Reply all',
  'action.forward': 'Forward',
  'action.archive': 'Archive',
  'action.reportSpam': 'Report as spam',
  'action.notSpam': 'Not spam',
  'action.pin': 'Pin',
  'action.unpin': 'Unpin',
  'action.delete': 'Delete',
  'action.send': 'Send',
  'action.cancel': 'Cancel',
  'action.continue': 'Continue',
  'action.close': 'Close',
  'action.collapse': 'Collapse',
  'action.expand': 'Expand',
  'action.remove': 'Remove',
  'action.done': 'Done',
  'action.cancelSend': 'Cancel send',
  'action.save': 'Save',
  'action.clear': 'Clear',
  'action.accept': 'Accept',
  'action.tentative': 'Tentative',
  'action.decline': 'Decline',
  // PLAN-RETOURS-10 R1: the multi-select bar.
  'action.markRead': 'Mark as read',
  'action.markUnread': 'Mark as unread',
  'action.cancelSelection': 'Cancel selection',

  // --- Invitation card (PLAN-INVITATIONS) -------------------------------
  'inv.kicker': 'Invitation',
  'inv.kickerCancelled': 'Invitation cancelled',
  'inv.kickerReply': 'Reply to your invitation',
  'inv.noReply': 'You have not replied',
  'inv.you_accepted': 'You accepted',
  'inv.you_tentative': 'You tentatively accepted',
  'inv.you_declined': 'You declined',
  'inv.attendee_accepted': '{who} accepted',
  'inv.attendee_tentative': '{who} tentatively accepted',
  'inv.attendee_declined': '{who} declined',
  'inv.attendee_no_reply': '{who} replied',
  'inv.cancelledText': 'The meeting was cancelled by the organiser.',
  'inv.organizerLocation': '{location} · organised by {who}',
  'inv.organizedBy': 'Organised by {who}',
  'inv.repeats': 'repeats',
  'inv.localTime': 'organiser’s local time',
  'inv.subject_accepted': 'Accepted: {title}',
  'inv.subject_tentative': 'Tentative: {title}',
  'inv.subject_declined': 'Declined: {title}',
  'inv.chip_accepted': 'Accepted',
  'inv.chip_tentative': 'Tentative',
  'inv.chip_declined': 'Declined',
  'inv.chip_cancelled': 'Cancelled',

  // --- Toasts ---------------------------------------------------------
  'toast.accountAdded': 'Account added.',
  'toast.accountRemoved': 'Account removed.',
  'toast.archived': 'Conversation archived.',
  'toast.deleted': 'Conversation deleted.',
  'toast.messageDeleted': 'Message deleted.',
  'toast.spamReported': 'Reported as spam.',
  'toast.notSpam': 'Moved back to Inbox.',
  // PLAN-RETOURS-10 R1: bulk gestures — ONE toast per batch.
  'toast.groupArchived': 'Conversation archived.|{n} conversations archived.',
  'toast.groupDeleted': 'Message deleted.|{n} messages deleted.',
  'toast.groupSpam': 'Conversation reported as spam.|{n} conversations reported as spam.',
  'toast.groupNotSpam': 'Conversation moved back to Inbox.|{n} conversations moved back to Inbox.',
  'toast.groupRead': 'Conversation marked as read.|{n} conversations marked as read.',
  'toast.groupUnread': 'Conversation marked as unread.|{n} conversations marked as unread.',
  'error.groupPartial': '{done} of {total}; the rest failed.',
  'toast.attachmentSaved': 'Attachment saved: {path}',
  'toast.draftSaved': 'Draft saved.',
  'toast.draftDeleted': 'Draft deleted.',
  'toast.draftFork': 'This draft had changed elsewhere; your version was kept separately.',
  'toast.sent': 'Message sent.',
  'toast.scheduled': 'Send scheduled: leaves {when}.',
  'toast.sendCancelled': 'Send cancelled: the message is back in your drafts.',
  'toast.signature': 'Signature saved.',
  'toast.signatureAll': 'Signature and choice applied to all accounts.',
  'toast.echoPending': 'Copy still syncing: try again in a moment.',

  // --- Error envelopes (the core's detail stays verbatim, L-3) -----------
  'error.spamFailed': 'This account has no spam folder.',
  'error.resend': 'Could not resend: {err}',
  'error.discard': 'Could not discard: {err}',
  'error.update': 'Update failed: {err}',
  'error.opening': 'Could not open: {err}',
  'error.preference': 'Preference not saved: {err}',
  'error.save': 'Could not save: {err}',
  'error.forward': 'Could not forward: {err}',
  'error.replyAll': 'Could not reply all: {err}',
  'error.send': 'Could not send: {err}',
  'error.invitation': 'The reply was not sent: {err}',
  'error.attachment': 'Could not attach: {err}',
  'error.attachmentsMissing':
    'Some forwarded files are still missing: wait for retrieval, try again, or remove them before sending.',
  'error.noAccount': 'No sending account: add an account.',
  'error.connection': 'Could not connect: {err}',
  'error.deferredPass': 'Pick a time in the future.',
  'error.cancelSend': 'Could not cancel: {err}',
  'error.cancelLater': 'Too late: the message already left.',
  'error.signature': 'Signature not saved: {err}',

  // --- List -------------------------------------------------------------
  'list.aria': 'Message list',
  'list.noResult': 'No results.',
  'list.empty': 'No messages here.',
  'list.loadMore': 'Show the next result|Show the next {n} results',
  'list.refine': 'Refine your search (from:, to:, date:) to go further.',
  'list.draftPrefix': 'Draft: ',
  'list.dest': 'To: {a}',
  // A80, decision D10: “Camille Roux in Work” — the mailbox is a
  // container, not a medium.
  'list.on': 'in',
  // PLAN-RETOURS-10 R1: multi-select.
  'list.nSelection': '{n} selected|{n} selected',
  'list.check': 'Select the conversation',
  'drafts.to': 'To: {a}',
  'drafts.withoutRecipient': '(no recipient)',
  'drafts.withoutSubject': '(no subject)',
  'chip.messages': '{n} message|{n} messages',
  'chip.files': '{n} file|{n} files',
  'chip.pin': 'Pinned',
  'tab.all': 'All',
  'tab.unread': 'Unread',

  // --- Reading pane -------------------------------------------------------
  'reading.aria': 'Message',
  'reading.empty': 'Select a message to read it.',
  'reading.open': 'Open',
  'reading.bodyFailure': 'This message could not be loaded.',
  'reading.blockedImages': '{n} remote image blocked to protect your privacy.|{n} remote images blocked to protect your privacy.',
  'reading.showImages': 'Show images',
  'reading.alwaysShowImages': 'Always show images from this sender',
  'reading.body': 'Message content',
  'reading.save': 'Save…',
  'reading.veilSave': 'Save',

  // --- Conversation (screen 03) --------------------------------------------
  'conv.expand': 'Expand all',
  'conv.collapse': 'Collapse all',
  'conv.draft': 'Draft',
  'conv.toLine': 'To: {list}',
  'conv.ccLine': 'Cc: {list}',
  'conv.from': 'From',
  'conv.to': 'To',
  'conv.subject': 'Subject',
  'conv.attachedFiles': 'Attachments',

  // --- Compose --------------------------------------------------------
  // Reconnecting an account with a dead token (field finding 2026-08-20).
  'settings.disconnected': 'Disconnected',
  'settings.reconnect': 'Reconnect',
  'settings.reconnectAccount': 'Reconnect {email}',
  'settings.reconnectionInProgress': 'Waiting for consent…',
  'settings.reconnectionFailed': 'Reconnection failed: {err}',
  'settings.markerAccount': 'Marker for {email}',
  'settings.markerTitle': 'Account icon and color',
  'settings.markerIcons': 'Marker icon',
  'settings.markerHues': 'Marker color',
  'settings.markerRemove': 'Remove marker',
  'settings.markerFailed': 'Marker not saved: {err}',
  // PLAN-RETOURS-9: the removal is worded this way (D2), the custom name (D3).
  'settings.remove': 'Remove account',
  'settings.renameAccount': 'Name {email}',
  'settings.nameTitle': 'Account name',
  'settings.nameFailed': 'Name not saved: {err}',
  'marker.icon.home': 'Home',
  'marker.icon.work': 'Work',
  'marker.icon.school': 'School',
  'marker.icon.star': 'Star',
  'marker.icon.favorite': 'Heart',
  'marker.icon.flight': 'Travel',
  'marker.icon.shopping_bag': 'Shopping',
  'marker.icon.account_balance': 'Bank',
  'marker.icon.sports_esports': 'Games',
  'marker.icon.eco': 'Nature',
  'marker.icon.pets': 'Pets',
  'marker.icon.music_note': 'Music',
  'marker.hue.red': 'Red',
  'marker.hue.orange': 'Orange',
  'marker.hue.ochre': 'Ochre',
  'marker.hue.olive': 'Olive',
  'marker.hue.green': 'Green',
  'marker.hue.pine': 'Pine',
  'marker.hue.blue': 'Blue',
  'marker.hue.indigo': 'Indigo',
  'marker.hue.violet': 'Purple',
  'marker.hue.magenta': 'Magenta',
  'marker.hue.pink': 'Pink',
  'marker.hue.brown': 'Brown',

  'compose.new': 'New message',
  'compose.re': 'Re: {subject}',
  'compose.tr': 'Fwd: {subject}',
  'compose.hello': 'Hello {firstName},',
  'compose.withoutSubject': 'no subject',
  'compose.sendingAccount': 'Sending account',
  'compose.recipient': 'Recipient',
  'compose.suggestions': 'Suggested addresses',
  'compose.subjectPlaceholder': 'Message subject',
  'compose.bodyPlaceholder': 'Your message…',
  'compose.cc': 'Cc',
  'compose.bcc': 'Bcc',
  // The actual formatting bar (PLAN-COMPOSITION-HTML, R4). Link and
  // Quote REMOVED (CE decision D1: strict scope).
  'compose.font': 'Font',
  'compose.fontSans': 'Sans serif',
  'compose.fontSerif': 'Serif',
  'compose.fontMono': 'Monospace',
  'compose.size': 'Size',
  'compose.sizeSmall': 'Small',
  'compose.sizeNormal': 'Normal',
  'compose.sizeLarge': 'Large',
  'compose.sizeVeryLarge': 'Extra large',
  'compose.bold': 'Bold',
  'compose.italic': 'Italic',
  'compose.underline': 'Underline',
  'compose.strikethrough': 'Strikethrough',
  'compose.color': 'Text color',
  'compose.alignLeft': 'Align left',
  'compose.alignCenter': 'Center',
  'compose.alignRight': 'Align right',
  'compose.listBullets': 'Bulleted list',
  'compose.listNumbered': 'Numbered list',
  'compose.indentLess': 'Decrease indent',
  'compose.indentMore': 'Increase indent',
  'compose.clearFormat': 'Clear formatting',
  'compose.attach': 'Attach',
  'compose.removeAttachment': 'Remove {name}',
  'compose.retrieving': '{name} · retrieving…',
  'compose.totalWeight': '{poids} / 25 MB',
  'compose.attachmentRefused': '"{name}" exceeds the remaining space ({remaining}).',
  'compose.saveDraft': 'Save draft',
  'compose.deleteDraft': 'Delete draft',
  'compose.deleteConfirm': 'Delete this draft? This cannot be undone.',
  // R3 (PLAN-RETOURS-6): marking the send as “important” —
  // icon button of the formatting bar, the tooltip names the gesture.
  'compose.importantTitle': 'Mark the message as important',
  // R2: the deferred send — the card above the footer.
  'compose.later': 'Send later',
  'compose.deferredWhen': 'Leaves',
  'compose.deferredNote': 'The message will be sent at that time if Wind is open, otherwise at the next launch.',
  'compose.schedule': 'Schedule',

  // --- Screen 01 and account desk ------------------------------------------
  'onboarding.welcome': 'Welcome to',
  'onboarding.step': 'Step {n}/{total}',
  'onboarding.addUnder': 'To begin, add an email address.',
  'onboarding.add': 'Add',
  'onboarding.addOther': 'Add another email address',
  'onboarding.back': 'Back',
  'onboarding.continue': 'Continue',
  'onboarding.finish': 'Finish',
  'onboarding.panesTitle': 'Choose your window layout',
  'onboarding.panesUnder': 'You can change it later in Settings > Display.',
  'onboarding.themeTitle': 'Choose your theme',
  'onboarding.themeUnder': 'You can change it later in Settings > Themes.',
  'onboarding.betaTitle': 'Wind is in beta',
  'onboarding.betaUnder':
    'You are using a beta version of Wind. Some features may still evolve, but everything should work without problems.',
  'onboarding.betaButton':
    'Tell us what is broken or missing in this form. When you click Send, it forwards your feedback by email to feedback-wind@fcts.io. We read every piece of feedback; it is invaluable to us!',
  'onboarding.endTitle': 'All set.',
  'onboarding.endText': 'Check your choices before finishing.',
  'onboarding.goBack': 'Return to this step',
  'onboarding.theme': 'Theme',
  'desk.address': 'Email address',
  'desk.password': 'Password',
  'desk.imap': 'IMAP server',
  'desk.smtp': 'SMTP server',
  'desk.port': 'Port',
  'desk.addressInvalid': 'Enter your full email address.',
  'desk.authorization': 'Authorization in progress in your browser…',
  'desk.checking': 'Checking the connection to the server…',
  'desk.noteGeneric': "Enter your provider's servers. The password goes to the system vault, never a file.",
  'desk.horizon': 'History to import for search',
  'horizon.1m': '1 month',
  'horizon.2m': '2 months',
  'horizon.3m': '3 months',
  'horizon.6m': '6 months',
  'horizon.1a': '1 year',
  'horizon.2a': '2 years',
  'horizon.5a': '5 years',
  'horizon.all': 'Everything from the beginning',
  'mailbox.cleanup': 'Spring cleaning',
  'cleanup.subtitle':
    'By starting a spring cleaning, you can sort your archives over the period of your choice by deciding, for each sender, how their messages should be handled.',
  'cleanup.range': 'Period to clean',
  'cleanup.scope': 'Mailboxes to clean',
  'cleanup.scope.inbox': 'Inbox only',
  'cleanup.scope.folders': 'Inbox + Folders',
  'cleanup.scope.foldersArchive': 'Inbox + Folders + Archive',
  'cleanup.scope.archive': 'Inbox + Archive',
  'cleanup.start': 'Start cleaning',
  'cleanup.progress': '{p}% done',
  'cleanup.progressAria': 'Cleaning progress',
  'cleanup.message': '{n} message',
  'cleanup.messages': '{n} messages',
  'cleanup.done': 'Every sender in the chosen period has been handled.',
  'cleanup.finish': 'Finish cleaning',
  'settings.horizonAccount': 'Imported history for {email}',
  'settings.horizonTitle': 'Imported history for search',
  'settings.horizonNote':
    'Extending the duration fetches older messages at the next sync. Reducing it deletes nothing already on this computer.',
  'settings.horizonFailed': 'Could not save this choice ({err}).',

  // --- Migration modal ------------------------------------------------
  'migration.aria': 'Message database update',
  'migration.title': 'Updating your mailbox.',
  'migration.note': 'About {n} messages are being updated. This runs only once and deletes nothing.',
  'migration.preparing': 'Preparing…',
  'migration.percent': '{p}%',
  'migration.cancelled': 'Update canceled, everything is back as before. It will resume at the next launch, or right away:',
  'migration.failure': 'The update failed ({err}). Nothing is lost: it can be run again.',

  // --- Settings -----------------------------------------------------------
  'settings.groupsAria': 'Settings groups',
  'group.accounts': 'Accounts',
  'group.themes': 'Themes',
  'group.display': 'Display',
  'group.notifications': 'Notifications',
  'group.signature': 'Signature',
  'group.shortcuts': 'Shortcuts',
  'group.about': 'About',
  'settings.sectionThemes': 'Color theme',
  'settings.sectionShortcuts': 'Keyboard shortcuts',
  'settings.addAccount': 'Add an account',
  'settings.removeAccount': 'Remove account {email}',
  'settings.removeConfirm': 'Remove {email}? Its local mail is erased and its connection forgotten. Nothing is deleted on the server.',
  'settings.removalInProgress': 'Removing…',
  'settings.removalFailed': 'Removal failed: {err}',
  'settings.darkAuto': 'Automatic dark',
  'settings.darkAutoDesc': 'Follow the system dark setting: the night variant of your chosen theme shows while it is on, the light one returns as soon as it turns off. A hand-picked night theme stays as it is.',
  'settings.language': 'Language',
  'settings.languageDesc': 'The interface language, applied immediately.',
  'settings.panes': 'Layout',
  'settings.panesDesc':
    'How many panes the main screen shows. Below three, reading opens full screen; with one pane, navigation lives in a drawer.',
  'panes.3': 'Three panes',
  'panes.2': 'Two panes',
  'panes.1': 'One pane',
  'settings.spacing': 'Message spacing',
  'settings.spacingDesc':
    'The air between two messages in the list. The more there is, the more the list breathes, and the fewer messages it shows at once.',
  'spacing.low': 'Low',
  'spacing.medium': 'Medium',
  'spacing.high': 'High',
  'settings.imagesSenders': 'Remote images',
  'settings.imagesSendersDesc':
    'Images in messages from these senders always load, without asking.',
  'settings.removeSender': 'Remove',
  'nav.openDrawer': 'Open navigation',
  'nav.closeDrawer': 'Close navigation',
  'panes.handleNav': 'Resize the navigation pane',
  'panes.handleList': 'Resize the list pane',
  'settings.bubbles': 'Arrival notifications',
  'settings.bubblesDesc': 'A system notification announces new messages at sync. Turning it off never stops the sync itself.',
  'settings.noteShortcuts': 'In a text field, letters are letters again; only Esc keeps a meaning.',
  'settings.version': 'Version',
  'settings.update': 'Updates',
  'settings.checkUpdate': 'Check for updates',
  'settings.checking': 'Checking…',
  'settings.upToDate': 'You are up to date.',
  'settings.updateAvailable': 'Version {version} available.',
  'settings.updateFailed': 'Check failed: {err}',
  'settings.installing': 'Downloading and installing…',
  'settings.signatureDesc':
    'One signature per account, added at the bottom of messages you compose. Composer formatting applies.',
  'settings.signaturePlaceholder': 'Your signature…',
  'settings.signatureReplies': 'Also in replies and forwards',
  'settings.signatureRepliesDesc': 'Otherwise the signature is only added to new messages.',
  'settings.signatureAll': 'Apply to all accounts',
  'settings.icons': 'Icons',
  'settings.iconsValue': "Wind's original set, drawn after Material Symbols (Google, Apache 2.0); no network.",
  'settings.originValue': 'Made in EU',

  // --- Shortcuts (table D3, reference) -------------------------------
  'shortcut.key.c': 'c',
  'shortcut.key.r': 'r',
  'shortcut.key.f': 'f',
  'shortcut.key.e': 'e',
  'shortcut.key.delete': 'Del',
  'shortcut.key.slash': '/',
  'shortcut.key.escape': 'Esc',
  'shortcut.gesture.c': 'Compose a new message',
  'shortcut.gesture.r': 'Reply to the selected conversation',
  'shortcut.gesture.f': 'Forward the selected conversation',
  'shortcut.gesture.e': 'Archive the selected conversation',
  'shortcut.gesture.delete': 'Delete the selected conversation',
  'shortcut.gesture.slash': 'Go to search',
  'shortcut.gesture.escape': 'Close the overlay, leave the field, return to the inbox',

  // --- Themes (picker entries: Settings, onboarding) ---------------------
  // V7 amended by A94: the theme table is short and living (the
  // 28-entry Wada table stays retired) — the keys
  // follow FICHES (lib/theme.js), the coherence gate checks both ways.
  'theme.elements.name': 'Elements',
  'theme.elements.desc': 'Light paper, the brand teal: the Elements direction.',
  'theme.elements-nuit.name': 'Elements · night',
  'theme.elements-nuit.desc': 'Dark variant. Same 17 tokens.',
  'theme.innamoramento.name': 'Innamoramento',
  'theme.innamoramento.desc': 'Deep rose, mauve tiles: the Innamoramento direction.',
  'theme.innamoramento-nuit.name': 'Innamoramento · night',
  'theme.innamoramento-nuit.desc': 'Dark variant. Same 17 tokens.',

  // --- Languages (each language is named in ITS OWN language) --------------
  'language.fr': 'Français',
  'language.en': 'English',

  // --- Dates (when.js) — transposition of the prototype's grammar --------
  'when.month': [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
  ],
  'when.days': [
    'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday',
  ],
  'when.yesterday': 'Yesterday',
  'when.today': 'Today',
  'when.long': '{day}, {time}',
  'when.first': '1',
  'when.inYear': '{month} {day}',
  'when.beyond': '{month} {day}, {year}',
};
