// Catalogue français (PLAN-LANGUES, A15) : le français du prototype,
// mot pour mot — ce fichier EST la référence, l'extraction n'a rien
// changé à l'écran. Gabarits `{nom}` ; une barre `|` sépare le
// singulier du pluriel (la règle par langue vit dans texte.svelte.js).
// Les tables de dates (mois, jours) sont des tableaux : quand.js les
// consomme telles quelles.

export const FR = {
  // --- Dossiers canoniques (nav, statut, conversation) ----------------
  'boite.reception': 'Boîte de réception',
  'boite.envoyes': 'Envoyés',
  'boite.brouillons': 'Brouillons',
  'boite.indesirables': 'Indésirables',
  'boite.archives': 'Archives',
  'boite.corbeille': 'Corbeille',
  'nav.toutes': 'Toutes les boîtes',
  'nav.boites': 'Boîtes',
  'nav.aria': 'Dossiers et comptes',

  // --- Entête de l'écran 02 -------------------------------------------
  'entete.recherche': 'Recherche',
  'entete.chercher': 'Chercher un message, une personne, un fichier',
  'entete.effacerRecherche': 'Effacer la recherche',
  'entete.ecrire': 'Écrire',
  'entete.reglages': 'Réglages',

  // --- Barre de statut --------------------------------------------------
  'statut.recherche': 'Recherche · {n} résultat|Recherche · {n} résultats',
  'statut.recherchePlafond': 'Recherche · {n} sur {total} résultat|Recherche · {n} sur {total} résultats',
  'statut.categorie': '{boite} · {n} élément|{boite} · {n} éléments',
  'statut.synchro': 'Synchronisation · {p} %',
  'statut.rattrapageCorps': 'Rattrapage des messages · {n} restants · {p} %',
  'statut.rattrapageCorpsSeul': 'Rattrapage des messages · {n} restants',
  'statut.rattrapageApercus': 'Rattrapage des aperçus…',
  'statut.envois': "Boîte d'envoi · {n} envoi en attente|Boîte d'envoi · {n} envois en attente",
  'statut.programmes':
    "Boîte d'envoi · {n} envoi programmé · départ {quand}|Boîte d'envoi · {n} envois programmés · prochain départ {quand}",
  'statut.synchroImpossible': 'Synchronisation impossible · nouvelle tentative automatique',
  'statut.synchroImpossibleDepuis':
    'Synchronisation impossible · nouvelle tentative automatique · dernière synchronisation {depuis}',
  'statut.ajour': 'Tous les messages sont à jour',
  'statut.ajourDepuis': 'Tous les messages sont à jour · dernière synchronisation {depuis}',
  'statut.horsLigne': 'Hors ligne',
  'statut.horsLigneDepuis': 'Hors ligne · dernière synchronisation {depuis}',
  'statut.cyclePrefixe': 'Synchronisation',
  'statut.synchroPartielle':
    '{n} compte sur {m} injoignable · nouvelle tentative automatique|{n} comptes sur {m} injoignables · nouvelle tentative automatique',
  'statut.pourcent': '{p} %',
  'statut.phase.inventaire': 'inventaire des dossiers',
  'statut.phase.fils': 'fils de discussion',
  'statut.phase.brouillons': 'brouillons',
  'depuis.instant': "à l'instant",
  'depuis.minutes': 'il y a {n} minute|il y a {n} minutes',
  'depuis.heures': 'il y a {n} heure|il y a {n} heures',
  'depuis.jours': 'il y a {n} jour|il y a {n} jours',
  'statut.demarrage': 'démarrage…',
  'statut.perf': '{total} conversations · première page servie+rendue en {ms} ms',

  // --- Fente d'avis -----------------------------------------------------
  'avis.envoiRefuse': "L'envoi « {sujet} » a été refusé{erreur}.",
  'avis.envoiInterrompu': "L'envoi « {sujet} » a été interrompu{erreur}.",
  'avis.maj': 'Une mise à jour est disponible (version {version}).',
  'avis.crash': "Wind a rencontré un problème lors d'une session précédente ({n} rapport(s) en attente). Rien n'est envoyé sans vous.",
  'avis.telemetrie': "Aider à améliorer Wind ? En cas de plantage, un rapport technique serait enregistré sur votre machine, jamais le contenu de vos mails. Vous choisissez ensuite de l'envoyer.",
  'avis.connexion': 'Compte non reconnecté : {details}',
  'avis.programme': '« {sujet} » partira {quand} — si Wind est ouvert à ce moment-là.',

  // --- Actions partagées ------------------------------------------------
  'action.renvoyer': 'Renvoyer',
  'action.abandonner': 'Abandonner',
  'action.installer': 'Installer',
  'action.plusTard': 'Plus tard',
  'action.ouvrirRapports': 'Ouvrir le dossier des rapports',
  'action.ignorer': 'Ignorer',
  'action.activer': 'Activer',
  'action.nonMerci': 'Non merci',
  'action.reprendre': 'Reprendre',
  'action.reessayer': 'Réessayer',
  'action.synchroniser': 'Synchroniser',
  'action.synchronisation': 'Synchronisation…',
  'action.repondre': 'Répondre',
  'action.repondreTous': 'Répondre à tous',
  'action.transferer': 'Transférer',
  'action.archiver': 'Archiver',
  'action.supprimer': 'Supprimer',
  'action.signalerSpam': 'Signaler comme spam',
  'action.pasSpam': 'Ce n’est pas un spam',
  'action.epingler': 'Épingler',
  'action.desepingler': 'Désépingler',
  'action.envoyer': 'Envoyer',
  'action.annuler': 'Annuler',
  'action.continuer': 'Continuer',
  'action.fermer': 'Fermer',
  'action.replier': 'Replier',
  'action.retirer': 'Retirer',
  'action.termine': 'Terminé',
  'action.annulerEnvoi': "Annuler l'envoi",
  'action.enregistrer': 'Enregistrer',
  'action.effacer': 'Effacer',

  // --- Toasts -----------------------------------------------------------
  'toast.compteAjoute': 'Compte ajouté.',
  'toast.compteRetire': 'Compte retiré.',
  'toast.archivee': 'Conversation archivée.',
  'toast.supprimee': 'Conversation supprimée.',
  'toast.spamSignale': 'Message signalé comme indésirable.',
  'toast.pasSpam': 'Message remis en réception.',
  'toast.pieceEnregistree': 'Pièce enregistrée : {chemin}',
  'toast.brouillonEnregistre': 'Brouillon enregistré.',
  'toast.brouillonSupprime': 'Brouillon supprimé.',
  'toast.brouillonFork': 'Ce brouillon avait changé ailleurs ; votre version a été conservée à part.',
  'toast.envoye': 'Message envoyé.',
  'toast.programme': 'Envoi programmé : départ {quand}.',
  'toast.envoiAnnule': 'Envoi annulé : le message est revenu dans vos brouillons.',
  'toast.signature': 'Signature enregistrée.',
  'toast.signatureTous': 'Signature et choix appliqués à tous les comptes.',
  'toast.echoAttente': 'Copie en cours de synchronisation : réessayez dans un instant.',

  // --- Enveloppes d'erreur (le détail du cœur reste verbatim, L-3) -----
  'erreur.spamImpossible': 'Ce compte n’a pas de dossier indésirable.',
  'erreur.renvoi': 'Renvoi impossible : {err}',
  'erreur.abandon': 'Abandon impossible : {err}',
  'erreur.maj': 'Mise à jour impossible : {err}',
  'erreur.ouverture': 'Ouverture impossible : {err}',
  'erreur.preference': 'Préférence non enregistrée : {err}',
  'erreur.enregistrement': 'Enregistrement impossible : {err}',
  'erreur.transfert': 'Transfert impossible : {err}',
  'erreur.repondreTous': 'Répondre à tous impossible : {err}',
  'erreur.envoi': 'Envoi impossible : {err}',
  'erreur.piece': 'Pièce jointe impossible : {err}',
  'erreur.piecesManquantes':
    "Des pièces du transfert manquent encore : attendez le rapatriement, réessayez, ou retirez-les avant d'envoyer.",
  'erreur.aucunCompte': 'Aucun compte émetteur : ajoutez un compte.',
  'erreur.connexion': 'Connexion impossible : {err}',
  'erreur.differePasse': 'Choisissez une date à venir.',
  'erreur.annulerEnvoi': 'Annulation impossible : {err}',
  'erreur.annulerTard': "Trop tard : l'envoi est déjà parti.",
  'erreur.signature': 'Signature non enregistrée : {err}',

  // --- Liste ------------------------------------------------------------
  'liste.aria': 'Liste des messages',
  'liste.aucunResultat': 'Aucun résultat.',
  'liste.vide': 'Aucun message ici.',
  'liste.chargerPlus': 'Afficher le résultat suivant|Afficher les {n} résultats suivants',
  'liste.affiner': 'Affinez votre recherche (from:, to:, date:) pour aller plus loin.',
  'liste.prefixeBrouillon': 'Brouillon : ',
  'liste.dest': 'À : {a}',
  'brouillons.a': 'À : {a}',
  'brouillons.sansDestinataire': '(sans destinataire)',
  'brouillons.sansObjet': '(sans objet)',
  'puce.messages': '{n} message|{n} messages',
  'puce.fichiers': '{n} fichier|{n} fichiers',
  'puce.epingle': 'Épinglé',
  'onglet.tous': 'Tous',
  'onglet.nonlus': 'Non lus',

  // --- Volet de lecture -------------------------------------------------
  'lecture.aria': 'Message',
  'lecture.vide': 'Sélectionnez un message pour le lire.',
  'lecture.ouvrir': 'Ouvrir',
  'lecture.imagesBloquees': '{n} image distante bloquée pour protéger votre vie privée.|{n} images distantes bloquées pour protéger votre vie privée.',
  'lecture.afficherImages': 'Afficher les images',
  'lecture.corps': 'Contenu du message',
  'lecture.enregistrer': 'Enregistrer…',
  'lecture.voileEnregistrer': 'Enregistrer',

  // --- Conversation (écran 03) ------------------------------------------
  'conv.deplier': 'Tout déplier',
  'conv.replier': 'Tout replier',
  'conv.brouillon': 'Brouillon',
  'conv.adrDest': '{adr} · à {qui}',
  'conv.de': 'De',
  'conv.a': 'À',
  'conv.objet': 'Objet',
  'conv.fichiersJoints': 'Fichiers joints',

  // --- Composition ------------------------------------------------------
  // Reconnexion d'un compte au jeton mort (constat terrain 2026-08-20).
  'reglages.deconnecte': 'Déconnecté',
  'reglages.reconnecter': 'Reconnecter',
  'reglages.reconnecterCompte': 'Reconnecter {email}',
  'reglages.reconnexionEnCours': 'Consentement en cours…',
  'reglages.reconnexionImpossible': 'Reconnexion impossible : {err}',
  'reglages.repereCompte': 'Repère de {email}',
  'reglages.repereTitre': 'Icône et couleur du compte',
  'reglages.repereIcones': 'Icône du repère',
  'reglages.repereTeintes': 'Couleur du repère',
  'reglages.repereRetirer': 'Retirer le repère',
  'reglages.repereImpossible': 'Repère non enregistré : {err}',
  'repere.icone.home': 'Maison',
  'repere.icone.work': 'Travail',
  'repere.icone.school': 'Études',
  'repere.icone.star': 'Étoile',
  'repere.icone.favorite': 'Cœur',
  'repere.icone.flight': 'Voyage',
  'repere.icone.shopping_bag': 'Achats',
  'repere.icone.account_balance': 'Banque',
  'repere.icone.sports_esports': 'Jeux',
  'repere.icone.eco': 'Nature',
  'repere.icone.pets': 'Animaux',
  'repere.icone.music_note': 'Musique',
  'repere.teinte.rouge': 'Rouge',
  'repere.teinte.orange': 'Orange',
  'repere.teinte.ocre': 'Ocre',
  'repere.teinte.olive': 'Olive',
  'repere.teinte.vert': 'Vert',
  'repere.teinte.sapin': 'Sapin',
  'repere.teinte.bleu': 'Bleu',
  'repere.teinte.indigo': 'Indigo',
  'repere.teinte.violet': 'Violet',
  'repere.teinte.magenta': 'Magenta',
  'repere.teinte.rose': 'Rose',
  'repere.teinte.brun': 'Brun',

  'compo.nouveau': 'Nouveau message',
  'compo.re': 'Re : {sujet}',
  'compo.tr': 'Tr : {sujet}',
  'compo.bonjour': 'Bonjour {prenom},',
  'compo.sansObjet': 'sans objet',
  'compo.compteEmetteur': 'Compte émetteur',
  'compo.destinataire': 'Destinataire',
  'compo.suggestions': 'Adresses suggérées',
  'compo.objetPlaceholder': 'Objet du message',
  'compo.corpsPlaceholder': 'Votre message…',
  'compo.cc': 'Cc',
  'compo.cci': 'Cci',
  // Barre de mise en forme réelle (PLAN-COMPOSITION-HTML, R4). Lien et
  // Citation RETIRÉS (décision CE D1 : périmètre strict).
  'compo.police': 'Police',
  'compo.policeSans': 'Sans serif',
  'compo.policeSerif': 'Serif',
  'compo.policeMono': 'Monospace',
  'compo.taille': 'Taille',
  'compo.taillePetit': 'Petit',
  'compo.tailleNormal': 'Normal',
  'compo.tailleGrand': 'Grand',
  'compo.tailleTresGrand': 'Très grand',
  'compo.gras': 'Gras',
  'compo.italique': 'Italique',
  'compo.souligne': 'Souligné',
  'compo.barre': 'Barré',
  'compo.couleur': 'Couleur du texte',
  'compo.alignerGauche': 'Aligner à gauche',
  'compo.alignerCentre': 'Centrer',
  'compo.alignerDroite': 'Aligner à droite',
  'compo.listePuces': 'Liste à puces',
  'compo.listeNumerotee': 'Liste numérotée',
  'compo.retraitMoins': 'Diminuer le retrait',
  'compo.retraitPlus': 'Augmenter le retrait',
  'compo.effacerFormat': 'Effacer la mise en forme',
  'compo.joindre': 'Joindre',
  'compo.retirerPiece': 'Retirer {nom}',
  'compo.rapatriement': '{nom} · rapatriement…',
  'compo.poidsTotal': '{poids} / 25 Mo',
  'compo.pieceRefusee': '« {nom} » dépasse la place restante ({reste}).',
  'compo.enregistrerBrouillon': 'Enregistrer le brouillon',
  'compo.supprimerBrouillon': 'Supprimer le brouillon',
  'compo.supprConfirme': 'Supprimer ce brouillon ? C’est définitif.',
  // R3 (PLAN-RETOURS-6) : le marquage « important » de l'envoi —
  // bouton-icône de la barre de mise en forme, l'infobulle dit le geste.
  'compo.importantTitre': 'Marquer le message comme important',
  // R2 : l'envoi différé — la carte au-dessus du pied.
  'compo.plusTard': 'Envoyer plus tard',
  'compo.differeQuand': 'Départ',
  'compo.differeNote': 'Le message partira à cette heure si Wind est ouvert — sinon au prochain lancement.',
  'compo.programmer': 'Programmer',

  // --- Écran 01 et guichet de compte ------------------------------------
  'accueil.bienvenue': 'Bienvenue dans',
  'accueil.etape': 'Étape {n}/{total}',
  'accueil.ajouterSous': 'Pour commencer, ajoutez une adresse email.',
  'accueil.ajouter': 'Ajouter',
  'accueil.ajouterAutre': 'Ajouter une autre adresse email',
  'accueil.retour': 'Retour',
  'accueil.continuer': 'Continuer',
  'accueil.terminer': 'Terminer',
  'accueil.voletsTitre': 'Choisissez votre disposition de fenêtre',
  'accueil.voletsSous': 'Vous pourrez la changer plus tard dans Réglages > Affichage.',
  'accueil.themeTitre': 'Choisissez votre thème',
  'accueil.themeSous': 'Vous pourrez le changer plus tard dans Réglages > Thèmes.',
  'accueil.finTitre': 'Tout est prêt.',
  'accueil.finTexte': 'Vérifiez vos choix avant de continuer.',
  'accueil.revenir': 'Revenir à cette étape',
  'accueil.theme': 'Thème',
  'guichet.adresse': 'Adresse e-mail',
  'guichet.mdp': 'Mot de passe',
  'guichet.imap': 'Serveur IMAP',
  'guichet.smtp': 'Serveur SMTP',
  'guichet.port': 'Port',
  'guichet.adresseInvalide': 'Saisissez votre adresse e-mail complète.',
  'guichet.autorisation': 'Autorisation en cours dans votre navigateur…',
  'guichet.verification': 'Vérification de la connexion au serveur…',
  'guichet.noteGenerique': 'Renseignez les serveurs de votre fournisseur. Le mot de passe rejoint le coffre du système, jamais un fichier.',
  'guichet.noteAuto': "Le serveur est détecté automatiquement. Rien d'autre à régler.",

  // --- Modale de migration ----------------------------------------------
  'migration.aria': 'Mise à jour de la base de messages',
  'migration.titre': 'Mise à jour de votre boîte.',
  'migration.note': 'Environ {n} messages sont mis à jour. Cette mise à jour ne se fait qu’une fois et n’efface rien.',
  'migration.preparation': 'Préparation…',
  'migration.pourcent': '{p} %',
  'migration.annulee': 'Mise à jour annulée, tout est revenu comme avant. Elle reprendra au prochain lancement, ou tout de suite :',
  'migration.echec': 'La mise à jour a échoué ({err}). Rien n’est perdu : elle peut être relancée.',

  // --- Réglages ---------------------------------------------------------
  'reglages.groupesAria': 'Groupes de réglages',
  'groupe.comptes': 'Comptes',
  'groupe.themes': 'Thèmes',
  'groupe.affichage': 'Affichage',
  'groupe.notifications': 'Notifications',
  'groupe.signature': 'Signature',
  'groupe.raccourcis': 'Raccourcis',
  'groupe.apropos': 'À propos',
  'reglages.sectionThemes': 'Thème de couleur',
  'reglages.sectionRaccourcis': 'Raccourcis clavier',
  'reglages.ajouterCompte': 'Ajouter un compte',
  'reglages.retirerCompte': 'Retirer {email}',
  'reglages.retirerConfirme': 'Retirer {email} ? Son courrier local est effacé et sa connexion oubliée. Rien n’est supprimé sur le serveur.',
  'reglages.retraitEnCours': 'Retrait…',
  'reglages.retraitImpossible': 'Retrait impossible : {err}',
  'reglages.sombreAuto': 'Sombre automatique',
  'reglages.sombreAutoDesc': "Suivre le réglage sombre du système : la déclinaison nuit du thème choisi s'affiche quand il est actif, la claire revient dès qu'il s'éteint. Un thème nuit choisi à la main reste tel quel.",
  'reglages.langue': 'Langue',
  'reglages.langueDesc': "La langue de l'interface, appliquée immédiatement.",
  'reglages.volets': 'Disposition',
  'reglages.voletsDesc':
    "Le nombre de volets de l'écran principal. En dessous de trois, la lecture s'ouvre en plein écran ; en un volet, la navigation vit dans un tiroir.",
  'volets.3': 'Trois volets',
  'volets.2': 'Deux volets',
  'volets.1': 'Un volet',
  'nav.ouvrirTiroir': 'Ouvrir la navigation',
  'nav.fermerTiroir': 'Fermer la navigation',
  'volets.poigneeNav': 'Régler la largeur de la navigation',
  'volets.poigneeListe': 'Régler la largeur de la liste',
  'reglages.bulles': "Bulles d'arrivée",
  'reglages.bullesDesc': "Une bulle système annonce les nouveaux messages à la synchronisation. La couper n'arrête jamais la synchronisation elle-même.",
  'reglages.noteRaccourcis': 'Dans un champ de saisie, les lettres redeviennent des lettres ; seul Échap garde un sens.',
  'reglages.version': 'Version',
  'reglages.maj': 'Mises à jour',
  'reglages.verifierMaj': 'Vérifier les mises à jour',
  'reglages.verification': 'Vérification…',
  'reglages.ajour': 'Vous êtes à jour.',
  'reglages.majDisponible': 'Version {version} disponible.',
  'reglages.majImpossible': 'Vérification impossible : {err}',
  'reglages.installation': 'Téléchargement et installation…',
  'reglages.signatureDesc':
    "Une signature par compte, ajoutée au bas des messages que vous composez. La mise en forme du composeur s'applique.",
  'reglages.signaturePlaceholder': 'Votre signature…',
  'reglages.signatureRepliques': 'Aussi dans les réponses et transferts',
  'reglages.signatureRepliquesDesc':
    'Sinon, la signature ne s’ajoute qu’aux nouveaux messages.',
  'reglages.signatureTous': 'Appliquer à tous les comptes',
  'reglages.icones': 'Icônes',
  'reglages.iconesValeur': 'Material Symbols Rounded (Google), licence Apache 2.0 ; police embarquée, aucun réseau.',

  // --- Raccourcis (table D3, référence) ---------------------------------
  'raccourci.touche.c': 'c',
  'raccourci.touche.r': 'r',
  'raccourci.touche.f': 'f',
  'raccourci.touche.e': 'e',
  'raccourci.touche.suppr': 'Suppr',
  'raccourci.touche.slash': '/',
  'raccourci.touche.echap': 'Échap',
  'raccourci.geste.c': 'Écrire un nouveau message',
  'raccourci.geste.r': 'Répondre à la conversation sélectionnée',
  'raccourci.geste.f': 'Transférer la conversation sélectionnée',
  'raccourci.geste.e': 'Archiver la conversation sélectionnée',
  'raccourci.geste.suppr': 'Supprimer la conversation sélectionnée',
  'raccourci.geste.slash': 'Aller à la recherche',
  'raccourci.geste.echap': 'Fermer la surimpression, sortir du champ, revenir à la boîte',

  // --- Thèmes Clarity (fiches du dialogue Réglages) ---------------------
  // A42 « Wada élargi » : 28 fiches, mot pour mot du paquet livré
  // (docs/PLAN-WADA-ELARGI.md — le paquet d'étude ne rentre pas au
  // dépôt, esprit DC-D4).
  'theme.nature.nom': 'La nature',
  'theme.nature.desc': 'Vert pin sur ivoire, la direction de référence.',
  'theme.hortensia.nom': "L'hortensia",
  'theme.hortensia.desc': 'Bleu hortensia posé, fonds bleutés pâles.',
  'theme.coquelicot.nom': 'Le coquelicot',
  'theme.coquelicot.desc': 'Rouge coquelicot assourdi sur papier chaud.',
  'theme.chaume.nom': 'Le chaume',
  'theme.chaume.desc': 'Or de paille éteint, jaunes de toit sec.',
  'theme.bruyere.nom': 'La bruyère',
  'theme.bruyere.desc': 'Vieux rose bruyère, gris rosés.',
  'theme.source.nom': 'La source',
  'theme.source.desc': 'Sarcelle grisée, eaux froides claires.',
  'theme.bleuet.nom': 'Le bleuet',
  'theme.bleuet.desc': 'Bleu bleuet franc mais mat.',
  'theme.lavande.nom': 'La lavande',
  'theme.lavande.desc': 'Lavande grise, bleus mauves.',
  'theme.rosee.nom': 'La rosée',
  'theme.rosee.desc': "Bleu-vert d'eau froide, très clair.",
  'theme.iris.nom': "L'iris",
  'theme.iris.desc': "Ivoire rosé, indigo d'iris, sélection amande.",
  'theme.moisson.nom': 'La moisson',
  'theme.moisson.desc': 'Paille mûre, bleu ardoise, abricot.',
  'theme.grenade.nom': 'La grenade',
  'theme.grenade.desc': "Sable rosé, carmin profond, vert d'eau.",
  'theme.safran.nom': 'Le safran',
  'theme.safran.desc': 'Blanc cassé, safran brûlé, bleu-gris.',
  'theme.estampe.nom': "L'estampe",
  'theme.estampe.desc': 'Gris perle, vermillon sombre, bleu lavis.',
  'theme.nature-nuit.nom': 'La nature · nuit',
  'theme.nature-nuit.desc': 'Déclinaison sombre. Mêmes 17 jetons.',
  'theme.hortensia-nuit.nom': "L'hortensia · nuit",
  'theme.hortensia-nuit.desc': 'Déclinaison sombre. Mêmes 17 jetons.',
  'theme.coquelicot-nuit.nom': 'Le coquelicot · nuit',
  'theme.coquelicot-nuit.desc': 'Déclinaison sombre. Mêmes 17 jetons.',
  'theme.chaume-nuit.nom': 'Le chaume · nuit',
  'theme.chaume-nuit.desc': 'Déclinaison sombre. Mêmes 17 jetons.',
  'theme.bruyere-nuit.nom': 'La bruyère · nuit',
  'theme.bruyere-nuit.desc': 'Déclinaison sombre. Mêmes 17 jetons.',
  'theme.source-nuit.nom': 'La source · nuit',
  'theme.source-nuit.desc': 'Déclinaison sombre. Mêmes 17 jetons.',
  'theme.bleuet-nuit.nom': 'Le bleuet · nuit',
  'theme.bleuet-nuit.desc': 'Déclinaison sombre. Mêmes 17 jetons.',
  'theme.lavande-nuit.nom': 'La lavande · nuit',
  'theme.lavande-nuit.desc': 'Déclinaison sombre. Mêmes 17 jetons.',
  'theme.rosee-nuit.nom': 'La rosée · nuit',
  'theme.rosee-nuit.desc': 'Déclinaison sombre. Mêmes 17 jetons.',
  'theme.iris-nuit.nom': "L'iris · nuit",
  'theme.iris-nuit.desc': 'Déclinaison sombre. Mêmes 17 jetons.',
  'theme.moisson-nuit.nom': 'La moisson · nuit',
  'theme.moisson-nuit.desc': 'Déclinaison sombre. Mêmes 17 jetons.',
  'theme.grenade-nuit.nom': 'La grenade · nuit',
  'theme.grenade-nuit.desc': 'Déclinaison sombre. Mêmes 17 jetons.',
  'theme.safran-nuit.nom': 'Le safran · nuit',
  'theme.safran-nuit.desc': 'Déclinaison sombre. Mêmes 17 jetons.',
  'theme.estampe-nuit.nom': "L'estampe · nuit",
  'theme.estampe-nuit.desc': 'Déclinaison sombre. Mêmes 17 jetons.',

  // --- Langues (chaque langue se nomme dans SA langue, les deux
  //     catalogues portent les mêmes valeurs) --------------------------
  'langue.fr': 'Français',
  'langue.en': 'English',

  // --- Dates (quand.js) — formes exactes du prototype -------------------
  'quand.mois': [
    'janv.', 'févr.', 'mars', 'avr.', 'mai', 'juin',
    'juil.', 'août', 'sept.', 'oct.', 'nov.', 'déc.',
  ],
  'quand.jours': [
    'Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi',
  ],
  'quand.hier': 'Hier',
  'quand.aujourdhui': "Aujourd'hui",
  'quand.long': '{jour}, {heure}',
  'quand.premier': '1ᵉʳ',
  'quand.dansAnnee': '{jour} {mois}',
  'quand.auDela': '{jour} {mois} {annee}',
};
