// Catalogue anglais (PLAN-LANGUES, A15) : transposition de la grammaire
// du prototype, jamais une invention — mêmes clés que catalogue.fr.js,
// l'audit e2e casse au moindre écart. Les guillemets « » deviennent
// “ ”, l'heure reste sur 24 h (on livre une langue, pas une locale).

export const EN = {
  // --- Dossiers canoniques (nav, statut, conversation) ----------------
  'boite.reception': 'Inbox',
  'boite.envoyes': 'Sent',
  'boite.brouillons': 'Drafts',
  'boite.indesirables': 'Junk',
  'boite.archives': 'Archives',
  'boite.corbeille': 'Trash',
  'nav.toutes': 'All inboxes',
  'nav.boites': 'Inboxes',
  'nav.aria': 'Folders and accounts',

  // --- Entête de l'écran 02 -------------------------------------------
  'entete.recherche': 'Search',
  'entete.chercher': 'Search messages, people, files',
  'entete.effacerRecherche': 'Clear search',
  'entete.ecrire': 'Compose',
  'entete.reglages': 'Settings',

  // --- Barre de statut --------------------------------------------------
  'statut.recherche': 'Search · {n} result|Search · {n} results',
  'statut.recherchePlafond': 'Search · {n} of {total} result|Search · {n} of {total} results',
  'statut.categorie': '{boite} · {n} item|{boite} · {n} items',
  'statut.synchro': 'Syncing · {p}%',
  'statut.rattrapageCorps': 'Catching up on messages · {n} to go · {p} %',
  'statut.rattrapageCorpsSeul': 'Catching up on messages · {n} to go',
  'statut.rattrapageApercus': 'Catching up on previews…',
  'statut.envois': 'Outbox · {n} message waiting|Outbox · {n} messages waiting',
  'statut.programmes':
    'Outbox · {n} message scheduled · leaves {quand}|Outbox · {n} messages scheduled · next leaves {quand}',
  'statut.synchroImpossible': 'Sync failed · will retry automatically',
  'statut.synchroImpossibleDepuis':
    'Sync failed · will retry automatically · last synced {depuis}',
  'statut.ajour': 'All messages are up to date',
  'statut.ajourDepuis': 'All messages are up to date · last synced {depuis}',
  'statut.horsLigne': 'Offline',
  'statut.horsLigneDepuis': 'Offline · last synced {depuis}',
  'statut.cyclePrefixe': 'Syncing',
  'statut.synchroPartielle':
    '{n} account of {m} unreachable · will retry automatically|{n} accounts of {m} unreachable · will retry automatically',
  'statut.pourcent': '{p}%',
  'statut.phase.inventaire': 'folder inventory',
  'statut.phase.fils': 'conversation threads',
  'statut.phase.brouillons': 'drafts',
  'depuis.instant': 'just now',
  'depuis.minutes': '{n} minute ago|{n} minutes ago',
  'depuis.heures': '{n} hour ago|{n} hours ago',
  'depuis.jours': '{n} day ago|{n} days ago',
  'statut.demarrage': 'starting…',
  'statut.perf': '{total} conversations · first page served+rendered in {ms} ms',

  // --- Fente d'avis -----------------------------------------------------
  'avis.envoiRefuse': 'The message “{sujet}” was rejected{erreur}.',
  'avis.envoiInterrompu': 'The message “{sujet}” was interrupted{erreur}.',
  'avis.maj': 'An update is available (version {version}).',
  'avis.crash': 'Wind ran into a problem during a previous session ({n} report(s) pending). Nothing is sent without you.',
  'avis.telemetrie': 'Help improve Wind? If it crashes, a technical report would be saved on your machine, never the content of your mail. You then choose whether to send it.',
  'avis.connexion': 'Account not reconnected: {details}',
  'avis.programme': '“{sujet}” will be sent {quand} — if Wind is open at that time.',

  // --- Actions partagées ------------------------------------------------
  'action.renvoyer': 'Send again',
  'action.abandonner': 'Discard',
  'action.installer': 'Install',
  'action.plusTard': 'Later',
  'action.ouvrirRapports': 'Open the reports folder',
  'action.ignorer': 'Dismiss',
  'action.activer': 'Turn on',
  'action.nonMerci': 'No thanks',
  'action.reprendre': 'Resume',
  'action.reessayer': 'Try again',
  'action.synchroniser': 'Sync',
  'action.synchronisation': 'Syncing…',
  'action.repondre': 'Reply',
  'action.repondreTous': 'Reply all',
  'action.transferer': 'Forward',
  'action.archiver': 'Archive',
  'action.signalerSpam': 'Report as spam',
  'action.pasSpam': 'Not spam',
  'action.epingler': 'Pin',
  'action.desepingler': 'Unpin',
  'action.supprimer': 'Delete',
  'action.envoyer': 'Send',
  'action.annuler': 'Cancel',
  'action.continuer': 'Continue',
  'action.fermer': 'Close',
  'action.replier': 'Collapse',
  'action.retirer': 'Remove',
  'action.termine': 'Done',
  'action.annulerEnvoi': 'Cancel send',
  'action.enregistrer': 'Save',
  'action.effacer': 'Clear',

  // --- Toasts -----------------------------------------------------------
  'toast.compteAjoute': 'Account added.',
  'toast.compteRetire': 'Account removed.',
  'toast.archivee': 'Conversation archived.',
  'toast.supprimee': 'Conversation deleted.',
  'toast.spamSignale': 'Reported as spam.',
  'toast.pasSpam': 'Moved back to Inbox.',
  'toast.pieceEnregistree': 'Attachment saved: {chemin}',
  'toast.brouillonEnregistre': 'Draft saved.',
  'toast.brouillonSupprime': 'Draft deleted.',
  'toast.brouillonFork': 'This draft had changed elsewhere; your version was kept separately.',
  'toast.envoye': 'Message sent.',
  'toast.programme': 'Send scheduled: leaves {quand}.',
  'toast.envoiAnnule': 'Send cancelled: the message is back in your drafts.',
  'toast.signature': 'Signature saved.',
  'toast.signatureTous': 'Signature and choice applied to all accounts.',
  'toast.echoAttente': 'Copy still syncing: try again in a moment.',

  // --- Enveloppes d'erreur (le détail du cœur reste verbatim, L-3) -----
  'erreur.spamImpossible': 'This account has no spam folder.',
  'erreur.renvoi': 'Could not resend: {err}',
  'erreur.abandon': 'Could not discard: {err}',
  'erreur.maj': 'Update failed: {err}',
  'erreur.ouverture': 'Could not open: {err}',
  'erreur.preference': 'Preference not saved: {err}',
  'erreur.enregistrement': 'Could not save: {err}',
  'erreur.transfert': 'Could not forward: {err}',
  'erreur.repondreTous': 'Could not reply all: {err}',
  'erreur.envoi': 'Could not send: {err}',
  'erreur.piece': 'Could not attach: {err}',
  'erreur.piecesManquantes':
    'Some forwarded files are still missing: wait for retrieval, try again, or remove them before sending.',
  'erreur.aucunCompte': 'No sending account: add an account.',
  'erreur.connexion': 'Could not connect: {err}',
  'erreur.differePasse': 'Pick a time in the future.',
  'erreur.annulerEnvoi': 'Could not cancel: {err}',
  'erreur.annulerTard': 'Too late: the message already left.',
  'erreur.signature': 'Signature not saved: {err}',

  // --- Liste ------------------------------------------------------------
  'liste.aria': 'Message list',
  'liste.aucunResultat': 'No results.',
  'liste.vide': 'No messages here.',
  'liste.chargerPlus': 'Show the next result|Show the next {n} results',
  'liste.affiner': 'Refine your search (from:, to:, date:) to go further.',
  'liste.prefixeBrouillon': 'Draft: ',
  'liste.dest': 'To: {a}',
  'brouillons.a': 'To: {a}',
  'brouillons.sansDestinataire': '(no recipient)',
  'brouillons.sansObjet': '(no subject)',
  'puce.messages': '{n} message|{n} messages',
  'puce.fichiers': '{n} file|{n} files',
  'puce.epingle': 'Pinned',
  'onglet.tous': 'All',
  'onglet.nonlus': 'Unread',

  // --- Volet de lecture -------------------------------------------------
  'lecture.aria': 'Message',
  'lecture.vide': 'Select a message to read it.',
  'lecture.ouvrir': 'Open',
  'lecture.imagesBloquees': '{n} remote image blocked to protect your privacy.|{n} remote images blocked to protect your privacy.',
  'lecture.afficherImages': 'Show images',
  'lecture.corps': 'Message content',
  'lecture.enregistrer': 'Save…',
  'lecture.voileEnregistrer': 'Save',

  // --- Conversation (écran 03) ------------------------------------------
  'conv.deplier': 'Expand all',
  'conv.replier': 'Collapse all',
  'conv.brouillon': 'Draft',
  'conv.adrDest': '{adr} · to {qui}',
  'conv.de': 'From',
  'conv.a': 'To',
  'conv.objet': 'Subject',
  'conv.fichiersJoints': 'Attachments',

  // --- Composition ------------------------------------------------------
  // Reconnexion d'un compte au jeton mort (constat terrain 2026-08-20).
  'reglages.deconnecte': 'Disconnected',
  'reglages.reconnecter': 'Reconnect',
  'reglages.reconnecterCompte': 'Reconnect {email}',
  'reglages.reconnexionEnCours': 'Waiting for consent…',
  'reglages.reconnexionImpossible': 'Reconnection failed: {err}',
  'reglages.repereCompte': 'Marker for {email}',
  'reglages.repereTitre': 'Account icon and color',
  'reglages.repereIcones': 'Marker icon',
  'reglages.repereTeintes': 'Marker color',
  'reglages.repereRetirer': 'Remove marker',
  'reglages.repereImpossible': 'Marker not saved: {err}',
  'repere.icone.home': 'Home',
  'repere.icone.work': 'Work',
  'repere.icone.school': 'School',
  'repere.icone.star': 'Star',
  'repere.icone.favorite': 'Heart',
  'repere.icone.flight': 'Travel',
  'repere.icone.shopping_bag': 'Shopping',
  'repere.icone.account_balance': 'Bank',
  'repere.icone.sports_esports': 'Games',
  'repere.icone.eco': 'Nature',
  'repere.icone.pets': 'Pets',
  'repere.icone.music_note': 'Music',
  'repere.teinte.rouge': 'Red',
  'repere.teinte.orange': 'Orange',
  'repere.teinte.ocre': 'Ochre',
  'repere.teinte.olive': 'Olive',
  'repere.teinte.vert': 'Green',
  'repere.teinte.sapin': 'Pine',
  'repere.teinte.bleu': 'Blue',
  'repere.teinte.indigo': 'Indigo',
  'repere.teinte.violet': 'Purple',
  'repere.teinte.magenta': 'Magenta',
  'repere.teinte.rose': 'Pink',
  'repere.teinte.brun': 'Brown',

  'compo.nouveau': 'New message',
  'compo.re': 'Re: {sujet}',
  'compo.tr': 'Fwd: {sujet}',
  'compo.bonjour': 'Hello {prenom},',
  'compo.sansObjet': 'no subject',
  'compo.compteEmetteur': 'Sending account',
  'compo.destinataire': 'Recipient',
  'compo.suggestions': 'Suggested addresses',
  'compo.objetPlaceholder': 'Message subject',
  'compo.corpsPlaceholder': 'Your message…',
  'compo.cc': 'Cc',
  'compo.cci': 'Bcc',
  // Barre de mise en forme réelle (PLAN-COMPOSITION-HTML, R4). Lien et
  // Citation RETIRÉS (décision CE D1 : périmètre strict).
  'compo.police': 'Font',
  'compo.policeSans': 'Sans serif',
  'compo.policeSerif': 'Serif',
  'compo.policeMono': 'Monospace',
  'compo.taille': 'Size',
  'compo.taillePetit': 'Small',
  'compo.tailleNormal': 'Normal',
  'compo.tailleGrand': 'Large',
  'compo.tailleTresGrand': 'Extra large',
  'compo.gras': 'Bold',
  'compo.italique': 'Italic',
  'compo.souligne': 'Underline',
  'compo.barre': 'Strikethrough',
  'compo.couleur': 'Text color',
  'compo.alignerGauche': 'Align left',
  'compo.alignerCentre': 'Center',
  'compo.alignerDroite': 'Align right',
  'compo.listePuces': 'Bulleted list',
  'compo.listeNumerotee': 'Numbered list',
  'compo.retraitMoins': 'Decrease indent',
  'compo.retraitPlus': 'Increase indent',
  'compo.effacerFormat': 'Clear formatting',
  'compo.joindre': 'Attach',
  'compo.retirerPiece': 'Remove {nom}',
  'compo.rapatriement': '{nom} · retrieving…',
  'compo.poidsTotal': '{poids} / 25 MB',
  'compo.pieceRefusee': '"{nom}" exceeds the remaining space ({reste}).',
  'compo.enregistrerBrouillon': 'Save draft',
  'compo.supprimerBrouillon': 'Delete draft',
  'compo.supprConfirme': 'Delete this draft? This cannot be undone.',
  // R3 (PLAN-RETOURS-6) : le marquage « important » de l'envoi —
  // bouton-icône de la barre de mise en forme, l'infobulle dit le geste.
  'compo.importantTitre': 'Mark the message as important',
  // R2 : l'envoi différé — la carte au-dessus du pied.
  'compo.plusTard': 'Send later',
  'compo.differeQuand': 'Leaves',
  'compo.differeNote': 'The message will be sent at that time if Wind is open — otherwise at the next launch.',
  'compo.programmer': 'Schedule',

  // --- Écran 01 et guichet de compte ------------------------------------
  'accueil.bienvenue': 'Welcome to',
  'accueil.etape': 'Step {n}/{total}',
  'accueil.ajouterSous': 'To begin, add an email address.',
  'accueil.ajouter': 'Add',
  'accueil.ajouterAutre': 'Add another email address',
  'accueil.retour': 'Back',
  'accueil.continuer': 'Continue',
  'accueil.terminer': 'Finish',
  'accueil.voletsTitre': 'Choose your window layout',
  'accueil.voletsSous': 'You can change it later in Settings > Display.',
  'accueil.themeTitre': 'Choose your theme',
  'accueil.themeSous': 'You can change it later in Settings > Themes.',
  'accueil.finTitre': 'All set.',
  'accueil.finTexte': 'Check your choices before finishing.',
  'accueil.revenir': 'Return to this step',
  'accueil.theme': 'Theme',
  'guichet.adresse': 'Email address',
  'guichet.mdp': 'Password',
  'guichet.imap': 'IMAP server',
  'guichet.smtp': 'SMTP server',
  'guichet.port': 'Port',
  'guichet.adresseInvalide': 'Enter your full email address.',
  'guichet.autorisation': 'Authorization in progress in your browser…',
  'guichet.verification': 'Checking the connection to the server…',
  'guichet.noteGenerique': "Enter your provider's servers. The password goes to the system vault, never a file.",
  'guichet.noteAuto': 'The server is detected automatically. Nothing else to set.',

  // --- Modale de migration ----------------------------------------------
  'migration.aria': 'Message database update',
  'migration.titre': 'Updating your mailbox.',
  'migration.note': 'About {n} messages are being updated. This runs only once and deletes nothing.',
  'migration.preparation': 'Preparing…',
  'migration.pourcent': '{p}%',
  'migration.annulee': 'Update canceled, everything is back as before. It will resume at the next launch, or right away:',
  'migration.echec': 'The update failed ({err}). Nothing is lost: it can be run again.',

  // --- Réglages ---------------------------------------------------------
  'reglages.groupesAria': 'Settings groups',
  'groupe.comptes': 'Accounts',
  'groupe.themes': 'Themes',
  'groupe.affichage': 'Display',
  'groupe.notifications': 'Notifications',
  'groupe.signature': 'Signature',
  'groupe.raccourcis': 'Shortcuts',
  'groupe.apropos': 'About',
  'reglages.sectionThemes': 'Color theme',
  'reglages.sectionRaccourcis': 'Keyboard shortcuts',
  'reglages.ajouterCompte': 'Add an account',
  'reglages.retirerCompte': 'Remove {email}',
  'reglages.retirerConfirme': 'Remove {email}? Its local mail is erased and its connection forgotten. Nothing is deleted on the server.',
  'reglages.retraitEnCours': 'Removing…',
  'reglages.retraitImpossible': 'Removal failed: {err}',
  'reglages.sombreAuto': 'Automatic dark',
  'reglages.sombreAutoDesc': 'Follow the system dark setting: the night variant of your chosen theme shows while it is on, the light one returns as soon as it turns off. A hand-picked night theme stays as it is.',
  'reglages.langue': 'Language',
  'reglages.langueDesc': 'The interface language, applied immediately.',
  'reglages.volets': 'Layout',
  'reglages.voletsDesc':
    'How many panes the main screen shows. Below three, reading opens full screen; with one pane, navigation lives in a drawer.',
  'volets.3': 'Three panes',
  'volets.2': 'Two panes',
  'volets.1': 'One pane',
  'nav.ouvrirTiroir': 'Open navigation',
  'nav.fermerTiroir': 'Close navigation',
  'volets.poigneeNav': 'Resize the navigation pane',
  'volets.poigneeListe': 'Resize the list pane',
  'reglages.bulles': 'Arrival notifications',
  'reglages.bullesDesc': 'A system notification announces new messages at sync. Turning it off never stops the sync itself.',
  'reglages.noteRaccourcis': 'In a text field, letters are letters again; only Esc keeps a meaning.',
  'reglages.version': 'Version',
  'reglages.maj': 'Updates',
  'reglages.verifierMaj': 'Check for updates',
  'reglages.verification': 'Checking…',
  'reglages.ajour': 'You are up to date.',
  'reglages.majDisponible': 'Version {version} available.',
  'reglages.majImpossible': 'Check failed: {err}',
  'reglages.installation': 'Downloading and installing…',
  'reglages.signatureDesc':
    'One signature per account, added at the bottom of messages you compose. Composer formatting applies.',
  'reglages.signaturePlaceholder': 'Your signature…',
  'reglages.signatureRepliques': 'Also in replies and forwards',
  'reglages.signatureRepliquesDesc': 'Otherwise the signature is only added to new messages.',
  'reglages.signatureTous': 'Apply to all accounts',
  'reglages.icones': 'Icons',
  'reglages.iconesValeur': 'Material Symbols Rounded (Google), Apache 2.0 license; bundled font, no network.',

  // --- Raccourcis (table D3, référence) ---------------------------------
  'raccourci.touche.c': 'c',
  'raccourci.touche.r': 'r',
  'raccourci.touche.f': 'f',
  'raccourci.touche.e': 'e',
  'raccourci.touche.suppr': 'Del',
  'raccourci.touche.slash': '/',
  'raccourci.touche.echap': 'Esc',
  'raccourci.geste.c': 'Compose a new message',
  'raccourci.geste.r': 'Reply to the selected conversation',
  'raccourci.geste.f': 'Forward the selected conversation',
  'raccourci.geste.e': 'Archive the selected conversation',
  'raccourci.geste.suppr': 'Delete the selected conversation',
  'raccourci.geste.slash': 'Go to search',
  'raccourci.geste.echap': 'Close the overlay, leave the field, return to the inbox',

  // --- Thèmes Clarity (fiches du dialogue Réglages) ---------------------
  // A42 « Wada élargi » : 28 fiches, miroir de la référence française.
  'theme.nature.nom': 'Nature',
  'theme.nature.desc': 'Pine green on ivory, the reference direction.',
  'theme.hortensia.nom': 'Hydrangea',
  'theme.hortensia.desc': 'Composed hydrangea blue, pale bluish grounds.',
  'theme.coquelicot.nom': 'Poppy',
  'theme.coquelicot.desc': 'Muted poppy red on warm paper.',
  'theme.chaume.nom': 'Thatch',
  'theme.chaume.desc': 'Faded straw gold, dry-roof yellows.',
  'theme.bruyere.nom': 'Heather',
  'theme.bruyere.desc': 'Old heather pink, rosy grays.',
  'theme.source.nom': 'Spring',
  'theme.source.desc': 'Grayed teal, clear cold waters.',
  'theme.bleuet.nom': 'Cornflower',
  'theme.bleuet.desc': 'A frank yet matte cornflower blue.',
  'theme.lavande.nom': 'Lavender',
  'theme.lavande.desc': 'Gray lavender, mauve blues.',
  'theme.rosee.nom': 'Dew',
  'theme.rosee.desc': 'Cold water blue-green, very light.',
  'theme.iris.nom': 'Iris',
  'theme.iris.desc': 'Rosy ivory, iris indigo, almond selection.',
  'theme.moisson.nom': 'Harvest',
  'theme.moisson.desc': 'Ripe straw, slate blue, apricot.',
  'theme.grenade.nom': 'Pomegranate',
  'theme.grenade.desc': 'Rosy sand, deep carmine, sea green.',
  'theme.safran.nom': 'Saffron',
  'theme.safran.desc': 'Off-white, burnt saffron, blue-gray.',
  'theme.estampe.nom': 'Woodblock',
  'theme.estampe.desc': 'Pearl gray, dark vermilion, wash blue.',
  'theme.nature-nuit.nom': 'Nature · night',
  'theme.nature-nuit.desc': 'Dark variant. Same 17 tokens.',
  'theme.hortensia-nuit.nom': 'Hydrangea · night',
  'theme.hortensia-nuit.desc': 'Dark variant. Same 17 tokens.',
  'theme.coquelicot-nuit.nom': 'Poppy · night',
  'theme.coquelicot-nuit.desc': 'Dark variant. Same 17 tokens.',
  'theme.chaume-nuit.nom': 'Thatch · night',
  'theme.chaume-nuit.desc': 'Dark variant. Same 17 tokens.',
  'theme.bruyere-nuit.nom': 'Heather · night',
  'theme.bruyere-nuit.desc': 'Dark variant. Same 17 tokens.',
  'theme.source-nuit.nom': 'Spring · night',
  'theme.source-nuit.desc': 'Dark variant. Same 17 tokens.',
  'theme.bleuet-nuit.nom': 'Cornflower · night',
  'theme.bleuet-nuit.desc': 'Dark variant. Same 17 tokens.',
  'theme.lavande-nuit.nom': 'Lavender · night',
  'theme.lavande-nuit.desc': 'Dark variant. Same 17 tokens.',
  'theme.rosee-nuit.nom': 'Dew · night',
  'theme.rosee-nuit.desc': 'Dark variant. Same 17 tokens.',
  'theme.iris-nuit.nom': 'Iris · night',
  'theme.iris-nuit.desc': 'Dark variant. Same 17 tokens.',
  'theme.moisson-nuit.nom': 'Harvest · night',
  'theme.moisson-nuit.desc': 'Dark variant. Same 17 tokens.',
  'theme.grenade-nuit.nom': 'Pomegranate · night',
  'theme.grenade-nuit.desc': 'Dark variant. Same 17 tokens.',
  'theme.safran-nuit.nom': 'Saffron · night',
  'theme.safran-nuit.desc': 'Dark variant. Same 17 tokens.',
  'theme.estampe-nuit.nom': 'Woodblock · night',
  'theme.estampe-nuit.desc': 'Dark variant. Same 17 tokens.',

  // --- Langues (chaque langue se nomme dans SA langue) ------------------
  'langue.fr': 'Français',
  'langue.en': 'English',

  // --- Dates (quand.js) — transposition de la grammaire du prototype ----
  'quand.mois': [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
  ],
  'quand.jours': [
    'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday',
  ],
  'quand.hier': 'Yesterday',
  'quand.aujourdhui': 'Today',
  'quand.long': '{jour}, {heure}',
  'quand.premier': '1',
  'quand.dansAnnee': '{mois} {jour}',
  'quand.auDela': '{mois} {jour}, {annee}',
};
