// Catalogue français (PLAN-LANGUES, A15) : le français du prototype,
// mot pour mot — ce fichier EST la référence, l'extraction n'a rien
// changé à l'écran. Gabarits `{nom}` ; une barre `|` sépare le
// singulier du pluriel (la règle par langue vit dans texte.svelte.js).
// Les tables de dates (mois, jours) sont des tableaux : quand.js les
// consomme telles quelles.

export const FR = {
  // --- Dossiers canoniques (nav, statut, conversation) ----------------
  'boite.reception': 'Boîte de réception',
  // RETOURS-13 R3 : en mode organisé, la boîte se dit « Réception ».
  'boite.receptionOrganisee': 'Réception',
  // PLAN-MODE-ORGANISE E1 — les vues du mode organisé (noms CE).
  'boite.kiosque': 'Kiosque',
  'boite.registre': 'Registre',
  'boite.portier': 'Portier',
  'boite.envoyes': 'Envoyés',
  'boite.brouillons': 'Brouillons',
  'boite.indesirables': 'Indésirables',
  'boite.archives': 'Archives',
  'boite.corbeille': 'Corbeille',
  'nav.toutes': 'Toutes les boîtes',
  'nav.boites': 'Boîtes',
  'nav.aria': 'Dossiers et comptes',

  // --- Entête de l'écran 02 -------------------------------------------
  'entete.recherche': 'Recherche',
  'entete.chercher': 'Chercher un message, une personne, un fichier',
  'entete.effacerRecherche': 'Effacer la recherche',
  'entete.ecrire': 'Écrire',
  'entete.organise': 'Organisé',
  'action.deplacerVers': 'Déplacer vers…',
  'toast.expediteurDeplace': 'Expéditeur déplacé vers {boite} : ses messages suivent.',
  'erreur.sansAdresse': "Ce message n'a pas d'adresse d'expéditeur.",

  // --- Le Portier (PLAN-MODE-ORGANISE E2 ; sous-titre en trois
  // phrases, RETOURS-13 R4, textes CE — D1 : traits d'union posés).
  'portier.sousTitre1': 'Ces expéditeurs vous écrivent pour la première fois.',
  'portier.sousTitre2': 'Les autorisez-vous à vous contacter ?',
  'portier.sousTitre3': 'Les expéditeurs ne seront jamais informés de votre décision.',
  'portier.question': 'Voulez-vous recevoir leurs messages ?',
  'portier.oui': 'Oui',
  'portier.non': 'Non',
  'portier.ouiChoix': 'Oui, en choisissant la destination',
  'portier.nonChoix': 'Non, en choisissant la règle',
  'portier.ouiVers': 'Oui, et ses messages vont vers…',
  'portier.nonSeront': 'Non, et ses messages seront…',
  'portier.versReception': 'La Réception',
  'portier.versKiosque': 'Le Kiosque',
  'portier.versRegistre': 'Le Registre',
  'portier.laReception': 'la Réception',
  'portier.leKiosque': 'le Kiosque',
  'portier.leRegistre': 'le Registre',
  'portier.regleSpam': 'Signalés indésirables',
  'portier.regleArchive': 'Archivés automatiquement',
  // Terrain RETOURS-13 (C3) : le mot CE — rien n'est « supprimé »,
  // c'est la corbeille du serveur (D4).
  'portier.regleCorbeille': 'Déplacés automatiquement dans la corbeille',
  // RETOURS-13 R9 : le quatrième choix du Non — le comportement 0.14.0.
  'portier.regleEcarte': 'Écartés sans déplacer',
  'portier.vide':
    "Personne n'attend au Portier. Les nouveaux expéditeurs apparaîtront ici.",
  'portier.historique': 'Historique du Portier',
  // RETOURS-13 R6 : le texte CE — la note de confidentialité vit
  // désormais au sous-titre (R4).
  'portier.historiqueVide':
    "Vous n'avez écarté aucun expéditeur pour le moment.",
  'portier.reintegrer': 'Réintégrer',
  // RETOURS-14 R4 (D5) : le signe du fil mêlé.
  'fil.attentePortier': 'En attente au Portier',
  'portier.ecarte': 'écarté',
  'portier.ecarteSpam': 'écarté (signalé indésirable)',
  'portier.ecarteArchive': 'écarté (archivage automatique)',
  'portier.ecarteCorbeille': 'écarté (suppression automatique)',
  'toast.portierOuiNu': '{qui} peut vous écrire : ses messages arrivent en Réception.',
  'toast.portierOuiVers': '{qui} peut vous écrire : ses messages vont vers {boite}.',
  'toast.portierNonNu': "{qui} est écarté ; il n'en saura rien.",
  'toast.portierNonSpam':
    '{qui} est écarté ; ses prochains messages partiront aux Indésirables.',
  'toast.portierNonArchive':
    "{qui} est écarté ; ses prochains messages s'archiveront automatiquement.",
  'toast.portierNonCorbeille':
    '{qui} est écarté ; ses prochains messages iront à la Corbeille.',
  // E4 — la Réception organisée : sections et gestes par rangée.
  // RETOURS-14 R6 : le rang d'un groupe du Registre compte des FILS.
  'registre.fil': '{n} conversation',
  'registre.fils': '{n} conversations',
  'registre.voirPlus': 'Voir plus',
  // RETOURS-14 R9 : le bouton de tri des sections (cycle à 4 états).
  'tri.dateDesc': "Plus récents d'abord",
  'tri.dateAsc': "Plus anciens d'abord",
  'tri.alphaAZ': 'Expéditeur A → Z',
  'tri.alphaZA': 'Expéditeur Z → A',
  'tri.aria': 'Changer le tri de la section',
  'liste.sectionNouveau': 'Nouveau pour vous · {n}',
  'liste.sectionConsulte': 'Déjà consulté',
  'liste.gestes': 'Gestes sur ce message',
  'liste.deplacerVers': 'Déplacer vers {boite}',
  'liste.ecarter': 'Écarter cet expéditeur',
  // E5 — Mis de côté : la pile, l'éventail, le tableau (textes du
  // prototype).
  'pile.misDeCote': 'Mis de côté',
  'pile.mettre': 'Mettre de côté',
  'pile.reprendre': 'Reprendre',
  'pile.voirTableau': 'Voir le tableau',
  'pile.ouvrir': 'Ouvrir',
  'pile.tableauTitre': 'Le tableau des mis de côté',
  'pile.tableauNote':
    "Tout ce que vous avez mis de côté, en aperçu sur un seul écran. « Terminé » renvoie le message d'où il vient.",
  'pile.tableauVide': 'La pile est vide.',
  'pile.aria': 'Messages mis de côté',
  'toast.misDeCote': 'Mis de côté : la pile vit en bas à droite de la Réception.',
  'toast.reprisPile': 'Repris de la pile.',
  // E5bis — le Kiosque en cartes ; entête et sections RETOURS-13
  // R10/R11 (textes CE mot pour mot).
  'kiosque.sousTitre1': "Tous vos emails d'information sont regroupés ici.",
  'kiosque.sousTitre2': 'Il vous suffit de les faire défiler pour les lire.',
  'kiosque.sectionNonLus': 'Non lus',
  'kiosque.sectionLus': 'Lus précédemment',
  // Terrain C5 (texte CE, accord posé comme en D1).
  'kiosque.toutLu':
    'Vous avez lu toutes les nouvelles actualités de votre Kiosque.',
  'kiosque.vide':
    "Rien au Kiosque. Depuis un message, « Déplacer vers le Kiosque » y envoie les lettres d'information de cet expéditeur.",
  'toast.portierReintegre':
    '{qui} est réintégré ; ses messages des 90 derniers jours réapparaissent au Portier.',
  // RETOURS-13 R9 : la section Portier des Réglages — les défauts des
  // deux boutons du guichet.
  'groupe.portier': 'Portier',
  'reglages.portierDesc':
    'Les actions par défaut des boutons du Portier. Le mini ⋯ de chaque bouton permet toujours un autre choix, au cas par cas.',
  'reglages.portierOui': 'Le bouton « Oui »',
  'reglages.portierOuiDesc': "Où vont les messages d'un expéditeur autorisé.",
  'reglages.portierNon': 'Le bouton « Non »',
  'reglages.portierNonDesc':
    "Ce que deviennent les prochains messages d'un expéditeur écarté.",
  // RETOURS-14 R5 (D6) : la liste exhaustive des décisions.
  'reglages.portierDecisions': 'Décisions par expéditeur',
  'reglages.portierDecisionsDesc':
    'Toutes les décisions prises au Portier, par ordre alphabétique. Réintégrer un expéditeur le représentera au Portier à son prochain message.',
  'reglages.portierModifier': 'Modifier',
  'reglages.renvoyerPortier': 'Renvoyer au portier',
  'reglages.portierRecherche': 'Rechercher un expéditeur',
  'reglages.portierAucuneDecision': 'Aucune décision pour le moment.',
  'reglages.portierAucunResultat': 'Aucun expéditeur ne correspond.',
  'entete.reglages': 'Réglages',
  // Le retour bêta (RETOURS-11 R3) : le mot du CE, tel quel.
  'entete.feedback': 'Feedback',
  'retour.titre': 'Feedback',
  // Texte arrêté par le CE au terrain du 2026-08-28, mot pour mot.
  'retour.sous':
    'Dites-nous ce qui cloche ou ce qui manque dans ce formulaire. Lorsque vous cliquez sur Envoyer, il nous transmet votre retour par email à feedback-wind@fcts.io. Nous lisons tous les retours, ils nous sont très précieux !',
  'retour.placeholder': 'Votre retour…',
  'retour.merci': 'Merci pour votre retour !',

  // --- Barre de statut --------------------------------------------------
  'statut.recherche': 'Recherche · {n} résultat|Recherche · {n} résultats',
  'statut.recherchePlafond': 'Recherche · {n} sur {total} résultat|Recherche · {n} sur {total} résultats',
  'statut.categorie': '{boite} · {n} élément|{boite} · {n} éléments',
  'statut.synchro': 'Synchronisation · {p} %',
  'statut.rattrapageCorps': 'Rattrapage des messages · {n} restants · {p} %',
  'statut.rattrapageCorpsSeul': 'Rattrapage des messages · {n} restants',
  'statut.rattrapageApercus': 'Rattrapage des aperçus…',
  'statut.envois': "Boîte d'envoi · {n} envoi en attente|Boîte d'envoi · {n} envois en attente",
  'statut.programmes':
    "Boîte d'envoi · {n} envoi programmé · départ {quand}|Boîte d'envoi · {n} envois programmés · prochain départ {quand}",
  'statut.synchroImpossible': 'Synchronisation impossible · nouvelle tentative automatique',
  'statut.synchroImpossibleDepuis':
    'Synchronisation impossible · nouvelle tentative automatique · dernière synchronisation {depuis}',
  'statut.ajour': 'Tous les messages sont à jour',
  'statut.ajourDepuis': 'Tous les messages sont à jour · dernière synchronisation {depuis}',
  'statut.horsLigne': 'Hors ligne',
  'statut.horsLigneDepuis': 'Hors ligne · dernière synchronisation {depuis}',
  'statut.cyclePrefixe': 'Synchronisation',
  'statut.synchroPartielle':
    '{n} compte sur {m} injoignable · nouvelle tentative automatique|{n} comptes sur {m} injoignables · nouvelle tentative automatique',
  'statut.pourcent': '{p} %',
  'statut.phase.inventaire': 'inventaire des dossiers',
  'statut.phase.fils': 'fils de discussion',
  'statut.phase.brouillons': 'brouillons',
  'depuis.instant': "à l'instant",
  'depuis.minutes': 'il y a {n} minute|il y a {n} minutes',
  'depuis.heures': 'il y a {n} heure|il y a {n} heures',
  'depuis.jours': 'il y a {n} jour|il y a {n} jours',
  'statut.demarrage': 'démarrage…',
  'statut.perf': '{total} conversations · première page servie+rendue en {ms} ms',

  // --- Fente d'avis -----------------------------------------------------
  'avis.envoiRefuse': "L'envoi « {sujet} » a été refusé{erreur}.",
  'avis.envoiInterrompu': "L'envoi « {sujet} » a été interrompu{erreur}.",
  'avis.maj': 'Une mise à jour est disponible (version {version}).',
  'avis.crash': "Wind a rencontré un problème lors d'une session précédente ({n} rapport(s) en attente). Rien n'est envoyé sans vous.",
  'avis.telemetrie': "Aider à améliorer Wind ? En cas de plantage, un rapport technique serait enregistré sur votre machine, jamais le contenu de vos mails. Vous choisissez ensuite de l'envoyer.",
  'avis.connexion': 'Compte non reconnecté : {details}',
  'avis.programme': '« {sujet} » partira {quand}, si Wind est ouvert à ce moment-là.',
  'avis.actionsRefusees': "{n} action refusée par le serveur (dossier introuvable ou refus) : le message est resté où il était.|{n} actions refusées par le serveur (dossier introuvable ou refus) : les messages sont restés où ils étaient.",

  // --- Actions partagées ------------------------------------------------
  'action.renvoyer': 'Renvoyer',
  'action.abandonner': 'Abandonner',
  'action.installer': 'Installer',
  'action.plusTard': 'Plus tard',
  'action.ouvrirRapports': 'Ouvrir le dossier des rapports',
  'action.ignorer': 'Ignorer',
  'action.activer': 'Activer',
  'action.nonMerci': 'Non merci',
  'action.reprendre': 'Reprendre',
  'action.reessayer': 'Réessayer',
  'action.synchroniser': 'Synchroniser',
  'action.synchronisation': 'Synchronisation…',
  'action.repondre': 'Répondre',
  'action.repondreTous': 'Répondre à tous',
  'action.transferer': 'Transférer',
  'action.archiver': 'Archiver',
  'action.supprimer': 'Supprimer',
  'action.signalerSpam': 'Signaler comme spam',
  'action.pasSpam': 'Ce n’est pas un spam',
  'action.epingler': 'Épingler',
  'action.desepingler': 'Désépingler',
  'action.envoyer': 'Envoyer',
  'action.annuler': 'Annuler',
  'action.continuer': 'Continuer',
  'action.fermer': 'Fermer',
  'action.replier': 'Replier',
  'action.deplier': 'Déplier',
  'action.retirer': 'Retirer',
  'action.termine': 'Terminé',
  'action.annulerEnvoi': "Annuler l'envoi",
  'action.enregistrer': 'Enregistrer',
  'action.effacer': 'Effacer',
  'action.accepter': 'Accepter',
  'action.provisoire': 'Provisoire',
  'action.refuser': 'Refuser',
  // PLAN-RETOURS-10 R1 : la barre de sélection multiple.
  'action.marquerLu': 'Marquer lu',
  'action.marquerNonLu': 'Marquer non lu',
  'action.annulerSelection': 'Annuler la sélection',

  // --- Carte d'invitation (PLAN-INVITATIONS) ----------------------------
  'inv.kicker': 'Invitation',
  'inv.kickerAnnulee': 'Invitation annulée',
  'inv.kickerReponse': 'Réponse à votre invitation',
  'inv.sansReponse': 'Vous n’avez pas répondu',
  'inv.vous_accepte': 'Vous avez accepté',
  'inv.vous_provisoire': 'Vous avez répondu provisoirement',
  'inv.vous_refuse': 'Vous avez refusé',
  'inv.repondant_accepte': '{qui} a accepté',
  'inv.repondant_provisoire': '{qui} a répondu provisoirement',
  'inv.repondant_refuse': '{qui} a refusé',
  'inv.repondant_sans_reponse': '{qui} a répondu',
  'inv.annuleeTexte': 'La réunion a été annulée par l’organisateur.',
  'inv.lieuOrganisateur': '{lieu} · organisé par {qui}',
  'inv.organisePar': 'Organisé par {qui}',
  'inv.seRepete': 'se répète',
  'inv.heureLocale': 'heure locale de l’organisateur',
  'inv.sujet_accepte': 'Accepté : {titre}',
  'inv.sujet_provisoire': 'Provisoire : {titre}',
  'inv.sujet_refuse': 'Refusé : {titre}',
  'inv.puce_accepte': 'Acceptée',
  'inv.puce_provisoire': 'Provisoire',
  'inv.puce_refuse': 'Refusée',
  'inv.puce_annulee': 'Annulée',

  // --- Toasts -----------------------------------------------------------
  'toast.compteAjoute': 'Compte ajouté.',
  'toast.compteRetire': 'Compte retiré.',
  'toast.archivee': 'Conversation archivée.',
  'toast.supprimee': 'Conversation supprimée.',
  'toast.messageSupprime': 'Message supprimé.',
  'toast.spamSignale': 'Message signalé comme indésirable.',
  'toast.pasSpam': 'Message remis en réception.',
  // PLAN-RETOURS-10 R1 : les gestes de masse — UN toast par lot.
  'toast.groupeArchivees': 'Conversation archivée.|{n} conversations archivées.',
  'toast.groupeSupprimees': 'Message supprimé.|{n} messages supprimés.',
  'toast.groupeSpam': 'Conversation signalée indésirable.|{n} conversations signalées indésirables.',
  'toast.groupePasSpam': 'Conversation remise en réception.|{n} conversations remises en réception.',
  'toast.groupeLues': 'Conversation marquée lue.|{n} conversations marquées lues.',
  'toast.groupeNonLues': 'Conversation marquée non lue.|{n} conversations marquées non lues.',
  'erreur.groupePartiel': '{faits} sur {total} ; le reste a échoué.',
  'toast.pieceEnregistree': 'Pièce enregistrée : {chemin}',
  'toast.brouillonEnregistre': 'Brouillon enregistré.',
  'toast.brouillonSupprime': 'Brouillon supprimé.',
  'toast.brouillonFork': 'Ce brouillon avait changé ailleurs ; votre version a été conservée à part.',
  'toast.envoye': 'Message envoyé.',
  'toast.programme': 'Envoi programmé : départ {quand}.',
  'toast.envoiAnnule': 'Envoi annulé : le message est revenu dans vos brouillons.',
  'toast.signature': 'Signature enregistrée.',
  'toast.signatureTous': 'Signature et choix appliqués à tous les comptes.',
  'toast.echoAttente': 'Copie en cours de synchronisation : réessayez dans un instant.',

  // --- Enveloppes d'erreur (le détail du cœur reste verbatim, L-3) -----
  'erreur.spamImpossible': 'Ce compte n’a pas de dossier indésirable.',
  'erreur.renvoi': 'Renvoi impossible : {err}',
  'erreur.abandon': 'Abandon impossible : {err}',
  'erreur.maj': 'Mise à jour impossible : {err}',
  'erreur.ouverture': 'Ouverture impossible : {err}',
  'erreur.preference': 'Préférence non enregistrée : {err}',
  'erreur.enregistrement': 'Enregistrement impossible : {err}',
  'erreur.transfert': 'Transfert impossible : {err}',
  'erreur.repondreTous': 'Répondre à tous impossible : {err}',
  'erreur.envoi': 'Envoi impossible : {err}',
  'erreur.invitation': 'La réponse n’est pas partie : {err}',
  'erreur.piece': 'Pièce jointe impossible : {err}',
  'erreur.piecesManquantes':
    "Des pièces du transfert manquent encore : attendez le rapatriement, réessayez, ou retirez-les avant d'envoyer.",
  'erreur.aucunCompte': 'Aucun compte émetteur : ajoutez un compte.',
  'erreur.connexion': 'Connexion impossible : {err}',
  'erreur.differePasse': 'Choisissez une date à venir.',
  'erreur.annulerEnvoi': 'Annulation impossible : {err}',
  'erreur.annulerTard': "Trop tard : l'envoi est déjà parti.",
  'erreur.signature': 'Signature non enregistrée : {err}',

  // --- Liste ------------------------------------------------------------
  'liste.aria': 'Liste des messages',
  'liste.aucunResultat': 'Aucun résultat.',
  'liste.vide': 'Aucun message ici.',
  'liste.chargerPlus': 'Afficher le résultat suivant|Afficher les {n} résultats suivants',
  'liste.affiner': 'Affinez votre recherche (from:, to:, date:) pour aller plus loin.',
  'liste.prefixeBrouillon': 'Brouillon : ',
  'liste.dest': 'À : {a}',
  // A80 : la préposition du bloc de boîte — « Camille Roux sur Travail ».
  // L'ordre des mots est figé par le dessin (nom, bloc, heure) : une
  // langue qui demanderait un autre ordre exigerait un gabarit, pas une
  // clé (limite dite au PLAN-REPERE-LIGNE §4.6).
  'liste.sur': 'sur',
  // PLAN-RETOURS-10 R1 : la sélection multiple.
  'liste.nSelection': '{n} sélectionné|{n} sélectionnés',
  'liste.cocher': 'Sélectionner la conversation',
  'brouillons.a': 'À : {a}',
  'brouillons.sansDestinataire': '(sans destinataire)',
  'brouillons.sansObjet': '(sans objet)',
  'puce.messages': '{n} message|{n} messages',
  'puce.fichiers': '{n} fichier|{n} fichiers',
  'puce.epingle': 'Épinglé',
  'onglet.tous': 'Tous',
  'onglet.nonlus': 'Non lus',

  // --- Volet de lecture -------------------------------------------------
  'lecture.aria': 'Message',
  'lecture.vide': 'Sélectionnez un message pour le lire.',
  'lecture.ouvrir': 'Ouvrir',
  'lecture.imagesBloquees': '{n} image distante bloquée pour protéger votre vie privée.|{n} images distantes bloquées pour protéger votre vie privée.',
  'lecture.afficherImages': 'Afficher les images',
  'lecture.toujoursAfficherImages': 'Toujours afficher les images de cet expéditeur',
  'lecture.corps': 'Contenu du message',
  'lecture.enregistrer': 'Enregistrer…',
  'lecture.voileEnregistrer': 'Enregistrer',

  // --- Conversation (écran 03) ------------------------------------------
  'conv.deplier': 'Tout déplier',
  'conv.replier': 'Tout replier',
  'conv.brouillon': 'Brouillon',
  'conv.ligneA': 'À : {liste}',
  'conv.ligneCc': 'Cc : {liste}',
  'conv.de': 'De',
  'conv.a': 'À',
  'conv.objet': 'Objet',
  'conv.fichiersJoints': 'Fichiers joints',

  // --- Composition ------------------------------------------------------
  // Reconnexion d'un compte au jeton mort (constat terrain 2026-08-20).
  'reglages.deconnecte': 'Déconnecté',
  'reglages.reconnecter': 'Reconnecter',
  'reglages.reconnecterCompte': 'Reconnecter {email}',
  'reglages.reconnexionEnCours': 'Consentement en cours…',
  'reglages.reconnexionImpossible': 'Reconnexion impossible : {err}',
  'reglages.repereCompte': 'Repère de {email}',
  'reglages.repereTitre': 'Icône et couleur du compte',
  'reglages.repereIcones': 'Icône du repère',
  'reglages.repereTeintes': 'Couleur du repère',
  'reglages.repereRetirer': 'Retirer le repère',
  'reglages.repereImpossible': 'Repère non enregistré : {err}',
  // PLAN-RETOURS-9 : le retrait se dit (D2), le nom personnalisé (D3).
  'reglages.retirer': 'Retirer le compte',
  'reglages.nommerCompte': 'Nommer {email}',
  'reglages.nomTitre': 'Nom du compte',
  'reglages.nomImpossible': 'Nom non enregistré : {err}',
  'repere.icone.home': 'Maison',
  'repere.icone.work': 'Travail',
  'repere.icone.school': 'Études',
  'repere.icone.star': 'Étoile',
  'repere.icone.favorite': 'Cœur',
  'repere.icone.flight': 'Voyage',
  'repere.icone.shopping_bag': 'Achats',
  'repere.icone.account_balance': 'Banque',
  'repere.icone.sports_esports': 'Jeux',
  'repere.icone.eco': 'Nature',
  'repere.icone.pets': 'Animaux',
  'repere.icone.music_note': 'Musique',
  'repere.teinte.rouge': 'Rouge',
  'repere.teinte.orange': 'Orange',
  'repere.teinte.ocre': 'Ocre',
  'repere.teinte.olive': 'Olive',
  'repere.teinte.vert': 'Vert',
  'repere.teinte.sapin': 'Sapin',
  'repere.teinte.bleu': 'Bleu',
  'repere.teinte.indigo': 'Indigo',
  'repere.teinte.violet': 'Violet',
  'repere.teinte.magenta': 'Magenta',
  'repere.teinte.rose': 'Rose',
  'repere.teinte.brun': 'Brun',

  'compo.nouveau': 'Nouveau message',
  'compo.re': 'Re : {sujet}',
  'compo.tr': 'Tr : {sujet}',
  'compo.bonjour': 'Bonjour {prenom},',
  'compo.sansObjet': 'sans objet',
  'compo.compteEmetteur': 'Compte émetteur',
  'compo.destinataire': 'Destinataire',
  'compo.suggestions': 'Adresses suggérées',
  'compo.objetPlaceholder': 'Objet du message',
  'compo.corpsPlaceholder': 'Votre message…',
  'compo.cc': 'Cc',
  'compo.cci': 'Cci',
  // Barre de mise en forme réelle (PLAN-COMPOSITION-HTML, R4). Lien et
  // Citation RETIRÉS (décision CE D1 : périmètre strict).
  'compo.police': 'Police',
  'compo.policeSans': 'Sans serif',
  'compo.policeSerif': 'Serif',
  'compo.policeMono': 'Monospace',
  'compo.taille': 'Taille',
  'compo.taillePetit': 'Petit',
  'compo.tailleNormal': 'Normal',
  'compo.tailleGrand': 'Grand',
  'compo.tailleTresGrand': 'Très grand',
  'compo.gras': 'Gras',
  'compo.italique': 'Italique',
  'compo.souligne': 'Souligné',
  'compo.barre': 'Barré',
  'compo.couleur': 'Couleur du texte',
  'compo.alignerGauche': 'Aligner à gauche',
  'compo.alignerCentre': 'Centrer',
  'compo.alignerDroite': 'Aligner à droite',
  'compo.listePuces': 'Liste à puces',
  'compo.listeNumerotee': 'Liste numérotée',
  'compo.retraitMoins': 'Diminuer le retrait',
  'compo.retraitPlus': 'Augmenter le retrait',
  'compo.effacerFormat': 'Effacer la mise en forme',
  'compo.joindre': 'Joindre',
  'compo.retirerPiece': 'Retirer {nom}',
  'compo.rapatriement': '{nom} · rapatriement…',
  'compo.poidsTotal': '{poids} / 25 Mo',
  'compo.pieceRefusee': '« {nom} » dépasse la place restante ({reste}).',
  'compo.enregistrerBrouillon': 'Enregistrer le brouillon',
  'compo.supprimerBrouillon': 'Supprimer le brouillon',
  'compo.supprConfirme': 'Supprimer ce brouillon ? C’est définitif.',
  // R3 (PLAN-RETOURS-6) : le marquage « important » de l'envoi —
  // bouton-icône de la barre de mise en forme, l'infobulle dit le geste.
  'compo.importantTitre': 'Marquer le message comme important',
  // R2 : l'envoi différé — la carte au-dessus du pied.
  'compo.plusTard': 'Envoyer plus tard',
  'compo.differeQuand': 'Départ',
  'compo.differeNote': 'Le message partira à cette heure si Wind est ouvert, sinon au prochain lancement.',
  'compo.programmer': 'Programmer',

  // --- Écran 01 et guichet de compte ------------------------------------
  'accueil.bienvenue': 'Bienvenue dans',
  'accueil.etape': 'Étape {n}/{total}',
  'accueil.ajouterSous': 'Pour commencer, ajoutez une adresse email.',
  'accueil.ajouter': 'Ajouter',
  'accueil.ajouterAutre': 'Ajouter une autre adresse email',
  'accueil.retour': 'Retour',
  'accueil.continuer': 'Continuer',
  'accueil.terminer': 'Terminer',
  'accueil.voletsTitre': 'Choisissez votre disposition de fenêtre',
  'accueil.voletsSous': 'Vous pourrez la changer plus tard dans Réglages > Affichage.',
  'accueil.themeTitre': 'Choisissez votre thème',
  'accueil.themeSous': 'Vous pourrez le changer plus tard dans Réglages > Thèmes.',
  'accueil.betaTitre': 'Wind est en bêta',
  // Textes arrêtés par le CE au terrain du 2026-08-28 ; le texte du
  // bouton est LE MÊME que celui de la fenêtre de feedback (retour.sous).
  'accueil.betaSous':
    'Vous utilisez une version Bêta de Wind. Certaines fonctionnalités peuvent évoluer, mais toutes doivent fonctionner sans problème.',
  'accueil.betaBouton':
    'Dites-nous ce qui cloche ou ce qui manque dans ce formulaire. Lorsque vous cliquez sur Envoyer, il nous transmet votre retour par email à feedback-wind@fcts.io. Nous lisons tous les retours, ils nous sont très précieux !',
  'accueil.finTitre': 'Tout est prêt.',
  'accueil.finTexte': 'Vérifiez vos choix avant de continuer.',
  'accueil.revenir': 'Revenir à cette étape',
  'accueil.theme': 'Thème',
  'guichet.adresse': 'Adresse e-mail',
  'guichet.mdp': 'Mot de passe',
  'guichet.imap': 'Serveur IMAP',
  'guichet.smtp': 'Serveur SMTP',
  'guichet.port': 'Port',
  'guichet.adresseInvalide': 'Saisissez votre adresse e-mail complète.',
  'guichet.autorisation': 'Autorisation en cours dans votre navigateur…',
  'guichet.verification': 'Vérification de la connexion au serveur…',
  'guichet.noteGenerique': 'Renseignez les serveurs de votre fournisseur. Le mot de passe rejoint le coffre du système, jamais un fichier.',
  'guichet.horizon': "Historique à importer pour la recherche",
  'horizon.1m': '1 mois',
  'horizon.2m': '2 mois',
  'horizon.3m': '3 mois',
  'horizon.6m': '6 mois',
  'horizon.1a': '1 an',
  'horizon.2a': '2 ans',
  'horizon.5a': '5 ans',
  'horizon.tout': 'Tout depuis le début',
  'boite.nettoyage': 'Nettoyage de printemps',
  'nettoyage.sousTitre':
    'En lançant un nettoyage de printemps, vous allez pouvoir trier vos archives sur la durée de votre choix en choisissant, pour chaque expéditeur, comment vous souhaitez que ses messages soient traités.',
  'nettoyage.plage': 'Période à nettoyer',
  'nettoyage.perimetre': 'Boîtes à nettoyer',
  'nettoyage.perimetre.reception': 'Réception seule',
  'nettoyage.perimetre.dossiers': 'Réception + Dossiers',
  'nettoyage.perimetre.dossiersArchives': 'Réception + Dossiers + Archives',
  'nettoyage.perimetre.archives': 'Réception + Archives',
  'nettoyage.demarrer': 'Démarrer le nettoyage',
  'nettoyage.progression': '{p} % traités',
  'nettoyage.progressionAria': 'Progression du nettoyage',
  'nettoyage.message': '{n} message',
  'nettoyage.messages': '{n} messages',
  'nettoyage.fini': 'Tous les expéditeurs de la période choisie ont été traités.',
  'nettoyage.terminer': 'Terminer le nettoyage',
  'reglages.horizonCompte': 'Historique importé pour {email}',
  'reglages.horizonTitre': 'Historique importé pour la recherche',
  'reglages.horizonNote':
    "Étendre la durée rapatrie les messages plus anciens à la prochaine relève. Réduire n'efface rien de ce qui est déjà sur cet ordinateur.",
  'reglages.horizonImpossible': "Impossible d'enregistrer ce choix ({err}).",

  // --- Modale de migration ----------------------------------------------
  'migration.aria': 'Mise à jour de la base de messages',
  'migration.titre': 'Mise à jour de votre boîte.',
  'migration.note': 'Environ {n} messages sont mis à jour. Cette mise à jour ne se fait qu’une fois et n’efface rien.',
  'migration.preparation': 'Préparation…',
  'migration.pourcent': '{p} %',
  'migration.annulee': 'Mise à jour annulée, tout est revenu comme avant. Elle reprendra au prochain lancement, ou tout de suite :',
  'migration.echec': 'La mise à jour a échoué ({err}). Rien n’est perdu : elle peut être relancée.',

  // --- Réglages ---------------------------------------------------------
  'reglages.groupesAria': 'Groupes de réglages',
  'groupe.comptes': 'Comptes',
  'groupe.themes': 'Thèmes',
  'groupe.affichage': 'Affichage',
  'groupe.notifications': 'Notifications',
  'groupe.signature': 'Signature',
  'groupe.raccourcis': 'Raccourcis',
  'groupe.apropos': 'À propos',
  'reglages.sectionThemes': 'Thème de couleur',
  'reglages.sectionRaccourcis': 'Raccourcis clavier',
  'reglages.ajouterCompte': 'Ajouter un compte',
  // Le texte visible du bouton (« Retirer le compte ») vit DANS son nom
  // accessible — WCAG 2.5.3, revue 2026-08-23.
  'reglages.retirerCompte': 'Retirer le compte {email}',
  'reglages.retirerConfirme': 'Retirer {email} ? Son courrier local est effacé et sa connexion oubliée. Rien n’est supprimé sur le serveur.',
  'reglages.retraitEnCours': 'Retrait…',
  'reglages.retraitImpossible': 'Retrait impossible : {err}',
  'reglages.sombreAuto': 'Sombre automatique',
  'reglages.sombreAutoDesc': "Suivre le réglage sombre du système : la déclinaison nuit du thème choisi s'affiche quand il est actif, la claire revient dès qu'il s'éteint. Un thème nuit choisi à la main reste tel quel.",
  'reglages.langue': 'Langue',
  'reglages.langueDesc': "La langue de l'interface, appliquée immédiatement.",
  'reglages.volets': 'Disposition',
  'reglages.voletsDesc':
    "Le nombre de volets de l'écran principal. En dessous de trois, la lecture s'ouvre en plein écran ; en un volet, la navigation vit dans un tiroir.",
  'volets.3': 'Trois volets',
  'volets.2': 'Deux volets',
  'volets.1': 'Un volet',
  'reglages.espacement': 'Espacement des messages',
  'reglages.espacementDesc':
    "L'air entre deux messages dans la liste. Plus il est grand, plus la liste respire, et moins elle montre de messages à la fois.",
  'espacement.faible': 'Faible',
  'espacement.moyen': 'Moyen',
  'espacement.eleve': 'Élevé',
  'reglages.imagesExpediteurs': 'Images distantes',
  'reglages.imagesExpediteursDesc':
    "Les images des messages de ces expéditeurs s'affichent toujours, sans demande.",
  'reglages.retirerExpediteur': 'Retirer',
  'nav.ouvrirTiroir': 'Ouvrir la navigation',
  'nav.fermerTiroir': 'Fermer la navigation',
  'volets.poigneeNav': 'Régler la largeur de la navigation',
  'volets.poigneeListe': 'Régler la largeur de la liste',
  'reglages.bulles': "Bulles d'arrivée",
  'reglages.bullesDesc': "Une bulle système annonce les nouveaux messages à la synchronisation. La couper n'arrête jamais la synchronisation elle-même.",
  'reglages.noteRaccourcis': 'Dans un champ de saisie, les lettres redeviennent des lettres ; seul Échap garde un sens.',
  'reglages.version': 'Version',
  'reglages.maj': 'Mises à jour',
  'reglages.verifierMaj': 'Vérifier les mises à jour',
  'reglages.verification': 'Vérification…',
  'reglages.ajour': 'Vous êtes à jour.',
  'reglages.majDisponible': 'Version {version} disponible.',
  'reglages.majImpossible': 'Vérification impossible : {err}',
  'reglages.installation': 'Téléchargement et installation…',
  'reglages.signatureDesc':
    "Une signature par compte, ajoutée au bas des messages que vous composez. La mise en forme du composeur s'applique.",
  'reglages.signaturePlaceholder': 'Votre signature…',
  'reglages.signatureRepliques': 'Aussi dans les réponses et transferts',
  'reglages.signatureRepliquesDesc':
    'Sinon, la signature ne s’ajoute qu’aux nouveaux messages.',
  'reglages.signatureTous': 'Appliquer à tous les comptes',
  'reglages.icones': 'Icônes',
  'reglages.iconesValeur': "Jeu original de Wind, dessiné d'après Material Symbols (Google, Apache 2.0) ; aucun réseau.",
  // D5 (PLAN-RETOURS-11) : le label tel quel, identique dans les deux
  // langues ; sans clé (verdict CE du STOP visuel).
  'reglages.origineValeur': 'Made in EU',

  // --- Raccourcis (table D3, référence) ---------------------------------
  'raccourci.touche.c': 'c',
  'raccourci.touche.r': 'r',
  'raccourci.touche.f': 'f',
  'raccourci.touche.e': 'e',
  'raccourci.touche.suppr': 'Suppr',
  'raccourci.touche.slash': '/',
  'raccourci.touche.echap': 'Échap',
  'raccourci.geste.c': 'Écrire un nouveau message',
  'raccourci.geste.r': 'Répondre à la conversation sélectionnée',
  'raccourci.geste.f': 'Transférer la conversation sélectionnée',
  'raccourci.geste.e': 'Archiver la conversation sélectionnée',
  'raccourci.geste.suppr': 'Supprimer la conversation sélectionnée',
  'raccourci.geste.slash': 'Aller à la recherche',
  'raccourci.geste.echap': 'Fermer la surimpression, sortir du champ, revenir à la boîte',

  // --- Thèmes (fiches du sélecteur : Réglages, accueil) -----------------
  // V7 amendée par A94 : la table des thèmes est courte et vivante
  // (la table Wada de 28 fiches reste retirée) —
  // les clés suivent FICHES (lib/theme.js), la gate de cohérence y
  // veille dans les deux sens.
  'theme.elements.nom': 'Elements',
  'theme.elements.desc': 'Papier clair, teal de la marque : la direction Elements.',
  'theme.elements-nuit.nom': 'Elements · nuit',
  'theme.elements-nuit.desc': 'Déclinaison sombre. Mêmes 17 jetons.',
  'theme.innamoramento.nom': 'Innamoramento',
  'theme.innamoramento.desc': 'Rose profond, tuiles mauves : la direction Innamoramento.',
  'theme.innamoramento-nuit.nom': 'Innamoramento · nuit',
  'theme.innamoramento-nuit.desc': 'Déclinaison sombre. Mêmes 17 jetons.',

  // --- Langues (chaque langue se nomme dans SA langue, les deux
  //     catalogues portent les mêmes valeurs) --------------------------
  'langue.fr': 'Français',
  'langue.en': 'English',

  // --- Dates (quand.js) — formes exactes du prototype -------------------
  'quand.mois': [
    'janv.', 'févr.', 'mars', 'avr.', 'mai', 'juin',
    'juil.', 'août', 'sept.', 'oct.', 'nov.', 'déc.',
  ],
  'quand.jours': [
    'Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi',
  ],
  'quand.hier': 'Hier',
  'quand.aujourdhui': "Aujourd'hui",
  'quand.long': '{jour}, {heure}',
  'quand.premier': '1ᵉʳ',
  'quand.dansAnnee': '{jour} {mois}',
  'quand.auDela': '{jour} {mois} {annee}',
};
