// Catalogue français (PLAN-LANGUES, A15) : le français du prototype,
// mot pour mot — ce fichier EST la référence, l'extraction n'a rien
// changé à l'écran. Gabarits `{nom}` ; une barre `|` sépare le
// singulier du pluriel (la règle par langue vit dans texte.svelte.js).
// Les tables de dates (mois, jours) sont des tableaux : quand.js les
// consomme telles quelles.

export const FR = {
  // --- Dossiers canoniques (nav, statut, conversation) ----------------
  'boite.reception': 'Boîte de réception',
  'boite.envoyes': 'Envoyés',
  'boite.brouillons': 'Brouillons',
  'boite.indesirables': 'Indésirables',
  'boite.archives': 'Archives',
  'boite.corbeille': 'Corbeille',
  'nav.toutes': 'Toutes les boîtes',
  'nav.boites': 'Boîtes',
  'nav.aria': 'Dossiers et comptes',

  // --- Entête de l'écran 02 -------------------------------------------
  'entete.recherche': 'Recherche',
  'entete.chercher': 'Chercher un message, une personne, un fichier',
  'entete.effacerRecherche': 'Effacer la recherche',
  'entete.ecrire': 'Écrire',
  'entete.reglages': 'Réglages',

  // --- Barre de statut --------------------------------------------------
  'statut.recherche': 'Recherche · {n} résultat|Recherche · {n} résultats',
  'statut.categorie': '{boite} · {n} élément|{boite} · {n} éléments',
  'statut.synchro': 'Synchronisation · {p} %',
  'statut.rattrapageCorps': 'Rattrapage des messages · {n} restants',
  'statut.rattrapageApercus': 'Rattrapage des aperçus…',
  'statut.envois': "Boîte d'envoi · {n} envoi en attente|Boîte d'envoi · {n} envois en attente",
  'statut.synchroImpossible': 'Synchronisation impossible — nouvelle tentative automatique',
  'statut.synchroImpossibleDepuis':
    'Synchronisation impossible — nouvelle tentative automatique · dernière synchronisation {depuis}',
  'statut.ajour': 'Tous les messages sont à jour',
  'statut.ajourDepuis': 'Tous les messages sont à jour · dernière synchronisation {depuis}',
  'statut.horsLigne': 'Hors ligne',
  'statut.horsLigneDepuis': 'Hors ligne · dernière synchronisation {depuis}',
  'statut.cyclePrefixe': 'Synchronisation',
  'statut.synchroPartielle':
    '{n} compte sur {m} injoignable — nouvelle tentative automatique|{n} comptes sur {m} injoignables — nouvelle tentative automatique',
  'statut.pourcent': '{p} %',
  'statut.phase.inventaire': 'inventaire des dossiers',
  'statut.phase.fils': 'fils de discussion',
  'statut.phase.brouillons': 'brouillons',
  'depuis.instant': "à l'instant",
  'depuis.minutes': 'il y a {n} minute|il y a {n} minutes',
  'depuis.heures': 'il y a {n} heure|il y a {n} heures',
  'depuis.jours': 'il y a {n} jour|il y a {n} jours',
  'statut.demarrage': 'démarrage…',
  'statut.perf': '{total} conversations — première page servie+rendue en {ms} ms',

  // --- Fente d'avis -----------------------------------------------------
  'avis.envoiRefuse': "L'envoi « {sujet} » a été refusé{erreur}.",
  'avis.envoiInterrompu': "L'envoi « {sujet} » a été interrompu{erreur}.",
  'avis.maj': 'Une mise à jour est disponible (version {version}).',
  'avis.crash': "Wind a rencontré un problème lors d'une session précédente ({n} rapport(s) en attente). Rien n'est envoyé sans vous.",
  'avis.telemetrie': "Aider à améliorer Wind ? En cas de plantage, un rapport technique serait enregistré sur votre machine — jamais le contenu de vos mails. Vous choisissez ensuite de l'envoyer.",
  'avis.connexion': 'Compte non reconnecté — {details}',

  // --- Actions partagées ------------------------------------------------
  'action.renvoyer': 'Renvoyer',
  'action.abandonner': 'Abandonner',
  'action.installer': 'Installer',
  'action.plusTard': 'Plus tard',
  'action.ouvrirRapports': 'Ouvrir le dossier des rapports',
  'action.ignorer': 'Ignorer',
  'action.activer': 'Activer',
  'action.nonMerci': 'Non merci',
  'action.reprendre': 'Reprendre',
  'action.reessayer': 'Réessayer',
  'action.synchroniser': 'Synchroniser',
  'action.synchronisation': 'Synchronisation…',
  'action.repondre': 'Répondre',
  'action.repondreTous': 'Répondre à tous',
  'action.transferer': 'Transférer',
  'action.archiver': 'Archiver',
  'action.supprimer': 'Supprimer',
  'action.envoyer': 'Envoyer',
  'action.annuler': 'Annuler',
  'action.continuer': 'Continuer',
  'action.fermer': 'Fermer',
  'action.replier': 'Replier',
  'action.retirer': 'Retirer',
  'action.termine': 'Terminé',

  // --- Toasts -----------------------------------------------------------
  'toast.compteAjoute': 'Compte ajouté.',
  'toast.compteRetire': 'Compte retiré.',
  'toast.archivee': 'Conversation archivée.',
  'toast.supprimee': 'Conversation supprimée.',
  'toast.pieceEnregistree': 'Pièce enregistrée : {chemin}',
  'toast.brouillonEnregistre': 'Brouillon enregistré.',
  'toast.brouillonFork': 'Ce brouillon avait changé ailleurs — votre version a été conservée à part.',
  'toast.envoye': 'Message envoyé.',

  // --- Enveloppes d'erreur (le détail du cœur reste verbatim, L-3) -----
  'erreur.renvoi': 'Renvoi impossible : {err}',
  'erreur.abandon': 'Abandon impossible : {err}',
  'erreur.maj': 'Mise à jour impossible : {err}',
  'erreur.ouverture': 'Ouverture impossible : {err}',
  'erreur.preference': 'Préférence non enregistrée : {err}',
  'erreur.enregistrement': 'Enregistrement impossible : {err}',
  'erreur.transfert': 'Transfert impossible : {err}',
  'erreur.repondreTous': 'Répondre à tous impossible : {err}',
  'erreur.envoi': 'Envoi impossible : {err}',
  'erreur.piece': 'Pièce jointe impossible : {err}',
  'erreur.piecesManquantes':
    "Des pièces du transfert manquent encore — attendez le rapatriement, réessayez, ou retirez-les avant d'envoyer.",
  'erreur.aucunCompte': 'Aucun compte émetteur — ajoutez un compte.',
  'erreur.connexion': 'Connexion impossible : {err}',

  // --- Liste ------------------------------------------------------------
  'liste.aria': 'Liste des messages',
  'liste.aucunResultat': 'Aucun résultat.',
  'liste.vide': 'Aucun message ici.',
  'liste.prefixeBrouillon': 'Brouillon — ',
  'brouillons.a': 'À : {a}',
  'brouillons.sansDestinataire': '(sans destinataire)',
  'brouillons.sansObjet': '(sans objet)',
  'puce.messages': '{n} message|{n} messages',
  'puce.fichiers': '{n} fichier|{n} fichiers',
  'onglet.tous': 'Tous',
  'onglet.nonlus': 'Non lus',

  // --- Volet de lecture -------------------------------------------------
  'lecture.aria': 'Message',
  'lecture.vide': 'Sélectionnez un message pour le lire.',
  'lecture.dernier': 'Dernier message · {quand}',
  'lecture.voirConversation': 'Voir la conversation',
  'lecture.a': 'à {adresse}',
  'lecture.imagesBloquees': '{n} image distante bloquée pour protéger votre vie privée.|{n} images distantes bloquées pour protéger votre vie privée.',
  'lecture.afficherImages': 'Afficher les images',
  'lecture.corps': 'Contenu du message',
  'lecture.enregistrer': 'Enregistrer dans Téléchargements',

  // --- Conversation (écran 03) ------------------------------------------
  'conv.toutDeplier': 'Tout déplier',
  'conv.brouillon': 'Brouillon',
  'conv.de': 'De',
  'conv.a': 'À',
  'conv.objet': 'Objet',
  'conv.fichiersJoints': 'Fichiers joints',

  // --- Composition ------------------------------------------------------
  'compo.nouveau': 'Nouveau message',
  'compo.re': 'Re : {sujet}',
  'compo.tr': 'Tr : {sujet}',
  'compo.bonjour': 'Bonjour {prenom},',
  'compo.sansObjet': 'sans objet',
  'compo.independante': 'Rendre indépendante',
  'compo.compteEmetteur': 'Compte émetteur',
  'compo.destinataire': 'Destinataire',
  'compo.objetPlaceholder': 'Objet du message',
  'compo.corpsPlaceholder': 'Votre message…',
  'compo.cc': 'Cc',
  'compo.cci': 'Cci',
  'compo.gras': 'G',
  'compo.italique': 'I',
  'compo.souligne': 'S',
  'compo.liste': 'Liste',
  'compo.lien': 'Lien',
  'compo.citation': 'Citation',
  'compo.joindre': 'Joindre',
  'compo.retirerPiece': 'Retirer {nom}',
  'compo.rapatriement': '{nom} — rapatriement…',
  'compo.poidsTotal': '{poids} / 25 Mo',
  'compo.pieceRefusee': '« {nom} » dépasse la place restante ({reste}).',
  'compo.enregistrerBrouillon': 'Enregistrer le brouillon',

  // --- Écran 01 et guichet de compte ------------------------------------
  'onboarding.titre1': 'Votre adresse.',
  'onboarding.titre2': "C'est tout.",
  'guichet.adresse': 'Adresse e-mail',
  'guichet.mdp': 'Mot de passe',
  'guichet.imap': 'Serveur IMAP',
  'guichet.smtp': 'Serveur SMTP',
  'guichet.port': 'Port',
  'guichet.adresseInvalide': 'Saisissez votre adresse e-mail complète.',
  'guichet.autorisation': 'Autorisation en cours dans votre navigateur…',
  'guichet.verification': 'Vérification de la connexion au serveur…',
  'guichet.noteGenerique': 'Renseignez les serveurs de votre fournisseur — le mot de passe rejoint le coffre du système, jamais un fichier.',
  'guichet.noteAuto': "Le serveur est détecté automatiquement. Rien d'autre à régler.",

  // --- Modale de migration ----------------------------------------------
  'migration.aria': 'Mise à jour de la base de messages',
  'migration.titre': 'Vos messages deviennent des conversations.',
  'migration.note': 'Environ {n} messages vont être réorganisés en conversations. Cette mise à jour ne se fait qu’une fois et n’efface rien.',
  'migration.preparation': 'Préparation…',
  'migration.pourcent': '{p} %',
  'migration.annulee': 'Mise à jour annulée — tout est revenu comme avant. Elle reprendra au prochain lancement, ou tout de suite :',
  'migration.echec': 'La mise à jour a échoué ({err}). Rien n’est perdu : elle peut être relancée.',

  // --- Réglages ---------------------------------------------------------
  'reglages.groupesAria': 'Groupes de réglages',
  'groupe.comptes': 'Comptes',
  'groupe.themes': 'Thèmes',
  'groupe.affichage': 'Affichage',
  'groupe.notifications': 'Notifications',
  'groupe.raccourcis': 'Raccourcis',
  'groupe.apropos': 'À propos',
  'reglages.sectionThemes': 'Thème de couleur',
  'reglages.sectionRaccourcis': 'Raccourcis clavier',
  'reglages.ajouterCompte': 'Ajouter un compte',
  'reglages.retirerCompte': 'Retirer {email}',
  'reglages.retirerConfirme': 'Retirer {email} ? Son courrier local est effacé et sa connexion oubliée. Rien n’est supprimé sur le serveur.',
  'reglages.retraitEnCours': 'Retrait…',
  'reglages.retraitImpossible': 'Retrait impossible — {err}',
  'reglages.sombreAuto': 'Sombre automatique',
  'reglages.sombreAutoDesc': "Suivre le réglage sombre du système : « La nuit » s'affiche quand il est actif, le thème choisi revient dès qu'il s'éteint.",
  'reglages.langue': 'Langue',
  'reglages.langueDesc': "La langue de l'interface, appliquée immédiatement.",
  'reglages.bulles': "Bulles d'arrivée",
  'reglages.bullesDesc': "Une bulle système annonce les nouveaux messages à la synchronisation. La couper n'arrête jamais la synchronisation elle-même.",
  'reglages.noteRaccourcis': 'Dans un champ de saisie, les lettres redeviennent des lettres — seul Échap garde un sens.',
  'reglages.version': 'Version',
  'reglages.maj': 'Mises à jour',
  'reglages.verifierMaj': 'Vérifier les mises à jour',
  'reglages.verification': 'Vérification…',
  'reglages.ajour': 'Vous êtes à jour.',
  'reglages.majDisponible': 'Version {version} disponible.',
  'reglages.majImpossible': 'Vérification impossible — {err}',
  'reglages.installation': 'Téléchargement et installation…',
  'reglages.icones': 'Icônes',
  'reglages.iconesValeur': 'Material Symbols Rounded (Google), licence Apache 2.0 — police embarquée, aucun réseau.',

  // --- Raccourcis (table D3, référence) ---------------------------------
  'raccourci.touche.c': 'c',
  'raccourci.touche.r': 'r',
  'raccourci.touche.f': 'f',
  'raccourci.touche.e': 'e',
  'raccourci.touche.suppr': 'Suppr',
  'raccourci.touche.slash': '/',
  'raccourci.touche.echap': 'Échap',
  'raccourci.geste.c': 'Écrire un nouveau message',
  'raccourci.geste.r': 'Répondre à la conversation sélectionnée',
  'raccourci.geste.f': 'Transférer la conversation sélectionnée',
  'raccourci.geste.e': 'Archiver la conversation sélectionnée',
  'raccourci.geste.suppr': 'Supprimer la conversation sélectionnée',
  'raccourci.geste.slash': 'Aller à la recherche',
  'raccourci.geste.echap': 'Fermer la surimpression, sortir du champ, revenir à la boîte',

  // --- Thèmes Clarity (fiches du dialogue Réglages) ---------------------
  'theme.air.nom': "L'air",
  'theme.air.desc': 'Ciels pâles et bleu clair, beaucoup de respiration.',
  'theme.feu.nom': 'Le feu',
  'theme.feu.desc': 'Sables chauds et braise, un accent orangé profond.',
  'theme.eau.nom': "L'eau",
  'theme.eau.desc': "Verts d'eau et sarcelle, fond frais et minéral.",
  'theme.astres.nom': 'Les astres',
  'theme.astres.desc': 'Gris bleutés et indigo, une lumière nocturne claire.',
  'theme.terre.nom': 'La terre',
  'theme.terre.desc': 'Argile, ocre et lin, un accent terracotta.',
  'theme.nature.nom': 'La nature',
  'theme.nature.desc': 'Vert pin sur ivoire — la direction actuelle.',
  'theme.nuit.nom': 'La nuit',
  'theme.nuit.desc': 'Surfaces sombres, encre claire, pin adouci. Thème sombre.',

  // --- Langues (chaque langue se nomme dans SA langue, les deux
  //     catalogues portent les mêmes valeurs) --------------------------
  'langue.fr': 'Français',
  'langue.en': 'English',

  // --- Dates (quand.js) — formes exactes du prototype -------------------
  'quand.mois': [
    'janv.', 'févr.', 'mars', 'avr.', 'mai', 'juin',
    'juil.', 'août', 'sept.', 'oct.', 'nov.', 'déc.',
  ],
  'quand.jours': [
    'Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi',
  ],
  'quand.hier': 'Hier',
  'quand.aujourdhui': "Aujourd'hui",
  'quand.premier': '1ᵉʳ',
  'quand.dansAnnee': '{jour} {mois}',
  'quand.auDela': '{jour} {mois} {annee}',
};
