// Catalogue anglais (PLAN-LANGUES, A15) : transposition de la grammaire
// du prototype, jamais une invention — mêmes clés que catalogue.fr.js,
// l'audit e2e casse au moindre écart. Les guillemets « » deviennent
// “ ”, l'heure reste sur 24 h (on livre une langue, pas une locale).

export const EN = {
  // --- Dossiers canoniques (nav, statut, conversation) ----------------
  'boite.reception': 'Inbox',
  'boite.envoyes': 'Sent',
  'boite.brouillons': 'Drafts',
  'boite.indesirables': 'Junk',
  'boite.archives': 'Archives',
  'boite.corbeille': 'Trash',
  'nav.toutes': 'All inboxes',
  'nav.boites': 'Inboxes',
  'nav.aria': 'Folders and accounts',

  // --- Entête de l'écran 02 -------------------------------------------
  'entete.recherche': 'Search',
  'entete.chercher': 'Search messages, people, files',
  'entete.effacerRecherche': 'Clear search',
  'entete.ecrire': 'Compose',
  'entete.reglages': 'Settings',

  // --- Barre de statut --------------------------------------------------
  'statut.recherche': 'Search · {n} result|Search · {n} results',
  'statut.categorie': '{boite} · {n} item|{boite} · {n} items',
  'statut.synchro': 'Syncing · {p}%',
  'statut.rattrapageCorps': 'Catching up on messages · {n} to go',
  'statut.rattrapageApercus': 'Catching up on previews…',
  'statut.envois': 'Outbox · {n} message waiting|Outbox · {n} messages waiting',
  'statut.synchroImpossible': 'Sync failed — will retry automatically',
  'statut.synchroImpossibleDepuis':
    'Sync failed — will retry automatically · last synced {depuis}',
  'statut.ajour': 'All messages are up to date',
  'statut.ajourDepuis': 'All messages are up to date · last synced {depuis}',
  'statut.horsLigne': 'Offline',
  'statut.horsLigneDepuis': 'Offline · last synced {depuis}',
  'statut.cyclePrefixe': 'Syncing',
  'statut.synchroPartielle':
    '{n} account of {m} unreachable — will retry automatically|{n} accounts of {m} unreachable — will retry automatically',
  'statut.pourcent': '{p}%',
  'statut.phase.inventaire': 'folder inventory',
  'statut.phase.fils': 'conversation threads',
  'statut.phase.brouillons': 'drafts',
  'depuis.instant': 'just now',
  'depuis.minutes': '{n} minute ago|{n} minutes ago',
  'depuis.heures': '{n} hour ago|{n} hours ago',
  'depuis.jours': '{n} day ago|{n} days ago',
  'statut.demarrage': 'starting…',
  'statut.perf': '{total} conversations — first page served+rendered in {ms} ms',

  // --- Fente d'avis -----------------------------------------------------
  'avis.envoiRefuse': 'The message “{sujet}” was rejected{erreur}.',
  'avis.envoiInterrompu': 'The message “{sujet}” was interrupted{erreur}.',
  'avis.maj': 'An update is available (version {version}).',
  'avis.crash': 'Wind ran into a problem during a previous session ({n} report(s) pending). Nothing is sent without you.',
  'avis.telemetrie': 'Help improve Wind? If it crashes, a technical report would be saved on your machine — never the content of your mail. You then choose whether to send it.',
  'avis.connexion': 'Account not reconnected — {details}',

  // --- Actions partagées ------------------------------------------------
  'action.renvoyer': 'Send again',
  'action.abandonner': 'Discard',
  'action.installer': 'Install',
  'action.plusTard': 'Later',
  'action.ouvrirRapports': 'Open the reports folder',
  'action.ignorer': 'Dismiss',
  'action.activer': 'Turn on',
  'action.nonMerci': 'No thanks',
  'action.reprendre': 'Resume',
  'action.reessayer': 'Try again',
  'action.synchroniser': 'Sync',
  'action.synchronisation': 'Syncing…',
  'action.repondre': 'Reply',
  'action.repondreTous': 'Reply all',
  'action.transferer': 'Forward',
  'action.archiver': 'Archive',
  'action.supprimer': 'Delete',
  'action.envoyer': 'Send',
  'action.annuler': 'Cancel',
  'action.continuer': 'Continue',
  'action.fermer': 'Close',
  'action.replier': 'Collapse',
  'action.retirer': 'Remove',
  'action.termine': 'Done',

  // --- Toasts -----------------------------------------------------------
  'toast.compteAjoute': 'Account added.',
  'toast.compteRetire': 'Account removed.',
  'toast.archivee': 'Conversation archived.',
  'toast.supprimee': 'Conversation deleted.',
  'toast.pieceEnregistree': 'Attachment saved: {chemin}',
  'toast.brouillonEnregistre': 'Draft saved.',
  'toast.brouillonFork': 'This draft had changed elsewhere — your version was kept separately.',
  'toast.envoye': 'Message sent.',
  'toast.echoAttente': 'Copy still syncing — try again in a moment.',

  // --- Enveloppes d'erreur (le détail du cœur reste verbatim, L-3) -----
  'erreur.renvoi': 'Could not resend: {err}',
  'erreur.abandon': 'Could not discard: {err}',
  'erreur.maj': 'Update failed: {err}',
  'erreur.ouverture': 'Could not open: {err}',
  'erreur.preference': 'Preference not saved: {err}',
  'erreur.enregistrement': 'Could not save: {err}',
  'erreur.transfert': 'Could not forward: {err}',
  'erreur.repondreTous': 'Could not reply all: {err}',
  'erreur.envoi': 'Could not send: {err}',
  'erreur.piece': 'Could not attach: {err}',
  'erreur.piecesManquantes':
    'Some forwarded files are still missing — wait for retrieval, try again, or remove them before sending.',
  'erreur.aucunCompte': 'No sending account — add an account.',
  'erreur.connexion': 'Could not connect: {err}',

  // --- Liste ------------------------------------------------------------
  'liste.aria': 'Message list',
  'liste.aucunResultat': 'No results.',
  'liste.vide': 'No messages here.',
  'liste.prefixeBrouillon': 'Draft — ',
  'brouillons.a': 'To: {a}',
  'brouillons.sansDestinataire': '(no recipient)',
  'brouillons.sansObjet': '(no subject)',
  'puce.messages': '{n} message|{n} messages',
  'puce.fichiers': '{n} file|{n} files',
  'onglet.tous': 'All',
  'onglet.nonlus': 'Unread',

  // --- Volet de lecture -------------------------------------------------
  'lecture.aria': 'Message',
  'lecture.vide': 'Select a message to read it.',
  'lecture.dernier': 'Latest message · {quand}',
  'lecture.voirConversation': 'View conversation',
  'lecture.a': 'to {adresse}',
  'lecture.imagesBloquees': '{n} remote image blocked to protect your privacy.|{n} remote images blocked to protect your privacy.',
  'lecture.afficherImages': 'Show images',
  'lecture.corps': 'Message content',
  'lecture.enregistrer': 'Save to Downloads',

  // --- Conversation (écran 03) ------------------------------------------
  'conv.toutDeplier': 'Expand all',
  'conv.brouillon': 'Draft',
  'conv.de': 'From',
  'conv.a': 'To',
  'conv.objet': 'Subject',
  'conv.fichiersJoints': 'Attachments',

  // --- Composition ------------------------------------------------------
  'compo.nouveau': 'New message',
  'compo.re': 'Re: {sujet}',
  'compo.tr': 'Fwd: {sujet}',
  'compo.bonjour': 'Hello {prenom},',
  'compo.sansObjet': 'no subject',
  'compo.independante': 'Pop out',
  'compo.compteEmetteur': 'Sending account',
  'compo.destinataire': 'Recipient',
  'compo.objetPlaceholder': 'Message subject',
  'compo.corpsPlaceholder': 'Your message…',
  'compo.cc': 'Cc',
  'compo.cci': 'Bcc',
  'compo.gras': 'B',
  'compo.italique': 'I',
  'compo.souligne': 'U',
  'compo.liste': 'List',
  'compo.lien': 'Link',
  'compo.citation': 'Quote',
  'compo.joindre': 'Attach',
  'compo.retirerPiece': 'Remove {nom}',
  'compo.rapatriement': '{nom} — retrieving…',
  'compo.poidsTotal': '{poids} / 25 MB',
  'compo.pieceRefusee': '"{nom}" exceeds the remaining space ({reste}).',
  'compo.enregistrerBrouillon': 'Save draft',

  // --- Écran 01 et guichet de compte ------------------------------------
  'onboarding.titre1': 'Your address.',
  'onboarding.titre2': "That's it.",
  'guichet.adresse': 'Email address',
  'guichet.mdp': 'Password',
  'guichet.imap': 'IMAP server',
  'guichet.smtp': 'SMTP server',
  'guichet.port': 'Port',
  'guichet.adresseInvalide': 'Enter your full email address.',
  'guichet.autorisation': 'Authorization in progress in your browser…',
  'guichet.verification': 'Checking the connection to the server…',
  'guichet.noteGenerique': "Enter your provider's servers — the password goes to the system vault, never a file.",
  'guichet.noteAuto': 'The server is detected automatically. Nothing else to set.',

  // --- Modale de migration ----------------------------------------------
  'migration.aria': 'Message database update',
  'migration.titre': 'Your messages become conversations.',
  'migration.note': 'About {n} messages will be reorganized into conversations. This update runs only once and deletes nothing.',
  'migration.preparation': 'Preparing…',
  'migration.pourcent': '{p}%',
  'migration.annulee': 'Update canceled — everything is back as before. It will resume at the next launch, or right away:',
  'migration.echec': 'The update failed ({err}). Nothing is lost: it can be run again.',

  // --- Réglages ---------------------------------------------------------
  'reglages.groupesAria': 'Settings groups',
  'groupe.comptes': 'Accounts',
  'groupe.themes': 'Themes',
  'groupe.affichage': 'Display',
  'groupe.notifications': 'Notifications',
  'groupe.raccourcis': 'Shortcuts',
  'groupe.apropos': 'About',
  'reglages.sectionThemes': 'Color theme',
  'reglages.sectionRaccourcis': 'Keyboard shortcuts',
  'reglages.ajouterCompte': 'Add an account',
  'reglages.retirerCompte': 'Remove {email}',
  'reglages.retirerConfirme': 'Remove {email}? Its local mail is erased and its connection forgotten. Nothing is deleted on the server.',
  'reglages.retraitEnCours': 'Removing…',
  'reglages.retraitImpossible': 'Removal failed — {err}',
  'reglages.sombreAuto': 'Automatic dark',
  'reglages.sombreAutoDesc': 'Follow the system dark setting: “Night” shows while it is on, your chosen theme returns as soon as it turns off.',
  'reglages.langue': 'Language',
  'reglages.langueDesc': 'The interface language, applied immediately.',
  'reglages.bulles': 'Arrival notifications',
  'reglages.bullesDesc': 'A system notification announces new messages at sync. Turning it off never stops the sync itself.',
  'reglages.noteRaccourcis': 'In a text field, letters are letters again — only Esc keeps a meaning.',
  'reglages.version': 'Version',
  'reglages.maj': 'Updates',
  'reglages.verifierMaj': 'Check for updates',
  'reglages.verification': 'Checking…',
  'reglages.ajour': 'You are up to date.',
  'reglages.majDisponible': 'Version {version} available.',
  'reglages.majImpossible': 'Check failed — {err}',
  'reglages.installation': 'Downloading and installing…',
  'reglages.icones': 'Icons',
  'reglages.iconesValeur': 'Material Symbols Rounded (Google), Apache 2.0 license — bundled font, no network.',

  // --- Raccourcis (table D3, référence) ---------------------------------
  'raccourci.touche.c': 'c',
  'raccourci.touche.r': 'r',
  'raccourci.touche.f': 'f',
  'raccourci.touche.e': 'e',
  'raccourci.touche.suppr': 'Del',
  'raccourci.touche.slash': '/',
  'raccourci.touche.echap': 'Esc',
  'raccourci.geste.c': 'Compose a new message',
  'raccourci.geste.r': 'Reply to the selected conversation',
  'raccourci.geste.f': 'Forward the selected conversation',
  'raccourci.geste.e': 'Archive the selected conversation',
  'raccourci.geste.suppr': 'Delete the selected conversation',
  'raccourci.geste.slash': 'Go to search',
  'raccourci.geste.echap': 'Close the overlay, leave the field, return to the inbox',

  // --- Thèmes Clarity (fiches du dialogue Réglages) ---------------------
  'theme.air.nom': 'Air',
  'theme.air.desc': 'Pale skies and light blue, plenty of breathing room.',
  'theme.feu.nom': 'Fire',
  'theme.feu.desc': 'Warm sands and embers, a deep orange accent.',
  'theme.eau.nom': 'Water',
  'theme.eau.desc': 'Water greens and teal, a cool mineral background.',
  'theme.astres.nom': 'Stars',
  'theme.astres.desc': 'Blue-tinted grays and indigo, a light nocturnal glow.',
  'theme.terre.nom': 'Earth',
  'theme.terre.desc': 'Clay, ochre and linen, a terracotta accent.',
  'theme.nature.nom': 'Nature',
  'theme.nature.desc': 'Pine green on ivory — the current direction.',
  'theme.nuit.nom': 'Night',
  'theme.nuit.desc': 'Dark surfaces, light ink, softened pine. Dark theme.',

  // --- Langues (chaque langue se nomme dans SA langue) ------------------
  'langue.fr': 'Français',
  'langue.en': 'English',

  // --- Dates (quand.js) — transposition de la grammaire du prototype ----
  'quand.mois': [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
  ],
  'quand.jours': [
    'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday',
  ],
  'quand.hier': 'Yesterday',
  'quand.aujourdhui': 'Today',
  'quand.premier': '1',
  'quand.dansAnnee': '{mois} {jour}',
  'quand.auDela': '{mois} {jour}, {annee}',
};
