//! Composing an outgoing message: the validation boundary.
//!
//! Everything WE produce is strict (unlike display, which tolerates the
//! real world): addresses validated one by one, subject flattened to a
//! single line (no header injection possible), Message-ID generated by
//! us BEFORE sending — it is what makes an interrupted send correlatable
//! to the message that actually went out (the "never a phantom" rule).

use std::collections::hash_map::RandomState;
use std::hash::{BuildHasher, Hasher};
use std::time::{SystemTime, UNIX_EPOCH};

use crate::address::EmailAddress;
use crate::error::Error;

/// A message ready to enter the outbox: everything in it is validated.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Draft {
    /// Message-ID per RFC 5322, angle brackets included, generated by us.
    pub message_id: String,
    pub from: String,
    /// Validated recipients — never empty.
    pub to: Vec<String>,
    /// Carbon copy, validated — can be empty.
    pub cc: Vec<String>,
    /// Blind carbon copy, validated — can be empty. NEVER appears in
    /// the headers of the message served to others (the send carries it
    /// in the SMTP envelope alone, mail-smtp) — that is its whole point.
    pub bcc: Vec<String>,
    pub subject: String,
    pub body_text: String,
    /// Rich body (PLAN-COMPOSITION-HTML), already sanitized by the caller
    /// (the ammonia boundary lives on the app side, the only crate that
    /// depends on mail-render). `None` = text-only send, the legacy path.
    /// `compose()` returns `None`; the caller that has HTML sets it —
    /// the text field ALWAYS stays populated, it is the fallback.
    pub body_html: Option<String>,
    /// Message-ID of the message being replied to (thread).
    pub in_reply_to: Option<String>,
    /// The `References` chain (RFC 5322 §3.6.4): the parent's + its own
    /// Message-ID — read from the database by `Store::references_of` (E7).
    /// `None` = the parent alone (`in_reply_to`), the previous path.
    pub references: Option<String>,
    /// Marked "important" by the sender (PLAN-RETOURS-6, R3): the send
    /// will carry the headers `X-Priority: 1` + `Importance: high` — the
    /// pair mature clients set. `compose()` returns `false`; the caller
    /// that has the gesture sets it.
    pub important: bool,
    /// The iTIP reply of an invitation (PLAN-INVITATIONS): the
    /// `METHOD:REPLY` text that delivery will carry in a
    /// `text/calendar; method=REPLY` part. `compose()` returns `None`;
    /// the caller replying to an invitation sets it.
    pub ics_reply: Option<String>,
}

/// Validates and assembles a draft ready to be logged.
///
/// `to_raw`/`cc_raw`/`bcc_raw` accept several addresses separated by
/// commas or semicolons; each must be valid, otherwise everything is
/// refused (fail fast at the boundary). `to_raw` cannot be empty; Cc and
/// Bcc can. `in_reply_to` is the Message-ID of the original message as
/// reported by the server — normalized here.
pub fn compose(
    from: &str,
    to_raw: &str,
    cc_raw: &str,
    bcc_raw: &str,
    subject: &str,
    body_text: &str,
    in_reply_to: Option<&str>,
) -> Result<Draft, Error> {
    let from = EmailAddress::parse(from)?;
    let to = parse_recipients(to_raw)?;
    if to.is_empty() {
        return Err(Error::InvalidEmailAddress(to_raw.to_string()));
    }
    let cc = parse_recipients(cc_raw)?;
    let bcc = parse_recipients(bcc_raw)?;
    Ok(Draft {
        message_id: generate_message_id(&from),
        from: from.to_string(),
        to,
        cc,
        bcc,
        subject: single_line(subject),
        body_text: body_text.to_string(),
        body_html: None,
        in_reply_to: in_reply_to.and_then(normalize_message_id),
        references: None,
        important: false,
        ics_reply: None,
    })
}

/// Validates a list of addresses (commas or semicolons): each one strict,
/// a single invalid one refuses all of them. Returns an empty list on an
/// empty input — the caller decides whether empty is allowed (To: no; Cc,
/// Bcc: yes).
fn parse_recipients(raw: &str) -> Result<Vec<String>, Error> {
    raw.split([',', ';'])
        .filter(|part| !part.trim().is_empty())
        .map(|part| EmailAddress::parse(part).map(|address| address.to_string()))
        .collect()
}

/// Pre-filled subject of a reply: "Re: " without stacking — never
/// "Re: Re:", including against Outlook's French-style "RE :".
pub fn reply_subject(original: Option<&str>) -> String {
    match original
        .map(str::trim)
        .filter(|subject| !subject.is_empty())
    {
        Some(subject) => {
            let lower = subject.to_lowercase();
            if lower.starts_with("re:") || lower.starts_with("re :") {
                // lang:fr
                subject.to_string()
            } else {
                format!("Re: {subject}")
            }
        }
        None => "Re:".to_string(),
    }
}

/// Pre-filled subject of a forward: "Fwd: " without stacking, tolerant of
/// variants seen in the field (Outlook French "Tr :", "Fw:"…).
pub fn forward_subject(original: Option<&str>) -> String {
    match original
        .map(str::trim)
        .filter(|subject| !subject.is_empty())
    {
        Some(subject) => {
            let lower = subject.to_lowercase();
            let already = ["fwd:", "fwd :", "fw:", "fw :", "tr:", "tr :"] // lang:fr
                .iter()
                .any(|prefix| lower.starts_with(prefix));
            if already {
                subject.to_string()
            } else {
                format!("Fwd: {subject}")
            }
        }
        None => "Fwd:".to_string(),
    }
}

/// Recipients of a "Reply all", To and Cc KEPT SEPARATE (CE verdict D3,
/// PLAN-RETOURS-2): the To field receives the sender then the original
/// To addresses; the Cc field receives the original Cc addresses — Cc
/// stays Cc instead of being flattened into To. No duplicates
/// (case-insensitive comparison), never your own address (writing to
/// yourself would be noise), and never putting someone already placed in
/// To back into Cc. Either list can be EMPTY: a message you sent only to
/// yourself has no one else — the caller decides.
pub fn reply_all_split(
    sender: Option<&str>,
    to: &[String],
    cc: &[String],
    own_address: &str,
) -> (Vec<String>, Vec<String>) {
    let own = own_address.trim().to_lowercase();
    let mut seen: Vec<String> = Vec::new();
    let mut add = |dest: &mut Vec<String>, candidate: &str| {
        let address = candidate.trim();
        if address.is_empty() {
            return;
        }
        let key = address.to_lowercase();
        if key == own || seen.contains(&key) {
            return;
        }
        seen.push(key);
        dest.push(address.to_string());
    };
    let mut to_out = Vec::new();
    for candidate in sender.into_iter().chain(to.iter().map(String::as_str)) {
        add(&mut to_out, candidate);
    }
    let mut cc_out = Vec::new();
    for candidate in cc {
        add(&mut cc_out, candidate);
    }
    (to_out, cc_out)
}

/// Who a SIMPLE reply ("Reply") addresses — R4, PLAN-RETOURS-3, field
/// finding of 2026-08-18.
///
/// On a RECEIVED message: the sender, as always. On OUR OWN message (the
/// sender is the account), replying to the sender would write to
/// ourselves; so we target the ORIGINAL recipients (the message's To),
/// i.e. writing back to the same group. The list can be EMPTY — a
/// received message with no known sender, or an old send whose
/// recipients are not yet in the database: the caller decides the
/// fallback (poll the server, or fail outright).
pub fn reply_to(
    is_own: bool,
    sender: Option<&str>,
    to_addrs: &[String],
    reply_to: Option<&str>,
) -> Vec<String> {
    // `Reply-To` says where the sender wants the reply (mailing lists,
    // notifications) — it takes priority over `From` (PLAN-AUDIT-V2 E5),
    // except on your own message, where you write back to the same group.
    let reply_to = reply_to
        .map(str::trim)
        .filter(|address| !address.is_empty());
    if !is_own && let Some(address) = reply_to {
        return vec![address.to_string()];
    }
    if is_own {
        to_addrs
            .iter()
            .map(|address| address.trim())
            .filter(|address| !address.is_empty())
            .map(str::to_string)
            .collect()
    } else {
        sender
            .map(str::trim)
            .filter(|address| !address.is_empty())
            .map(|address| vec![address.to_string()])
            .unwrap_or_default()
    }
}

/// The attribution line of a quote — the SINGLE authority for both
/// variants (text and rich): a label that changes changes everywhere.
fn attribution(sender: Option<&str>, date: Option<&str>) -> String {
    let sender = sender.unwrap_or("(expéditeur inconnu)"); // lang:fr
    match date {
        Some(date) => format!("Le {date}, {sender} a écrit :"), // lang:fr
        None => format!("{sender} a écrit :"),                  // lang:fr
    }
}

/// The header of a forward (separator, From/Date/Subject) — same rule:
/// a single source for both the text and rich variants.
fn forward_header(sender: Option<&str>, date: Option<&str>, subject: Option<&str>) -> String {
    let mut header = String::from("---------- Message transféré ----------\n"); // lang:fr
    header.push_str(&format!(
        "De : {}\n",                              // lang:fr
        sender.unwrap_or("(expéditeur inconnu)")  // lang:fr
    ));
    if let Some(date) = date {
        header.push_str(&format!("Date : {date}\n")); // lang:fr
    }
    header.push_str(&format!("Objet : {}", subject.unwrap_or("(sans objet)"))); // lang:fr
    header
}

/// Quote block of a reply, to place BELOW the cursor (top-posting): an
/// attribution line then every line of the text prefixed with "> ".
pub fn quote_reply(sender: Option<&str>, date: Option<&str>, body_text: &str) -> String {
    if body_text.trim().is_empty() {
        return String::new();
    }
    let quoted: String = body_text
        .lines()
        .map(|line| format!("> {line}\n"))
        .collect();
    format!("\n\n{}\n{}", attribution(sender, date), quoted.trim_end())
}

/// Rich quote of a reply (PLAN-COMPOSITION-HTML): the ESCAPED attribution
/// (the sender comes from the real world), then the body — already
/// sanitized by the caller — inside a `<blockquote>` with a left rule,
/// the shape every mature client gives quoted text. The inline style goes
/// through `clean_style` (no url, no execution) and the allowlist.
pub fn quote_reply_html(sender: Option<&str>, date: Option<&str>, body_html: &str) -> String {
    if body_html.trim().is_empty() {
        return String::new();
    }
    format!(
        "<br><br>{}<blockquote style=\"margin:0 0 0 0.8ex;border-left:2px solid #ccc;padding-left:1ex\">{body_html}</blockquote>",
        crate::echo::text_as_html(&attribution(sender, date)),
    )
}

/// Rich block of a forward: the original header (From/Date/Subject)
/// escaped, then the HTML body as is — a forward transmits.
/// The attribute that marks the forwarded block in a composed body
/// (PLAN-AUDIT-V2 E10, D8). Its value names the source
/// (`account/uid/mailbox`): on send, [`substitute_forward`] replaces
/// everything that follows with the render WITH remote images — the
/// composer itself loaded none.
pub const FORWARD_MARKER: &str = "data-wind-transfert";

pub fn quote_forward_html(
    sender: Option<&str>,
    date: Option<&str>,
    subject: Option<&str>,
    body_html: &str,
    source: Option<&str>,
) -> String {
    let opening = match source {
        Some(source) => format!("<div {FORWARD_MARKER}=\"{}\">", escape_attribute(source)),
        None => "<div>".to_string(),
    };
    // The editable blank line AFTER the block (field, STOP 2, 2026-09-02):
    // in a contenteditable, the cursor placed after the last block falls
    // INSIDE it — a word typed "after" used to live inside the marked
    // `<div>`, and the send-time substitution swept it away too. Here,
    // the cursor has an outside.
    format!(
        "<br><br>{}<br>{opening}{body_html}</div><div><br></div>",
        crate::echo::text_as_html(&forward_header(sender, date, subject)),
    )
}

fn escape_attribute(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('"', "&quot;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// Where a forwarded block comes from: the account, the UID and the
/// mailbox of the original message — what the marker carries
/// (`account/uid/mailbox`, the mailbox last because it can contain `/`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ForwardSource {
    pub account_id: i64,
    pub uid: crate::Uid,
    pub mailbox: String,
}

impl ForwardSource {
    /// The value of the marker — the exact inverse of [`forward_source`].
    pub fn key(&self) -> String {
        format!("{}/{}/{}", self.account_id, self.uid, self.mailbox)
    }
}

/// The source of the forwarded block of a composed body, as the marker
/// carries it — `None` without a marker (reply, new message) or if the
/// value doesn't have the expected shape. Pure decision: the shell only
/// re-reads the source and substitutes (review, STANDARD §4).
pub fn forward_source(body_html: &str) -> Option<ForwardSource> {
    let key = format!("{FORWARD_MARKER}=\"");
    let start = body_html.find(&key)? + key.len();
    let end = body_html[start..].find('"')? + start;
    let value = body_html[start..end]
        .replace("&quot;", "\"")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&amp;", "&");
    let (account, rest) = value.split_once('/')?;
    let (uid, mailbox) = rest.split_once('/')?;
    Some(ForwardSource {
        account_id: account.parse().ok()?,
        uid: uid.parse().ok()?,
        mailbox: mailbox.to_string(),
    })
}

/// Replaces the forwarded block — the marked `<div>`, up to ITS closing
/// tag (nested `<div>`s in the quoted mail are counted) — with
/// `fresh_body` (the render with its remote images). What the user typed
/// BEFORE and AFTER the block stays; an edit INSIDE the block is lost
/// (a stated limit: we forward, we don't comment line by line). A block
/// that is never closed is replaced up to the end.
pub fn substitute_forward(body_html: &str, fresh_body: &str) -> String {
    // By the ATTRIBUTE, then the tag that carries it (review): an editor
    // that sets `style` or `class` before the marker doesn't make it miss.
    let key = format!(" {FORWARD_MARKER}=");
    let Some(attribute) = body_html.find(&key) else {
        return body_html.to_string();
    };
    let Some(start) = body_html[..attribute].rfind('<') else {
        return body_html.to_string();
    };
    let end = block_end(&body_html[start..]).map_or(body_html.len(), |l| start + l);
    format!(
        "{}<div>{fresh_body}</div>{}",
        &body_html[..start],
        &body_html[end..]
    )
}

/// The length of the first `<div …>…</div>` element of `html`, nested
/// closings included — `None` if it is never closed. Case-insensitive
/// (the composer may rewrite `<DIV>`).
fn block_end(html: &str) -> Option<usize> {
    // On BYTES, never `str[i..]`: advancing byte by byte used to land in
    // the middle of an "é" and panic (gate andon, 2026-09-02). The tags
    // being searched for are ASCII: the returned index is a character
    // boundary.
    let lower = html.to_ascii_lowercase();
    let lower = lower.as_bytes();
    let mut depth = 0usize;
    let mut i = 0;
    while i < lower.len() {
        if lower[i..].starts_with(b"</div") {
            depth = depth.checked_sub(1)?;
            let close = lower[i..].iter().position(|&c| c == b'>')? + i + 1;
            if depth == 0 {
                return Some(close);
            }
            i = close;
        } else if lower[i..].starts_with(b"<div") {
            depth += 1;
            i += 4;
        } else {
            i += 1;
        }
    }
    None
}

/// Block of a forward: the original header (From/Date/Subject) then the
/// text as is — a forward transmits, it doesn't comment line by line.
pub fn quote_forward(
    sender: Option<&str>,
    date: Option<&str>,
    subject: Option<&str>,
    body_text: &str,
) -> String {
    format!(
        "\n\n{}\n\n{}",
        forward_header(sender, date, subject),
        body_text.trim_end(),
    )
}

/// A subject lives on a single line: every control character becomes a
/// space — the header-injection path is cut off at the source.
fn single_line(subject: &str) -> String {
    subject
        .trim()
        .chars()
        .map(|c| if c.is_control() { ' ' } else { c })
        .collect()
}

/// A Message-ID is used with angle brackets (RFC 5322); some servers omit
/// them in their ENVELOPE responses — normalize here, once.
fn normalize_message_id(id: &str) -> Option<String> {
    let bare = id.trim().trim_matches(['<', '>']);
    if bare.is_empty() {
        None
    } else {
        Some(format!("<{bare}>"))
    }
}

/// Unique Message-ID, generated BEFORE any send attempt.
///
/// `RandomState` is randomly seeded by the system on each instance:
/// combined with the nanosecond clock, uniqueness is guaranteed without
/// an extra dependency.
fn generate_message_id(from: &EmailAddress) -> String {
    let domain = from.as_str().rsplit('@').next().unwrap_or("localhost");
    let epoch = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default();
    let random = RandomState::new().build_hasher().finish();
    format!("<{}.{:016x}@{}>", epoch.as_nanos(), random, domain)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn compose_simple(to_raw: &str) -> Result<Draft, Error> {
        compose("me@example.fr", to_raw, "", "", "Subject", "Body", None)
    }

    #[test]
    fn validates_cc_and_bcc_like_the_to_field() {
        let draft = compose(
            "me@example.fr",
            "a@example.fr",
            "b@example.fr, c@example.fr",
            "secret@example.fr",
            "Subject",
            "Body",
            None,
        )
        .unwrap();
        assert_eq!(draft.to, vec!["a@example.fr"]);
        assert_eq!(draft.cc, vec!["b@example.fr", "c@example.fr"]);
        assert_eq!(draft.bcc, vec!["secret@example.fr"]);
    }

    #[test]
    fn empty_cc_and_bcc_mean_empty_list() {
        let draft = compose_simple("a@example.fr").unwrap();
        assert!(draft.cc.is_empty());
        assert!(draft.bcc.is_empty());
    }

    #[test]
    fn an_invalid_cc_or_bcc_address_refuses_everything() {
        assert!(
            compose(
                "me@example.fr",
                "a@example.fr",
                "not-an-address",
                "",
                "s",
                "c",
                None
            )
            .is_err()
        );
        assert!(
            compose(
                "me@example.fr",
                "a@example.fr",
                "",
                "x\r\ny@z.fr",
                "s",
                "c",
                None
            )
            .is_err()
        );
    }

    #[test]
    fn composes_multiple_recipients_from_comma_or_semicolon_list() {
        let draft = compose_simple(" a@example.fr , b@example.fr ; c@example.fr ").unwrap();
        assert_eq!(
            draft.to,
            vec!["a@example.fr", "b@example.fr", "c@example.fr"]
        );
        assert_eq!(draft.from, "me@example.fr");
    }

    #[test]
    fn rejects_the_whole_draft_if_any_recipient_is_invalid() {
        assert!(compose_simple("a@example.fr, not-an-address").is_err());
    }

    #[test]
    fn rejects_empty_recipient_list() {
        assert!(compose_simple("").is_err());
        assert!(compose_simple("  ,  ; ").is_err());
    }

    #[test]
    fn rejects_invalid_sender() {
        assert!(compose("not-an-address", "a@example.fr", "", "", "s", "c", None).is_err());
    }

    #[test]
    fn generates_unique_well_formed_message_ids() {
        let first = compose_simple("a@example.fr").unwrap();
        let second = compose_simple("a@example.fr").unwrap();
        assert_ne!(first.message_id, second.message_id);
        assert!(first.message_id.starts_with('<'));
        assert!(first.message_id.ends_with("@example.fr>"));
    }

    /// Header injection through the subject is neutralized at the source.
    #[test]
    fn subject_is_flattened_to_a_single_line() {
        let draft = compose(
            "me@example.fr",
            "a@example.fr",
            "",
            "",
            "Alert\r\nBcc: spy@mal.example",
            "Body",
            None,
        )
        .unwrap();
        assert!(!draft.subject.contains('\r'));
        assert!(!draft.subject.contains('\n'));
        assert!(draft.subject.contains("Bcc: spy@mal.example"));
    }

    #[test]
    fn body_newlines_are_preserved_verbatim() {
        let draft = compose(
            "me@example.fr",
            "a@example.fr",
            "",
            "",
            "s",
            "line 1\nline 2",
            None,
        )
        .unwrap();
        assert_eq!(draft.body_text, "line 1\nline 2");
    }

    #[test]
    fn normalizes_in_reply_to_with_angle_brackets() {
        let with = compose(
            "me@example.fr",
            "a@example.fr",
            "",
            "",
            "s",
            "c",
            Some("<id@x.y>"),
        )
        .unwrap();
        assert_eq!(with.in_reply_to.as_deref(), Some("<id@x.y>"));
        let without = compose(
            "me@example.fr",
            "a@example.fr",
            "",
            "",
            "s",
            "c",
            Some("id@x.y"),
        )
        .unwrap();
        assert_eq!(without.in_reply_to.as_deref(), Some("<id@x.y>"));
        let blank = compose(
            "me@example.fr",
            "a@example.fr",
            "",
            "",
            "s",
            "c",
            Some("  "),
        )
        .unwrap();
        assert_eq!(blank.in_reply_to, None);
    }

    #[test]
    fn reply_subject_prefixes_exactly_once() {
        assert_eq!(reply_subject(Some("Meeting")), "Re: Meeting");
        assert_eq!(reply_subject(Some("Re: Meeting")), "Re: Meeting");
        assert_eq!(reply_subject(Some("RE : Meeting")), "RE : Meeting"); // lang:fr
        assert_eq!(reply_subject(Some("  ")), "Re:");
        assert_eq!(reply_subject(None), "Re:");
    }

    #[test]
    fn forward_subject_prefixes_exactly_once() {
        assert_eq!(forward_subject(Some("Meeting")), "Fwd: Meeting");
        assert_eq!(forward_subject(Some("Fwd: Meeting")), "Fwd: Meeting");
        assert_eq!(forward_subject(Some("TR : Meeting")), "TR : Meeting"); // lang:fr
        assert_eq!(forward_subject(Some("Fw: Meeting")), "Fw: Meeting");
        assert_eq!(forward_subject(None), "Fwd:");
    }

    /// A "Re: " is not a "Fwd: ": forwarding a reply still prefixes it.
    #[test]
    fn forward_subject_still_prefixes_a_reply_subject() {
        assert_eq!(forward_subject(Some("Re: Meeting")), "Fwd: Re: Meeting");
    }

    #[test]
    fn reply_all_split_orders_sender_then_to_then_cc_without_self() {
        let to = vec!["me@example.fr".to_string(), "bob@example.fr".to_string()];
        let cc = vec!["carole@example.fr".to_string()];
        let (to_out, cc_out) = reply_all_split(Some("alice@example.fr"), &to, &cc, "me@example.fr");
        assert_eq!(to_out, vec!["alice@example.fr", "bob@example.fr"]);
        assert_eq!(cc_out, vec!["carole@example.fr"]);
    }

    /// D3: the original Cc addresses stay in Cc; a Cc already placed in
    /// To (bob) is not put back there.
    #[test]
    fn reply_all_split_keeps_the_cc_in_cc() {
        let to = vec!["me@example.fr".to_string(), "bob@example.fr".to_string()];
        let cc = vec![
            "carole@example.fr".to_string(),
            "bob@example.fr".to_string(),
        ];
        let (to_out, cc_out) = reply_all_split(Some("alice@example.fr"), &to, &cc, "me@example.fr");
        assert_eq!(to_out, vec!["alice@example.fr", "bob@example.fr"]);
        assert_eq!(cc_out, vec!["carole@example.fr"]);
    }

    /// Case doesn't make two addresses: "Bob@" and "bob@" only produce
    /// one recipient, and "ME@" stays self.
    #[test]
    fn reply_all_split_dedupes_case_insensitively() {
        let to = vec!["Bob@Example.fr".to_string(), "ME@example.fr".to_string()];
        let cc = vec!["bob@example.fr".to_string(), "alice@example.fr".to_string()];
        let (to_out, cc_out) = reply_all_split(Some("alice@example.fr"), &to, &cc, "me@example.fr");
        assert_eq!(to_out, vec!["alice@example.fr", "Bob@Example.fr"]);
        assert!(cc_out.is_empty(), "bob and alice are already in To");
    }

    /// A message sent only to yourself: no one else — both lists are
    /// empty, it is up to the caller to decide (fall back to the sender).
    #[test]
    fn reply_all_split_can_be_empty_when_alone() {
        let to = vec!["me@example.fr".to_string()];
        let (to_out, cc_out) = reply_all_split(Some("me@example.fr"), &to, &[], "me@example.fr");
        assert!(to_out.is_empty());
        assert!(cc_out.is_empty());
    }

    #[test]
    fn reply_all_split_ignores_blanks_and_a_missing_sender() {
        let to = vec!["  ".to_string(), "bob@example.fr".to_string()];
        let (to_out, _) = reply_all_split(None, &to, &[], "me@example.fr");
        assert_eq!(to_out, vec!["bob@example.fr"]);
    }

    /// Simple reply to a RECEIVED message: the sender, one only.
    /// PLAN-AUDIT-V2 E5: "Reply" used to go to `From` even when the
    /// message carried a `Reply-To` (mailing lists, notifications) — the
    /// header was dropped by the adapter. On your OWN message, `Reply-To`
    /// changes nothing: you write back to the same group.
    #[test]
    fn reply_targets_reply_to() {
        assert_eq!(
            reply_to(false, Some("list@x.fr"), &[], Some("bob@y.fr")),
            vec!["bob@y.fr".to_string()]
        );
        let to = vec!["group@x.fr".to_string()];
        assert_eq!(
            reply_to(true, Some("me@example.fr"), &to, Some("bob@y.fr")),
            to
        );
        assert_eq!(
            reply_to(false, Some("list@x.fr"), &[], Some("  ")),
            vec!["list@x.fr".to_string()],
            "an empty Reply-To is worth nothing"
        );
    }

    /// PLAN-AUDIT-V2 E10, CE decision D8: "Forward" loads NO remote image
    /// into the composer (the tracking pixel used to fire on click,
    /// "Cancel" didn't undo it); on send, the forwarded block is replaced
    /// by the render WITH the real URLs — the recipient gets the same
    /// message.
    /// Gate andon (2026-09-02): "transféré" in the block — a non-ASCII
    /// byte made `block_end` PANIC (slicing a `str` off a character
    /// boundary); the async task crashed and `queue_send` never answered:
    /// composition frozen, no toast, no error. The review's test only had
    /// ASCII.
    #[test]
    fn an_accented_block_substitutes_without_panicking() {
        let body = format!(
            "<p>Salut é</p><div {FORWARD_MARKER}=\"1/17/INBOX\">             <p>Message transféré — été</p><div>à</div></div><p>après</p>" // lang:fr
        );
        assert_eq!(
            substitute_forward(&body, "Z"),
            "<p>Salut é</p><div>Z</div><p>après</p>" // lang:fr
        );
    }

    #[test]
    fn a_forward_loads_no_remote_image_at_composition_but_renders_them_at_send() {
        let blocked = r#"<p>letter</p><img src="data:image/gif;base64,R0lGOD" alt="">"#;
        let source = ForwardSource {
            account_id: 3,
            uid: 42,
            mailbox: "INBOX".to_string(),
        };
        let compose = quote_forward_html(
            Some("Alice"),
            Some("2026-09-02"),
            Some("Letter"),
            blocked,
            Some(&source.key()),
        );
        assert!(!compose.contains("https://"), "{compose}");
        assert!(
            compose.contains(r#"data-wind-transfert="3/42/INBOX""#),
            "{compose}"
        );
        assert_eq!(forward_source(&compose), Some(source));

        // Typed BEFORE and AFTER the block: both remain (review — the
        // first version truncated everything after the marker).
        let edited = format!("<div>my word</div>{compose}<div>and my conclusion</div>");
        let fresh = r#"<p>letter</p><img src="https://x.example/p.gif" alt="">"#;
        let sent = substitute_forward(&edited, fresh);
        assert!(sent.starts_with("<div>my word</div><br><br>"), "{sent}");
        assert!(
            sent.ends_with("</div><div>and my conclusion</div>"),
            "{sent}"
        );
        assert!(sent.contains("https://x.example/p.gif"), "{sent}");
        assert!(!sent.contains("data:image"), "{sent}");
        assert!(!sent.contains("data-wind-transfert"), "{sent}");
        // Quoted mail full of nested <div>s: the closing tag found is the
        // RIGHT one, not the first one to come along.
        let nested = quote_forward_html(
            None,
            None,
            None,
            "<div><div>a</div><div>b</div></div>",
            Some("1/1/INBOX"),
        );
        let sent = substitute_forward(&format!("{nested}<p>end</p>"), "X");
        // Between the block and "end": the forward's editable blank line
        // (field, STOP 2) — it lives OUTSIDE the block, it survives.
        assert!(
            sent.ends_with("<div>X</div><div><br></div><p>end</p>"),
            "{sent}"
        );
        // The editor placed an attribute BEFORE the marker: found anyway.
        let reserialized = nested.replace(
            "<div data-wind-transfert",
            r#"<div style="x" data-wind-transfert"#,
        );
        assert!(substitute_forward(&reserialized, "Y").contains("<div>Y</div>"));
        // Without a marker (a reply, a new message): nothing moves.
        assert_eq!(substitute_forward("<p>a</p>", fresh), "<p>a</p>");
        assert_eq!(forward_source("<p>a</p>"), None);
        // A mailbox name with quotes AND `/` survives the round trip; a
        // malformed value is worth nothing.
        let weird = quote_forward_html(None, None, None, "", Some(r#"1/2/[Gmail]/Dossier "cité""#)); // lang:fr
        assert_eq!(
            forward_source(&weird),
            Some(ForwardSource {
                account_id: 1,
                uid: 2,
                mailbox: r#"[Gmail]/Dossier "cité""#.to_string() // lang:fr
            })
        );
        assert_eq!(forward_source(r#"<div data-wind-transfert="x/y/z">"#), None);
    }

    #[test]
    fn reply_to_received_targets_the_sender() {
        assert_eq!(
            reply_to(
                false,
                Some("alice@example.fr"),
                &["bob@example.fr".to_string()],
                None
            ),
            vec!["alice@example.fr"],
        );
    }

    /// THE field finding (R4): on OUR OWN message, replying targets the
    /// original recipients — never the sender (us).
    #[test]
    fn reply_to_own_targets_the_recipients_not_self() {
        let to = vec!["client@vantis.fr".to_string(), "boss@vantis.fr".to_string()];
        assert_eq!(
            reply_to(true, Some("me@example.fr"), &to, None),
            vec!["client@vantis.fr", "boss@vantis.fr"],
        );
    }

    /// Our own message WITHOUT recipients in the database (an old send
    /// never backfilled): empty list — the caller polls the server.
    #[test]
    fn reply_to_own_without_recipients_is_empty() {
        assert!(reply_to(true, Some("me@example.fr"), &[], None).is_empty());
    }

    /// Received message with no known sender: empty — the caller fails
    /// outright.
    #[test]
    fn reply_to_received_without_sender_is_empty() {
        assert!(reply_to(false, None, &["x@y.fr".to_string()], None).is_empty());
    }

    /// PLAN-COMPOSITION-HTML E2: the rich quote of a reply — an ESCAPED
    /// attribution then the sanitized body inside a blockquote. The
    /// sender comes from the real world: a name with angle brackets must
    /// never inject itself into our HTML.
    #[test]
    fn quote_reply_html_attributes_then_blockquotes() {
        let quote = quote_reply_html(
            Some("Alice <alice@ex.fr>"),
            Some("2026-08-19 10:23"),
            "<p>first</p>",
        );
        assert!(
            quote.contains("Le 2026-08-19 10:23, Alice &lt;alice@ex.fr&gt; a écrit :"), // lang:fr
            "{quote}"
        );
        assert!(
            quote.contains("<blockquote"),
            "the quoted body lives inside a blockquote: {quote}"
        );
        assert!(
            quote.contains("<p>first</p></blockquote>"),
            "the original HTML is quoted as is: {quote}"
        );
        let attribution = quote.find("a écrit :").unwrap(); // lang:fr
        let block = quote.find("<blockquote").unwrap();
        assert!(
            attribution < block,
            "the attribution precedes the block: {quote}"
        );
    }

    #[test]
    fn quote_reply_html_degrades_gracefully_without_metadata() {
        let quote = quote_reply_html(None, None, "<p>text</p>");
        assert!(quote.contains("(expéditeur inconnu) a écrit :"), "{quote}"); // lang:fr
    }

    #[test]
    fn quote_reply_html_of_empty_body_is_empty() {
        assert_eq!(quote_reply_html(Some("Alice"), None, "  \n "), "");
    }

    /// The rich block of a forward: the original header (From/Date/
    /// Subject) escaped, then the HTML body as is — a forward transmits.
    #[test]
    fn quote_forward_html_carries_headers_and_body() {
        let block = quote_forward_html(
            Some("Alice <alice@ex.fr>"),
            Some("2026-08-19 10:23"),
            Some("Quote <urgent>"),
            "<p>the body</p>",
            None,
        );
        assert!(
            block.contains("---------- Message transféré ----------"), // lang:fr
            "{block}"
        );
        assert!(block.contains("De : Alice &lt;alice@ex.fr&gt;"), "{block}"); // lang:fr
        assert!(block.contains("Date : 2026-08-19 10:23"), "{block}"); // lang:fr
        assert!(block.contains("Objet : Quote &lt;urgent&gt;"), "{block}"); // lang:fr
        assert!(
            block.contains("<p>the body</p>"),
            "the original HTML follows as is: {block}"
        );
    }

    /// Field, STOP 2, PLAN-AUDIT-V2 (2026-09-02): "a word typed AFTER the
    /// block disappeared on send". In a contenteditable, the cursor
    /// placed after the last block falls INSIDE it; the word therefore
    /// lived inside the marked `<div>`, and the substitution swept it
    /// away too. The block ends with an editable blank line — the cursor
    /// has an outside.
    #[test]
    fn a_forward_leaves_an_editable_line_after_the_block() {
        let block = quote_forward_html(None, None, None, "<p>body</p>", Some("1/2/INBOX"));
        assert!(block.ends_with("</div><div><br></div>"), "{block}");
        let without_source = quote_forward_html(None, None, None, "<p>body</p>", None);
        assert!(
            without_source.ends_with("</div><div><br></div>"),
            "{without_source}"
        );
    }

    #[test]
    fn quote_forward_html_uses_placeholders_for_missing_metadata() {
        let block = quote_forward_html(None, None, None, "<p>body</p>", None);
        assert!(block.contains("De : (expéditeur inconnu)"), "{block}"); // lang:fr
        assert!(!block.contains("Date :"), "{block}");
        assert!(block.contains("Objet : (sans objet)"), "{block}"); // lang:fr
    }

    #[test]
    fn quote_reply_attributes_and_prefixes_every_line() {
        let quote = quote_reply(
            Some("Alice Martin"),
            Some("2026-07-17 10:23"),
            "first line\n\nsecond line",
        );
        assert!(quote.starts_with("\n\nLe 2026-07-17 10:23, Alice Martin a écrit :\n")); // lang:fr
        assert!(quote.contains("> first line"));
        assert!(quote.contains("> second line"));
        assert!(
            !quote.contains("\n\n>"),
            "blank lines stay quoted: {quote:?}"
        );
    }

    #[test]
    fn quote_reply_degrades_gracefully_without_metadata() {
        let quote = quote_reply(None, None, "text");
        assert!(quote.contains("(expéditeur inconnu) a écrit :")); // lang:fr
        assert!(quote.contains("> text"));
    }

    #[test]
    fn quote_reply_of_empty_body_is_empty() {
        assert_eq!(quote_reply(Some("Alice"), None, "  \n "), "");
    }

    #[test]
    fn quote_forward_carries_original_headers_and_text() {
        let block = quote_forward(
            Some("Alice Martin"),
            Some("2026-07-17 10:23"),
            Some("Meeting"),
            "the body\non two lines\n",
        );
        assert!(block.contains("---------- Message transféré ----------")); // lang:fr
        assert!(block.contains("De : Alice Martin")); // lang:fr
        assert!(block.contains("Date : 2026-07-17 10:23")); // lang:fr
        assert!(block.contains("Objet : Meeting")); // lang:fr
        assert!(block.ends_with("the body\non two lines"));
    }

    #[test]
    fn quote_forward_uses_placeholders_for_missing_metadata() {
        let block = quote_forward(None, None, None, "body");
        assert!(block.contains("De : (expéditeur inconnu)")); // lang:fr
        assert!(!block.contains("Date :"));
        assert!(block.contains("Objet : (sans objet)")); // lang:fr
    }
}
