$ErrorActionPreference = 'Stop'
$certPath = Join-Path $PSScriptRoot 'certs'
$rootKey = [System.Security.Cryptography.RSA]::Create(2048)
$rootRequest = [System.Security.Cryptography.X509Certificates.CertificateRequest]::new('CN=Wind Synthetic Test Root', $rootKey, [System.Security.Cryptography.HashAlgorithmName]::SHA256, [System.Security.Cryptography.RSASignaturePadding]::Pkcs1)
$rootRequest.CertificateExtensions.Add([System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension]::new($true, $false, 0, $true))
$rootRequest.CertificateExtensions.Add([System.Security.Cryptography.X509Certificates.X509KeyUsageExtension]::new([System.Security.Cryptography.X509Certificates.X509KeyUsageFlags]::KeyCertSign, $true))
$rootCert = $rootRequest.CreateSelfSigned([datetimeoffset]::UtcNow.AddDays(-1), [datetimeoffset]::UtcNow.AddYears(2))
$leafKey = [System.Security.Cryptography.RSA]::Create(2048)
$leafRequest = [System.Security.Cryptography.X509Certificates.CertificateRequest]::new('CN=localhost', $leafKey, [System.Security.Cryptography.HashAlgorithmName]::SHA256, [System.Security.Cryptography.RSASignaturePadding]::Pkcs1)
$leafRequest.CertificateExtensions.Add([System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension]::new($false, $false, 0, $true))
$san = [System.Security.Cryptography.X509Certificates.SubjectAlternativeNameBuilder]::new()
$san.AddDnsName('localhost')
$leafRequest.CertificateExtensions.Add($san.Build())
$oids = [System.Security.Cryptography.OidCollection]::new()
$null = $oids.Add([System.Security.Cryptography.Oid]::new('1.3.6.1.5.5.7.3.1'))
$leafRequest.CertificateExtensions.Add([System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension]::new($oids, $false))
$serial = [byte[]]::new(16)
[System.Security.Cryptography.RandomNumberGenerator]::Fill($serial)
$leafCert = $leafRequest.Create($rootCert, [datetimeoffset]::UtcNow.AddHours(-1), [datetimeoffset]::UtcNow.AddYears(1), $serial)
[System.IO.File]::WriteAllBytes((Join-Path $certPath 'root.der'), $rootCert.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Cert))
[System.IO.File]::WriteAllBytes((Join-Path $certPath 'leaf.der'), $leafCert.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Cert))
[System.IO.File]::WriteAllBytes((Join-Path $certPath 'leaf-key.der'), $leafKey.ExportPkcs8PrivateKey())
$rootKey.Dispose()
$leafKey.Dispose()
Write-Output 'Synthetic certificates created only in spike/certs; no certificate store changed.'
